pivotal/docs-tap

- getting-started/add-test-and-security.hbs.md
- scc/ootb-supply-chain-testing-scanning.hbs.md
- scst-scan/observing.hbs.md
- scst-scan/policies.hbs.md
Which other branches should this be merged with (if any)? main and please cherry-pick to 1.2 branches
> Improvements to CVE triage workflow

- app-live-view/configuring-apps/steeltoe-enablement.hbs.md
> Update ALV steeltoe page for TAP 1.3.0

- app-live-view/configuring-apps/convention-server.hbs.md
> Update ALV workload sample for TAP 1.2.1

- app-live-view/configuring-apps/convention-server.hbs.md
> Update ALV workload sample for TAP 1.2.2

- release-notes.hbs.md
> Add TAP GUI release notes for TAP 1.2.2

- getting-started/add-test-and-security.hbs.md
- scc/ootb-supply-chain-testing-scanning.hbs.md
- scst-scan/policies.hbs.md
Which other branches should this be merged with (if any)? main and please cherry-pick to 1.2.x branches
> [DRAFT] VSEE-701 modify CVE triage workflow after feedback

- app-live-view/configuring-apps/openshift.md
> Update Openshift flavor in ALV docs for 1.3.0

- release-notes.hbs.md
- scst-store/api-walkthrough.hbs.md
- scst-store/create-service-account-access-token.hbs.md
- scst-store/ingress-multicluster.hbs.md
None, this is only for Tap 1.2.2 Release
> SCST-Store Doc update for Tap 1.2.2 Release

- scst-store/troubleshooting.hbs.md
> Update Store's troubleshooting doc for TAP 1.2.2

- scst-scan/install-carbonblack-integration.hbs.md
> Remove "UnknownSeverity" from sample policy

- multicluster/reference/tap-values-view-sample.hbs.md
> openshift view profile values update

- multicluster/reference/tap-values-iterate-sample.hbs.md
> openshift iterate profile values update

- install.hbs.md
> openshift full profile shared key

- tap-gui/plugins/api-docs.hbs.md
Updated API Docs Plugin documentation with a link to the auto registration feature
> Update API Docs Plugin Documentation

- prerequisites.hbs.md
> Add openshift support details on pre-requisites

- multicluster/reference/tap-values-run-sample.hbs.md
> openshift run profile values update

- multicluster/reference/tap-values-build-sample.hbs.md
> openshift build values update

- install-components.hbs.md
- services-toolkit/install-services-toolkit.hbs.md
Just some cosmetics: bumping STK versions to the one to be released with 1.3
> Bump STK to 0.8.0

- release-notes.hbs.md
> AppSSO: add docs for upgrading to 2.0

- scst-policy/configuring.hbs.md
> Fixes typo

- app-live-view/install.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
> Update TAP profile config for ALV and version

- scc/ootb-supply-chain-testing-scanning.hbs.md
- merge with main
- cherry-pick to 1.2.x branches
> VSEE-701-cve-triage-workflow

- release-notes.hbs.md
> appsso: fix language explaining openshift SCCs

- scst-scan/install-carbonblack-integration.hbs.md
- scst-scan/install-scanners.hbs.md
> Remove duplicate steps for CBC scanner install

- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
The changes are targeted for TAP 1.3.0 only
> Update profile docs for ALV: ingressEnabled set to true

- install.hbs.md
updating the Installation to show the minimum(5) keys needed for installation.
> minimum(5) keys needed for inatallation

- release-notes.hbs.md
> VSEE-717 | For documentation of release 1.3.0 mentioned that Snyk Cli is upgraded to v1.944.0

- app-live-view/configuring-apps/spring-boot-enablement.hbs.md
- app-live-view/configuring-apps/steeltoe-enablement.hbs.md
Which other branches should this be merged with (if any)
> Update SCG and Steeltoe docs in ALV for TAP 1.3

- cli-plugins/apps/command-reference/commands-details/workload_create_update_apply.hbs.md
- cli-plugins/apps/command-reference/commands-details/workload_get.hbs.md
- cli-plugins/apps/command-reference/commands-details/workload_list.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload-apply.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload-create.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload-update.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload.hbs.md
- release-notes.hbs.md
Signed-off-by: Wendy Arango <warango@vmware.com>
> docs: Update apps plugin enhancements for TAP 1.3

- tap-gui/plugins/application-accelerator-git-repo.hbs.md
> Added supported providers to the git repo creation page

- getting-started/add-test-and-security.hbs.md
1.3.x (if possible), otherwise just main
> Added part-of labels to scan section to ensure workload loads in GUI.

- authn-authz/azure-ad.hbs.md
- authn-authz/pinniped-install-guide.hbs.md
This change also applies to 1.2.2.
> Improve Azure AD docs

- getting-started/add-test-and-security.hbs.md
- scc/ootb-supply-chain-testing-scanning.hbs.md
- scst-scan/install-carbonblack-integration.hbs.md
- scst-scan/install-snyk-integration.hbs.md
- scst-scan/policies.hbs.md
- scst-scan/results.hbs.md
- scst-scan/samples/public-image-compliance.hbs.md
- scst-scan/samples/public-source-compliance.hbs.md
- scst-scan/upgrading.hbs.md
> Vsee 719 standard sample scan policy name

- scst-scan/samples/private-image.hbs.md
- scst-scan/samples/private-source.hbs.md
> VSEE-740 More precisely specified params and examples.

- app-sso/platform-operators/rbac.md
Targeted for AppSSO `2.0.0` / TAP `1.3.0`
> Complete aggregated role RBAC for AppSSO `2.0.0`

- getting-started/consume-services.hbs.md
- getting-started/set-up-services.hbs.md
A few small updates to the consuming services guide (mostly just updating links, as well as tidy up of some of the commands).
Which other branches should this be merged with (if any)? 1.2
> Small updates to consuming services docs

- tanzu-build-service/install-airgapped.hbs.md
- tanzu-build-service/install-tbs.hbs.md
https://github.com/pivotal/build-service/issues/870
> Added legacy SBOM deprecation notice.

- tanzu-build-service/install-airgapped.hbs.md
- tanzu-build-service/install-tbs.hbs.md
> Revert "Added legacy SBOM deprecation notice."

- customize-package-installation.hbs.md
- tap-gui/non-standard-certs.hbs.md
Which other branches should this be merged with (if any)? release 1.3
> Add examples for custom ca overlays

- app-live-view/configuring-apps/steeltoe-enablement.hbs.md
> Add .net compatibility version for ALV

- release-notes.hbs.md
> document known issue in vscode extension

- install-air-gap.hbs.md
This change should be backported to v1.2
> Reconcile maven creds documentation with current state of the system

- getting-started/add-test-and-security.hbs.md
> Corrected tanzu insight command

- scc/ootb-supply-chain-testing-scanning.hbs.md
Summary:
* Updating docs pertaining to scan/policy
N/A
> Update ootb docs relating to scan

- scc/gitops-vs-regops.hbs.md
> Clearer language on PR flow requirements

- scc/ootb-supply-chain-testing-scanning.hbs.md
> Small typo fix

- cli-plugins/apps/command-reference/commands-details/workload_create_update_apply.hbs.md
- cli-plugins/apps/command-reference/commands-details/workload_get.hbs.md
- cli-plugins/apps/command-reference/commands-details/workload_list.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload-apply.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload-create.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload-update.hbs.md
- cli-plugins/apps/command-reference/tanzu-apps-workload.hbs.md
- release-notes.hbs.md
Signed-off-by: Wendy Arango <warango@vmware.com>
> docs: Update apps cli plugin docs to latest features for TAP1.3

- about-package-profiles.hbs.md
- scst-scan/overview.hbs.md
> Updates some Buildpack references to match current state

- app-sso/crds/authserver.md
- app-sso/crds/clientregistration.md
Does this cover what we wanted done [here](https://www.pivotaltracker.com/story/show/183257607)?
> appsso: clarify label selector

- intellij-extension/about.hbs.md
- intellij-extension/install.hbs.md
Which other branches should this be merged with (if any)? No, support for windows was only introduced in Tap 1.3
> document windows support for IntelliJ

- app-live-view/configuring-apps/configuring-actuator.hbs.md
> fix ALV doc in actuator endpoint config

- application-accelerator/creating-accelerators/accelerator-yaml.hbs.md
Ref https://github.com/pivotal/acc-release/issues/377
This should be backported to all previous versions
> Clarify the way dependsOn works

- scc/ootb-supply-chain-testing-with-jenkins.hbs.md
> Draft: Jenkins Adapter documentation

- scc/ootb-supply-chain-testing.hbs.md
This PR will clarify how to have multiple pipelines in a single namespace based on the 1.3 release.
> Update multi-pipeline guidance

- install.hbs.md
> Fix `imgpkg` tool name

- tap-gui/cluster-view-setup.hbs.md
> PSTAR-799 viewing cluster with version >=1.24

- prerequisites.hbs.md
We have to update the resource requirements based on the findings on TAP 1.3.0.
> Update Resource Requirements

- tap-gui/non-standard-certs.hbs.md
1.3 +
@dimitrybesson 
@andreizimin
> PSTAR-866 updated TAP custom CA cert config and verif

- release-notes.hbs.md
this should be applied to TAP v1.3 release notes.
> apps CLI Plugin and Source Controller updates

- prerequisites.hbs.md
> Updare Resource Requirements

- install-air-gap.hbs.md
> Update Airgapped section for App Live View

- release-notes.hbs.md
> Add known issue - Tanzu CLI EKS connection failure

- troubleshooting-tap/troubleshoot-using-tap.hbs.md
This change can be included in TAP 1.2 and above.
> update AWS EKS connection failure section

- tap-gui/plugins/application-accelerator-git-repo.hbs.md
> Added git repo creation configuration with secrets section

- release-notes.hbs.md
> added auto-complete feature to apps enhancements

- release-notes.hbs.md
> minor content tweaks to source controller and apps plugin

- tanzu-build-service/install-tbs.hbs.md
- tanzu-build-service/tbs-workload-config.hbs.md
> Which other branches should this be merged with (if any)?
None
> TBS: Document providing ca certs to a single workload

- scst-scan/offline-airgap.hbs.md
> Updated ytt comment section

- release-notes.hbs.md
Known issue https://jira.eng.vmware.com/browse/TANZUSC-1738 updated and added workaround.
> updated TLK known issue.

- about-package-profiles.hbs.md
- app-live-view/configuring-apps/steeltoe-enablement.hbs.md
- app-live-view/install.hbs.md
- install-air-gap.hbs.md
- vscode-extension/live-hover.hbs.md
> Update App Live View pages for 1.3.0

- about-package-profiles.hbs.md
- cloud-native-runtimes/install-cnrt.hbs.md
* update docs to reflect recent changes in tap
* change wording to reflect that TAP contour is preferred, and that CNR doesn't come with a Contour installation
* remove some broken links
* reference newest version
> update CNR install docs

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-eks.hbs.md
Doc update from TAP-GUI team for TAP 1.3.0
> Updating doc for adding and using an oidc authentication provider on eks

- release-notes.hbs.md
> Add release notes for ALV

- application-accelerator/install-app-acc.hbs.md
This applies to 1.2 and 1.3 docs
> Fix typo in acc schema

- upgrading.hbs.md
> updated the actual output from TAP 1.3.0

- multicluster/reference/tap-values-iterate-sample.hbs.md
updating shared keys into Iterate profile doc
> updating shared keys into Iterate profile doc

- multicluster/reference/tap-values-build-sample.hbs.md
Updating the TLKs into build profile as well.
> Updating the TLKs into build profile

- install.hbs.md
updating the TAP 1.3.0 component list in Install page.
> updating the TAP 1.3.0 component list in Install page.

- install-tanzu-cli.hbs.md
updating the versions for TAP 1.3.0
> updating the versions for TAP 1.3.0

- app-sso/getting-started/expose-httpproxy.md
> Revert "AppSSO - Getting Started - Remove unnecessary step"

- application-accelerator/install-app-acc.hbs.md
> Update accelerator properties for TAP 1.3.0

- cli-plugins/accelerator/command-reference/tanzu_accelerator_generate.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_list.hbs.md
> Update accelerator CLI commands for TAP 1.3.0

- release-notes.hbs.md
- tanzu-build-service/dependencies.hbs.md
- tanzu-build-service/install-tbs.hbs.md
- Also add note about installing on openshift
This should be for tap 1.3 docs only
> Add details for jammy stack support (TAP 1.3 docs)

- scc/ootb-supply-chain-testing-with-jenkins.hbs.md
> Review changes for Jenkins Adapter

- application-accelerator/creating-accelerators/composition.hbs.md
> Add content for CLI and fragments

- release-notes.hbs.md
> add min supported version of aws-cli

- release-notes.hbs.md
> docs: document synchronous intellij launch config known issue

- intellij-extension/using-the-extension.hbs.md
Anything applying to 1.3 and higher.
> fix td-1012: remove incorrect statement wrt Live update

- release-notes.hbs.md
Which other branches should this be merged with (if any)? No, new feature for TAP 1.3
> mention Tanzu Problems panel on Vscode release notes

- about-package-profiles.hbs.md
> update package profile

- tap-gui/catalog/catalog-operations.hbs.md
added different instructions for catalog updates to tap-gui based on install method chosen
> Enhancements to the package update command in the tap-gui Catalog Operations section

- intellij-extension/getting-started.hbs.md
Anything 1.2 and later. (See 1.2 release notes that states support for this file was added to tanzu apps plugin https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap.pdf).
> TD-1000: add .tanzuignore to recommended files.

- install-air-gap.hbs.md
- scst-policy/install-sigstore-stack.hbs.md
> Update more information on airgapped install

- intellij-extension/about.hbs.md
> TD-942: initellij monorepo

- install-air-gap.hbs.md
> Add Shared TLK in Update install-air-gap.hbs.md

- install.hbs.md
> Add how to install with jammy-only to the main install docs

- scst-store/create-service-account-access-token.hbs.md
> docs: update get read only access token for metadata store

- release-notes.hbs.md
Which other branches should this be merged with (if any)? main only
> VSEE-786 | Update release notes for scst-scan

- scst-policy/migration.hbs.md
- scst-sign/configuring.hbs.md
- scst-sign/install-scst-sign.hbs.md
- scst-sign/migrate.hbs.md
- scst-sign/overview.hbs.md
> Fix links; Add migration step

- release-notes.hbs.md
Which other branches should this be merged with (if any)? Applies to tap 1.2 as well
> Added known issue for vscode and intellij

- install-air-gap.hbs.md
> Update full profile for accelerator air-gap config

- cli-plugins/apps/usage.hbs.md
> Correct workload type in CLI apps plugin example

- vscode-extension/getting-started.hbs.md
Which other branches should this be merged with (if any)? None, only the latest.
> vscode: update getting started

- release-notes.hbs.md
This documents a known issue that exists in 1.3.0 but is already fixed for 1.3.1. 
So it needs to be applied to the 1.3.0 branch **but not the 1.3.1 branch**
> Intellij: Document stopping one debug session, stops them all

- application-accelerator/configuration.hbs.md
> Document HTTPProxy timeouts for accelerator

- eventing/about.hbs.md
- eventing/install-eventing.hbs.md
[PDY-1240](https://jira.eng.vmware.com/browse/PDY-1240)
Just the main branch.
> Draft: Add docs for the new Eventing package

- eventing/about.hbs.md
This short PR is a continuation of [ this PR](https://github.com/pivotal/docs-tap/pull/1706) because I couldn't add my change before the PR was merged 😅 
Only TAP 1.3, not TAP 1.4
> Update title of about section for Eventing

- app-sso/crds/authserver.md
- release-notes.hbs.md
Which other branches should this be merged with (if any)? This should go into the 1.3 release.
> appsso: add deprecation notice for LastParentGenerationWithRestart

- release-notes.hbs.md
- tanzu-build-service/dependencies.hbs.md
> Add deprecation notice for Bionic stack

- release-notes.hbs.md
Added known issues for supply chain plug in. Added release notes for new features added in the supply chain plug-in
> please review and merge with 1.3

- release-notes.hbs.md
> Update release docs with new features and update boiler templates

- install.hbs.md
- scst-scan/install-scanners.hbs.md
- scst-scan/install-snyk-integration.hbs.md
> Fix bad comment1

- getting-started/consume-services.hbs.md
Which other branches should this be merged with (if any)? TAP 1.3 and main
> Update accelerator link for Services usecase

- scc/dockerfile-based-builds.hbs.md
- add entry to the Dockerfile builds section detailing how to workaround the extra strictness that OpenShift places on running containers that require capabilities beyond the default unprivileged SecurityContextConstraints.
the changes are related to 1.3.x+
> scc: add instructions configuring required SecurityContextConstraints for kaniko on OpenShift

- install.hbs.md
- release-notes.hbs.md
[PSTAR-784]
None, just for TAP 1.3
> Add release notes for TAP GUI 1.3.2

- install-air-gap.hbs.md
- install.hbs.md
- multicluster/reference/tap-values-build-sample.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
- multicluster/reference/tap-values-view-sample.hbs.md
> Added shared.ca_cert_data in all the sample values files

- install.hbs.md
- multicluster/reference/tap-values-build-sample.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
> Fix certificates typo

- release-notes.hbs.md
> Update release-notes.hbs.md for contour known issues

- vscode-extension/getting-started.hbs.md
> fix: copy and paste errors

- multicluster/reference/tap-values-build-sample.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
- multicluster/reference/tap-values-view-sample.hbs.md
Which other branches should this be merged with (if any)? This change is from all releases before and including 1.3
> Remove telemetry customizations for profile docs

- vscode-extension/about.hbs.md
- vscode-extension/using-the-extension.hbs.md
> fix: we do not support windows prior to TAP 1.3.0

- release-notes.hbs.md
Release notes for meta and sagui
Which other branches should this be merged with (if any)? 1.3 only
> Release notes for meta and sagui

- release-notes.hbs.md
* call out that issue is on multi cluster setup, on run cluster
* addressing comments on https://jira.eng.vmware.com/browse/TANZUSC-2003
Which other branches should this be merged with (if any)? I want this to be in the TAP 1.3.0 docs, but I don't see a branch for that, only 1-3-1, so I've set it to main
> clarify CNR known issue on openshift in release notes

- tap-gui/database.hbs.md
https://backstage.io/docs/deployment/k8s#creating-a-backstage-deployment
> Fix indent for database configuration of TAP GUI

- app-sso/about.hbs.md
- app-sso/app-operators/tutorials/securing-first-workload.hbs.md
- app-sso/crds/clientregistration.md
- app-sso/getting-started/client-registration.md
- app-sso/getting-started/provision-auth-server.md
- app-sso/platform-operators/rbac.md
- app-sso/platform-operators/uninstallation.hbs.md
- app-sso/service-operators/metadata.md
- app-sso/service-operators/scale.md
- app-sso/service-operators/token-signature.md
- app-sso/service-operators/troubleshooting.md
> Draft: AppSSO: fixes/edits for TAP 1.3.0

- tanzu-build-service/dependencies.hbs.md
> Fix stack versions

- tanzu-build-service/dependencies.hbs.md
This is for tap 1.3 only.
Sorry this is after docs freeze!
> Update to correct java buildpack versions

- release-notes.hbs.md
Which other branches should this be merged with (if any)? 1.3.1
> Added release notes for VScode and IntelliJ extensions

- intellij-extension/getting-started.hbs.md
- vscode-extension/getting-started.hbs.md
- vscode-extension/using-the-extension.hbs.md
Use cartographer and kubernetes labels
This is for 1.3.0 and 1.3.1 only
> do not use knative labels

- scst-scan/available-scanners.hbs.md
- scst-scan/install-carbonblack-integration.hbs.md
- scst-scan/install-scanners.hbs.md
- scst-scan/install-snyk-integration.hbs.md
- toc.md
- merge with main
- cherry-pick to 1-3-0 (This pull request addresses TANZUSC-2063)
> VSEE-795 | Improved generalized scanner installation steps

- release-notes.hbs.md
include the new environment support items
> Update release notes for Scan

- release-notes.hbs.md
Which other branches should this be merged with (if any)? 
- 1-3-0 only (This pull request includes a release notes update as part of addressing TANZUSC-2063)
> VSEE-795 | Updated release notes

- install-openshift.hbs.md
- install.hbs.md
> Add missing pipe(|) after ca_cert_data

- release-notes.hbs.md
> Add note on Java Tiny support

- scst-store/create-service-account-access-token.hbs.md
- Documentation Update for Custom TLS
- Dedicated page for Custom TLS configuration
> feat: [META-799] - Document update for Custom TLS Support

- app-sso/crds/authserver.md
- app-sso/service-operators/token-signature.md
This change should _not_ go into the `1.3` release. I'm not quite sure which branch I should be opening this pull request against.
> appsso: require tokenSignature

- multicluster/installing-multicluster.hbs.md
- multicluster/reference/tap-values-build-sample.hbs.md
- scst-store/additional.hbs.md
- scst-store/multicluster-setup.hbs.md
- scst-store/overview.hbs.md
- toc.md
Create a dedicated document for how to enable the multicluster deployment of Store. Link to it from the TAP multicluster docs.
This applies to main (1.4), 1.3, and 1.2.
> Refactor multicluster store docs

- install.hbs.md
> Added imgpkg version query

- tap-gui/plugins/sa-tap-gui.hbs.md
Main image was broken, fixed notes indentation, and updated note about how CVEs may not match
Which other branches should this be merged with (if any)? None - only 1.3
> Fixed image link and note indentation

- scst-scan/install-scst-scan.hbs.md
Which other branches should this be merged with (if any)? 
- merge with main
- please cherry-pick to 1-3-1
> VSEE-540 | Added in description for retryScanJobsSecondsAfterError

- install-openshift.hbs.md
- install.hbs.md
> Describes CEIP

- getting-started/air-gap-workload.hbs.md
TAP 1.3
Please help me correct the links.
> Add instructions for workload creation with testing and testing scanning supply chain in air gapped.

- partials/_set-up-namespaces.hbs.md
- scc/ootb-supply-chain-testing-scanning.hbs.md
- scst-store/additional.hbs.md
- scst-store/developer-namespace-setup.hbs.md
- scst-store/multicluster-setup.hbs.md
- toc.md
Please merge other PRs #1798 and #1799 before this.
For this PR, please merge into main.
Also 1.3 and 1.2 if possible. Let me know if you have trouble merging it.
> Create a doc for metadata store setup a new developer namespace

- scst-policy/install-sigstore-stack.hbs.md
please merge to main and 1-3-1
> Add EKS airgap config

- scst-store/ingress.hbs.md
- scst-store/tls-configuration.hbs.md
> Be more explicit about custom certificate usage

- install.hbs.md
> Separate relocation and add repo

- scst-scan/install-scst-scan.hbs.md
- This MR is intended to **Main**
- Please cherry pick to **1-3-1**
> VSEE-540 | Changing field term from 'failed' to 'errored' to be consistent with scans terminology

- release-notes.hbs.md
Signed-off-by: Conor Nosal <cnosal@pivotal.io>
- This is meant for 1.3.1
> SCST-SCAN: Added versions updates to release 1.3.1

- toc.md
Add ingress doc to toc for metadata store component
Which other branches should this be merged with (if any)? 1.3.0
> Add ingress doc to toc

- multicluster/getting-started.hbs.md
1-3-1. Separate PR open here: #1816
> Update multicluster instructions for external delivery changes

- install.hbs.md
> Adds warning about skipping developer namespaces

- multicluster/reference/tap-values-view-sample.hbs.md
> Update multi-cluster View values

- release-notes.hbs.md
Which other branches should this be merged with (if any)? 
Just 1-3-1.
> intellij: remove debug sessions known issue and added to resolved issues

- scst-policy/known-issues.hbs.md
- upgrading.hbs.md
> Add instructions for 1.3.1 TAP upgrade for policy controller

- release-notes.hbs.md
> add release notes for Store in 1.3.1

- application-accelerator/creating-accelerators/transforms/index.hbs.md
- application-accelerator/creating-accelerators/transforms/loop.hbs.md
> Add documentation for Loop accelerator

- tap-gui/auth.hbs.md
I think all of the branches feature this doc (and this info should be pertinent for all of them), so yeah, it should hopefully improve things for all of them :smile:
> Tap gui/OIDC redirect url

- toc.md
> Added git repository creation doc to toc

- app-sso/app-operators/tutorials/securing-first-workload.hbs.md
- app-sso/getting-started/provision-auth-server.md
- app-sso/upgrades/index.md
Minor docs improvements following feedbacks from AppSSO users.
Please merge the following in:
- 1.3.x
- 1.4.0
> AppSSO docs improvements

- app-sso/service-operators/identity-providers.md
Please merge in:
- 1.3.x
- 1.4.0
> AppSSO: rework AuthServer.spec.identityProivders doc

- tap-gui/plugins/application-accelerator-git-repo.hbs.md
This doc needs to become available in the 1.3 docs
Closes pivotal/acc-release#430
> Minor revisions to examples for App Accelerator git repo creation

- scst-sign/known-issues.hbs.md
This change needs to be in the following versions:
1. TAP 1.3.0
2. TAP 1.3.1
> Add known issue for Image Policy Webhook

- tap-gui/catalog/catalog-operations.hbs.md
> Draft: Add gitlab discovery processor to TAP GUI docs

- tap-gui/catalog/catalog-operations.hbs.md
> Add namespace to tanzu package installed list

- developer-conventions/openshift.md
This is also for tap 1.3.x
Please let me know if I need to update any index pages.  I wasn't sure so I left it for now.  thx
> Document the developer conventions scc for openshift clusters

- release-notes.hbs.md
Tanzu Debug does not port forward application port
Just 1.4. And this is a breaking change
> add known issue

- scst-policy/install-sigstore-stack.hbs.md
This change is intended for 1.4, 1.3.1 and 1.3.0.
> Improve sigstore stack docs

- learning-center/runtime-environment/workshop-definition.hbs.md
- learning-center/workshop-content/workshop-config.hbs.md
> Learning Center: Removing master references that are not required

- app-sso/crds/authserver.md
- app-sso/platform-operators/configuration.md
- app-sso/service-operators/issuer-uri-and-tls.md
> AppSSO: document `default_authserver_issuer`

- .idea/workspace.xml
- learning-center/getting-started/training-portal.hbs.md
- learning-center/getting-started/workshops.hbs.md
Which other branches should this be merged with (if any)? No
> Inclusion updates for 1-0

- learning-center/getting-started/training-portal.hbs.md
- learning-center/getting-started/workshops.hbs.md
Which other branches should this be merged with (if any)? No
> Inclusion updates for 1-1

- learning-center/runtime-environment/workshop-definition.hbs.md
- learning-center/workshop-content/workshop-config.hbs.md
> Inclusion updates for 1-2-2

- learning-center/runtime-environment/workshop-definition.hbs.md
- learning-center/workshop-content/workshop-config.hbs.md
> Inclusion updates for 1-3-1

- learning-center/runtime-environment/workshop-definition.hbs.md
- learning-center/workshop-content/workshop-config.hbs.md
> Inclusion updates for 1-3-0

- release-notes.hbs.md
Added resolved issues for Supply Chain Choreographer plug-in as well as new known issues in 1.3.1
Merge with 1.3.1
> Added resolved and known issues

- partials/contour/_contour-scc.hbs.md
- scc-details.hbs.md
Doing this as part of: https://jira.eng.vmware.com/browse/TANZUSC-2123
I'm not sure if I did the partial correctly, please let me know if it is wrong!
Which other branches should this be merged with (if any)? main
> TANZUSC-2123: add contour custom scc details

- release-notes.hbs.md
please merge with 1.4 release notes.
> Preliminary updates for supply chain plugin

- application-accelerator/openshift.hbs.md
- partials/application-accelerator/_openshift-app-accelerator.hbs.md
- scc-details.hbs.md
1.3.1+
In reference to https://jira.eng.vmware.com/browse/TANZUSC-2123
> Add OpenShift SCC info

- scst-policy/install-sigstore-stack.hbs.md
Signed-off-by: Andrés Torres <andrest@vmware.com>
This change is intended for 1.4.0, 1.3.1 and 1.3.0.
> Improve OIDC issuer docs

- tap-gui/database.hbs.md
> Adds instructions on how to tell TAP GUI which database to use

- multicluster/reference/tap-values-build-sample.hbs.md
- scst-scan/observing.hbs.md
- scst-store/multicluster-setup.hbs.md
Please merge into `main`, `1-3-1`, `1-3-0`, and `1-2-2`.
> Improve multi-cluster scan->store docs

- app-sso/app-operators/register-an-app-with-app-sso.hbs.md
This is targeted for TAP `1.4.0`
> AppSSO: update usage of "tanzu service resource-claim"

- release-notes.hbs.md
[PSTAR-784]
None, just for TAP 1.3.1
> Add release notes for TAP GUI 1.3.3

- tap-gui/cluster-view-setup.hbs.md
> Updates based on feedback for Bug 3027498

- tanzu-build-service/tbs-about.hbs.md
Most recent and previous TAP releases
> Add link to buildpacks docs

- tanzu-build-service/dependencies.hbs.md
FAQ from the field.
* Previous TAP releases
> Updating TBS Deps out of band of TAP Releases

- cli-plugins/insight/cli-configuration.hbs.md
- partials/cli-plugins/_insight-set-target.hbs.md
Merge into `main`, `1-2-2`, `1-3-0`, `1-3-1`, and `1-3-2`.
> Clarify what insight health and config set-target does and does not do

- scst-store/additional.hbs.md
- scst-store/create-service-account.hbs.md
- scst-store/custom-role.hbs.md
- toc.md
Merge into `main`, `1-2-2`, `1-3-0`, `1-3-1`, and `1-3-2`.
> Simplify the guide for Store service account

- getting-started/consume-services.hbs.md
- getting-started/set-up-services.hbs.md
Class Claims are a new feature in TAP 1.4 and this commit updates the corresponding documentation to make use of them.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? None - these changes are only relevant from TAP 1.4 onwards.
> Update services docs to make use of class claims

- getting-started/about-vulnerability-scan-store.hbs.md
- scst-scan/install-scst-scan.hbs.md
- scst-scan/triaging-and-remediating-cves.hbs.md
- scst-store/overview.hbs.md
- tap-gui/plugins/scc-tap-gui.hbs.md
Merge into `main`, `1-2-2`, `1-3-0`, `1-3-1`, and `1-3-2`.
> Do a better job of linking to SCC

- install-air-gap.hbs.md
- install-openshift.hbs.md
- install.hbs.md
- multicluster/reference/tap-values-build-sample.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
> Add git auth link in install page

- release-notes.hbs.md
> Update release notes for build profile cluster change

- app-sso/crds/authserver.md
- app-sso/getting-started/provision-auth-server.md
- app-sso/service-operators/issuer-uri-and-tls.md
- app-sso/upgrades/index.md
- template_variables.yaml
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? None. This change is targeted for TAP 1.4.x
> AppSSO: inclusive language field update for AuthServer CRD

- partials/_set-up-namespaces.hbs.md
TAP v1.4.0+
cc @BarrAndrea --- Andrea this is just the most basic instructions for now. A substantial amount of additional documentation will be provided shortly. Just want to get something basic in for the time being.
> add high-level namespace provisioner instructions

- getting-started/consume-services.hbs.md
- getting-started/set-up-services.hbs.md
No other branches but can the docs-staging link be updated to live once TAP 1.4.0 docs go live
> Add new stk usecase classclaims

- release-notes.hbs.md
Updated resolved issues in 1.3.3 to include supply chain choreographer plug-in fixes
This can be merged with 1.3.3 please
> Updated resolved issues

- scst-policy/install-scst-policy.hbs.md
> Add no_match_policy and fail_on_empty_authorities

- prerequisites.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.3
> TKGS (Tanzu vsphere) supported version for TAP 1.3)

- install-openshift.hbs.md
Updates shared keys and SCC changes for TAP 1.4.0.
> openshift SCC changed for TAP 1.4.0.

- prerequisites.hbs.md
> Update openshift 4.11 support

- app-sso/crds/authserver.md
- app-sso/service-operators/storage.hbs.md
> appsso: update AuthServer storage configuration API references

- services-toolkit/install-services-toolkit.hbs.md
Hi, this is a small update to the "install services toolkit" doc to add in a new pre-requisite.
This change is relevant to TAP 1.4+
Thanks,
Ed
---
> List cert-manager as a prereq for install stk

- install.hbs.md
> Update openshift changes for v4.11

- multicluster/reference/tap-values-build-sample.hbs.md
> updates for openshift

- multicluster/reference/tap-values-iterate-sample.hbs.md
> updates for openshift in TAP 1.4.0.

- multicluster/reference/tap-values-run-sample.hbs.md
> Updates for openshift in TAP 1.4.0

- scst-policy/configuring.hbs.md
> scst-policy Add docs for `match` field in ClusterImagePolicy

- release-notes.hbs.md
Just needs to be documented for 1.3.x
> Add known issue regarding inability to configure custom CA cert

- scst-scan/observing.hbs.md
> [VSEE-835] Add troubleshooting docs for deprecated pre-v1.2 templates

- install-openshift.hbs.md
> update kubernetes_version TLK for openshift

- install-aws.hbs.md
- install.hbs.md
- multicluster/reference/tap-values-build-sample.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
- multicluster/reference/tap-values-view-sample.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? This is for 1.4 and beyond
> Telemetry - Add references to install tap telemetry via profiles

- install.hbs.md
This is targeted for TAP `1.4.x`.
---
* none
* ack
> Include `shared.ingress_issuer` in installation docs

- app-sso/service-operators/identity-providers.md
> appsso: add LDAP identity provider configuration

- release-notes.hbs.md
- scc/events.hbs.md
- toc.md
- troubleshooting-tap/troubleshoot-using-tap.hbs.md
This needs to be in 1.4 docs onwards.
> Introduce documentation for events

- app-sso/service-operators/index.md
> appsso: fix service operators index page subpage listing

- release-notes.hbs.md
- scst-scan/observing.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? NA
> VSEE-829 | Announce deprecation plain text creds fields

- app-sso/service-operators/identity-providers.md
> appsso: fix appsso > service ops > identity providers formatting

- scst-store/create-service-account.hbs.md
- tap-gui/plugins/scc-tap-gui.hbs.md
- upgrading.hbs.md
read-write service account must be used for install and upgrade in 1.4
> Updated for read-write changes in 1.4

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac.hbs.md
> Updated article name to resolve ambiguity-1

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-gke.hbs.md
> Updated article name to resolve ambiguity-2

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-eks.hbs.md
> Updated article name to resolve ambiguity-3

- scc/authoring-supply-chains.hbs.md
- scc/parameters-reference.hbs.md
**This change is only for 1.4**
> Add instructions for creating templates with Tekton lifecycles

- scc/authoring-supply-chains.hbs.md
- scc/parameters-reference.hbs.md
> Add documentation of param and templates that can be manipulated

- release-notes.hbs.md
> [VSEE-829] Add release note about cbc not affected.

- release-notes.hbs.md
> document minimum version of `apps` plugin

- tap-gui/plugins/app-live-view-springboot.hbs.md
- tap-gui/plugins/app-live-view-steeltoe.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Only for 1.4.0
> Update 1.4.0 steeltoe doc for App Live View

- intellij-extension/install.hbs.md
> Update required version of IntelliJ to install Tanzu Developer Tools extension

- tanzu-build-service/build-image-action.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? no
> add env for dev namespace

- app-sso/service-operators/identity-providers.md
- app-sso/service-operators/token-signature.md
- app-sso/troubleshoot.md
> appsso: explicitly mention which token signature algs are supported

- release-notes.hbs.md
Removed feature not being delivered and added Known Issues section for the Supply Chain Choreographer plug-in. Please review and merge to main.
> Updates for release for SCC plug-in

- scc/dockerfile-based-builds.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? No
> Remove automated steps

- partials/scst-scan/_offline-airgap.hbs.md
> [VSEE-565] Update airgap grype docs with better troubleshooting

- release-notes.hbs.md
- scst-scan/observing.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? N/A
Signed-off-by: Nicholas Eden-Walker <nedenwalker@vmware.com>
> VSEE-829 | Reverted terminology changes for docker field and sub-fields

- install.hbs.md
> Adds env vars descriptions for add tap package repo

- tanzu-build-service/build-image-action.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? no
> More updates

- release-notes.hbs.md
- services-toolkit/about.hbs.md
- services-toolkit/install-services-toolkit.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Targeting TAP 1.4 only.
> Services Toolkitt 0.9.0 updates

- release-notes.hbs.md
Summary:
* This is still an open grype issue https://github.com/anchore/syft/issues/690
N/A
> Add grype scanner known issue to 1-3-3 docs

- release-notes.hbs.md
this did not make it into 1.4
just 1.4
> remove known issues

- aws-resources.hbs.md
Should be applied to 1.3 and 1.4.
> Explicitly output json format when piping to jq

- release-notes.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.4.x
> cert-manager: add release notes subsection

- aws-install-intro.hbs.md
You must create repositories in advance, or else the getting started will fail.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1.3 and 1.4
> Add reminder to create repositories

- vs-extension/about.hbs.md
- vs-extension/dependencies.hbs.md
- vs-extension/using-the-extension.hbs.md
This PR is for this branch only
> Add Visual Studio Extension Documentation

- vs-extension/using-the-extension.hbs.md
> Update links for Visual Studio Extension docs

- release-notes.hbs.md
No cherry picking to other branches necessary. Thanks!
> known issues: add Intellij Describe action error for PodIntents

- intellij-extension/troubleshooting.hbs.md
> Intellij ts

- scst-scan/observing.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 
- merge with main
- cherry-pick to 1.2 and 1.3 branches
Signed-off-by: Conor Nosal <cnosal@vmware.com>
> VSEE-844 | Updated scan troubleshooting docs with error when Grype database is not available

- app-sso/service-operators/storage.hbs.md
[[#183979249]](https://www.pivotaltracker.com/story/show/183979249)
---
- none
- ack
> AppSSO: storage limitations

- api-validation-scoring/install.hbs.md
> updating package version to 0.2.5

- release-notes.hbs.md
> added release notes for IntelliJ extension

- intellij-extension/troubleshooting.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1-3-0
> Added troubleshooting docs for path issue on MacOS 

- vscode-extension/troubleshooting.hbs.md
> vscode: add troubleshooting steps for debug launch config task error

- troubleshooting-tap/troubleshoot-using-tap.hbs.md
this additional troubleshooting item can be backported as far back as this troubleshooting page has existed.
the `---` separators between each TS item really help with readability (to see where each TS item begins/ends), so I'd recommend making that change as well although, it would have to be manually added to older versions since they won't have all the same number of TS entries...
> add Docker registry url fix example

- api-auto-registration/troubleshooting.hbs.md
This is for TAP 1.4
This PR aims to document an issue found in the [integration tests](https://jira.eng.vmware.com/browse/TANZUSC-2467).
> Add TLS issue to API Auto Registration troubleshooting

- app-sso/service-operators/identity-providers.hbs.md
> appsso: add ldap search filter description

- release-notes.hbs.md
> Adds release notes for TAP GUI 1.3.4

- multicluster/reference/tap-values-view-sample.hbs.md
> remove http on view values

- multicluster/installing-multicluster.hbs.md
- multicluster/reference/tap-values-view-sample.hbs.md
- tap-gui/auth.hbs.md
- tap-gui/database.hbs.md
- tap-gui/install-tap-gui.hbs.md
- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-eks.hbs.md
- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-gke.hbs.md
* TAP GUI values from view values sample
* Updates TAP GUI scheme to reflect that TLS is on by default
> Removes superfluous TAP GUI values

- release-notes.hbs.md
> Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
This change only applies to the 1.4 release. So I think that means it only goes in `main` branch?
> Add known issue for IntelliJ tools

- application-accelerator/creating-accelerators/testing-accelerators.hbs.md
- toc.md
Fix https://github.com/pivotal/acc-engine/issues/217
None
> Document accelerator testing

- release-notes.hbs.md
> appsso: fix link in release notes

- app-sso/service-operators/issuer-uri-and-tls.hbs.md
- app-sso/service-operators/tls-scenario-guides.hbs.md
- toc.md
> appsso: add tls scenario guides

- release-notes.hbs.md
also updated formatting to improve readability
> add namespace provisioner and apps cli plugin to release notes

- app-sso/service-operators/identity-providers.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.4.x
> appsso: fix LDAP docs by removing 'experimental' tag

- external-secrets/getting-started.hsb.md
> Added install documentation for the External Secrets Operator

- release-notes.hbs.md
- vs-extension/install.hbs.md
- vs-extension/using-the-extension.hbs.md
For main branch. Added an install section and also added our extension to the Release Notes
> Final tweaks and release notes for VS Ext

- release-notes.hbs.md
> Adds a release note for TAP GUI around auto TLS

- app-live-view/install.hbs.md
- app-live-view/troubleshooting.hbs.md
- install-air-gap.hbs.md
- multicluster/reference/tap-values-iterate-sample.hbs.md
- multicluster/reference/tap-values-run-sample.hbs.md
- multicluster/reference/tap-values-view-sample.hbs.md
- release-notes.hbs.md
- spring-boot-conventions/install-spring-boot-conventions.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Only for TAP 1.4.0
> Update 1.4 App Live View docs

- release-notes.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? None, only available in 1.4
> Telemetry report release notes

- vs-extension/troubleshooting.hbs.md
> Add Workaround to VS Extension Troubleshooting Page

- release-notes.hbs.md
This is for the TAP 1.4.0 release. I believe main is the only branch needed for this.
> Add known issues for Security Analysis GUI Plugin

- scst-scan/observing.hbs.md
> VSEE-913 Updated troubleshooting on incorrectly configured self-signed certificate

- namespace-provisioner/how-tos.hbs.md
- namespace-provisioner/reference.hbs.md
> fix: nsp reference to scanpolicy and pipeline

- release-notes.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Only for TAP 1.4.0
> Update release notes for App Live View

- scc/ootb-supply-chain-testing-with-jenkins.hbs.md
Can you merge this into 1.3 also, thanks.
> fix: correct label for selecting jenkins pipeline

- release-notes.hbs.md
This PR adds a list of security vulnerabilities remediated in the 1.4.0 release.
> Add vulnerabilties remediated to release notes for 1.4.0

- release-notes.hbs.md
This is for TAP 1.4 release notes. I believe main is the only branch needed
> Add release notes for SCST Policy for TAP 1.4

- release-notes.hbs.md
- scst-scan/install-scst-scan.hbs.md
- scst-scan/observing.hbs.md
> VSEE-913 Updated docs concerning ca certs and reviewed

- release-notes.hbs.md
- vs-extension/install.hbs.md
- vs-extension/troubleshooting.hbs.md
- vs-extension/using-the-extension.hbs.md
> Updates to Tanzu VS Docs

- scst-scan/install-scst-scan.hbs.md
> VSEE-838 Updated installation docs for Scan with links to the Namespace Provisioner

- cli-plugins/accelerator/command-reference/tanzu_accelerator_generate_from_local.hbs.md
- release-notes.hbs.md
> Adding in release notes & missing CLI doc

- release-notes.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Only for TAP 1.4.0
> Update release notes for App Live View -- Spring Boot 3 support

- scst-store/additional.hbs.md
- scst-store/api-walkthrough.hbs.md
- scst-store/configure-access-token.hbs.md
- scst-store/create-service-account.hbs.md
- scst-store/custom-role.hbs.md
- scst-store/retrieve-access-tokens.hbs.md
- tap-gui/plugins/scc-tap-gui.hbs.md
- toc.md
> Extract retrieve access token into its own doc

- install.hbs.md
updating available packages output to show the list for 1.4.0
> updating available packages output

- cloud-native-runtimes/install-cnrt.hbs.md
- release-notes.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? This should be included in docs for TAP 1.4
> update docs for CNR 2.1

- about-package-profiles.hbs.md
> Add CBC Enhanced Scan

- release-notes.hbs.md
Improved descriptions (user focused) for new features in 1.4
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? none, 1.4 only
> Updated store and sagui release notes

- release-notes.hbs.md
please merge to main 1.4 branch
> last minute known issue updates

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac.hbs.md
Added note at the bottom of the page to indicate there could be issues viewing the Security Analysis GUI and Supply Chain Choreographer GUI with RBAC set up on remote clusters.
please merge to main
> Added note about SCC Plugin issue

- release-notes.hbs.md
- scst-scan/install-prisma-integration.hbs.md
- scst-scan/install-scanners.hbs.md
- toc.md
> VSEE - Added page for Prisma Scanner integration

- vs-extension/about.hbs.md
- vs-extension/troubleshooting.hbs.md
- vs-extension/using-the-extension.hbs.md
> Update to Tanzu VS Extension Docs

- cli-plugins/accelerator/command-reference/tanzu_accelerator.hbs.md
- release-notes.hbs.md
> Revision to release notes & adding link to new CLI command

- partials/application-accelerator/_configuration.hbs.md
- tap-gui/plugins/application-accelerator-git-repo.hbs.md
> Add clarity to supported GitHub token mechanisms

- install-tanzu-cli.hbs.md
> Updating Tanzu CLI versions

- cli-plugins/accelerator/command-reference.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_generate_from_local.hbs.md
- release-notes.hbs.md
> Revise formatting & generate-from-local description

- release-notes.hbs.md
> document vscode known issue

- vs-extension/install.hbs.md
> Specify VS 2022 dependency

- release-notes.hbs.md
> add ki for namespace provisioner

- about-package-profiles.hbs.md
> update lang&framework table for VS Ext

- scc/ootb-supply-chain-testing-with-jenkins.hbs.md
- Update Jenkins Adapter documentation
> Update jenkins adapter docs

- app-sso/service-operators/storage.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.5 only.
> appsso storage service binding type now optional

- app-sso/getting-started/application.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.4, TAP 1.5
> Fixes rendering issues on application deploy page

- release-notes.hbs.md
> Update release notes to include mention of app accelerator code completion feature

- release-notes.hbs.md
> add "delete namespace" issue to namespace provisioner

- application-accelerator/vscode.hbs.md
> Add link in AA VS Code extension doc for configuring optional git repository creation

- namespace-provisioner/how-tos.hbs.md
> add _ytt_library note + gitOps NS creation recco

- application-accelerator/creating-accelerators/accelerator-yaml.hbs.md
> Include custom types as option for dataType

- install-tanzu-cli.hbs.md
updating OpenShift 4.10 to use Cluster Essentials 1.3
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1.4.1
> updating OpenShift 4.10 to use CE 1.3

- release-notes.hbs.md
- troubleshooting-tap/troubleshoot-using-tap.hbs.md
* This can be completely cherry-picked to `1-4-1`
This should also be cherry-picked onto `main` but not `d0c6082ca67ce9009e1fad0c990a76b54c57102a` because hopefully we fix it before 1.5
> draft: 1 4 0 arr trust issues

- learning-center/workshop-content/building-an-image.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1-3-1, 1-3-2, and 1-3-3
> Changing the LC sha version for building workshop images on tap 1.3

- aws-install-intro.hbs.md
- install-aws.hbs.md
Please cherry-pick in to the 1.4 documentation as the bug effects 1.4.
> Add note to use Cluster Essentials 1.3

- install-aws.hbs.md
1.4.  This change was inadvertently added and has the potential to break users trying to install TAP on AWS.
> Remove Grype stanza as not credential not needed

- getting-started/add-test-and-security.hbs.md
We now support multiple pipelines per namespace.
> [TSCC-145] Remove outdated warning

- install-tanzu-cli.hbs.md
> add CLI shell completion step during install

- app-sso/getting-started/provision-auth-server.hbs.md
- app-sso/known-issues/index.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.5 only.
> Removes TKGm known issue and workaround docs in AppSSO

- release-notes.hbs.md
- scst-policy/configuring.hbs.md
None. I will make a slightly different PR for TAP 1.4.x.
> Keyless policy requires subject & issuer

- scst-policy/configuring.hbs.md
Not sure if necessary to cherry pick, but this is also valid for 1.4.0.
For 1.5.x, this PR will address that:
https://github.com/pivotal/docs-tap/pull/2152
> Add info about issuer and subject regex

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-gke.hbs.md
It should be applied to 1.4, 1.3
> Removed "SECTION TO BE ADDED"

- cli-plugins/accelerator/command-reference/tanzu_accelerator_generate_from_local.hbs.md
- scst-scan/install-prisma-integration.hbs.md
1.4.x to help make the path clearer for those wanting to try out the Prisma Integration.
> Prisma docs

- release-notes.hbs.md
- troubleshooting-tap/troubleshoot-using-tap.hbs.md
> Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
This can be completely cherry-picked to 1-4-1
This should also be cherry-picked onto main but not 6796c7ab740383162028edc8bfbd1e1c16b86ab9 because hopefully we fix it before 1.5
> 1 4 0 arr trust issues

- app-sso/app-operators/register-an-app-with-app-sso.hbs.md
- app-sso/app-operators/tutorials/securing-first-workload.hbs.md
- app-sso/troubleshoot.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? **TAP 1.5 only**
> Updates Secure a Workload docs for AppSSO

- api-auto-registration/installation.hbs.md
This would go into any release >= 1.4.1
> Add instructions for turning off certificate generation

- scst-scan/install-scanners.hbs.md
- scst-scan/install-trivy-integration.hbs.md
- toc.md
> add trivy scanner alpha docs

- workloads/server.hbs.md
1-4-0
1-4-1
Related story: https://jira.eng.vmware.com/browse/PDY-1432
> PDY-1432 Documentation to secure server workloads

- tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-gke.hbs.md
Each version where (SECTION TO BE ADDED) is present
> Cleaning up the doc

- scst-scan/install-trivy-integration.hbs.md
> trivy scanner updates for saas platform integration

- about-package-profiles.hbs.md
- scst-scan/install-scanners.hbs.md
- scst-scan/scanner-matrix.hbs.md
> Draft: VSEE-926 | added the support matrix for scanners in a new separate page

- workloads/web.hbs.md
> Add section for workload internal communication

- external-secrets/about-external-secrets-operator.hbs.md
- install-tanzu-cli.hbs.md
Changes need to be cherry-picked to **1.4.x branch** and **1.5.x branch** as well. 
- Add an example that demonstrates using external secrets in a supply chain 
- Update plugin list to show external secrets plugin as an option
> update eso documentation 

- workloads/web.hbs.md
> Updates to s2s comm of web workloads

- release-notes.hbs.md
Please merge to `1-3-5` branch only.
> Updated release note for Source Controller change when checking image versions

- source-controller/reference.hbs.md
> fix: correct MavenArtifact example

- release-notes.hbs.md
Added fixed issues for Supply Chain Choreographer plug-in
pull into 1.4.1 branch please
> Resolved Issues SCC 1.4.1

- scc/parameters-reference.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? **1.3**
> Clarify phrasing

- scc/authoring-supply-chains.hbs.md
- scc/build-container-img.hbs.md
- scc/dockerfile-based-builds.hbs.md
- scc/install-ootb-sc-basic.hbs.md
- scc/install-ootb-sc-wtest-scan.hbs.md
- scc/install-ootb-sc-wtest.hbs.md
- scc/ootb-supply-chain-testing-scanning.hbs.md
- scc/ootb-supply-chain-testing-with-jenkins.hbs.md
- scc/parameters-reference.hbs.md
- scc/pre-built-image.hbs.md
- scc/scc-how-to.hbs.md
> Bring grammar, spacing, etc for SCC in alignment with current version

- scst-policy/configuring.hbs.md
This change can be cherry picked to all branches till 1.2.0
> [scst-policy] Fix error message and scenario

- release-notes.hbs.md
> Update security fixes for TAP GUI 1.4.6

- api-auto-registration/installation.hbs.md
- api-auto-registration/troubleshooting.hbs.md
- api-auto-registration/usage.hbs.md
- api-portal/about.hbs.md
- api-portal/install-api-portal.hbs.md
These changes are only for TAP 1.5
> Add more details for api-portal and api-auto-reg

- tanzu-build-service/dependencies.hbs.md
- upgrading.hbs.md
Please also cherry pick this to the 1.4.x branch, I'm guessing that's both `1-4-1` and `1-4-2`
> add instructions for upgrading tbs full deps

- aws-resources.hbs.md
updated the correct node type
1.4.x
1.3.x
> updated the correct node type

- app-sso/crds/authserver.hbs.md
- app-sso/service-operators/configure-authorization.hbs.md
- app-sso/service-operators/identity-providers.hbs.md
- app-sso/service-operators/index.hbs.md
- release-notes.hbs.md
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.5.x only.
> Introduce access token scope configuration API in AuthServer CR

- scst-scan/install-trivy-integration.hbs.md
* pulled some commands into their own shell sections to enable easier copy/pasting
* updated example values to reflect new parameters
* refactored and added more details around metadata store integrations, specifically on how to obtain the metadata store ca and auth token secret
* added section to describe how to integrate with registry using self signed cert
> trivy doc updates for clarity

- release-notes.hbs.md
- scst-policy/configuring.hbs.md
> Update scst-policy docs for tap 1.5

- app-sso/service-operators/configure-authorization.hbs.md
- toc.md
> Add 'configure authorization' AppSSO section to ToC

- cli-plugins/accelerator/command-reference/tanzu_accelerator_create.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_fragment_create.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_fragment_list.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_generate_from_local.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_get.hbs.md
- cli-plugins/accelerator/command-reference/tanzu_accelerator_list.hbs.md
> Update with latest command docs for 1.5

- scst-scan/install-trivy-integration.hbs.md
> trivy air gap instruction updates for relocating trivy-db

- scst-scan/install-prisma-integration.hbs.md
* updated some commands to shell vs console and broke out to enable easier copy/pasting and running
* add instructions for registries using self signed certificates
* clarified metadata store integration options
1-4-1, 1-4-2
> prisma doc updates for clarity

- tap-gui/customize/customize-portal.hbs.md
- tap-gui/plugins/scc-tap-gui.hbs.md
This is only applicable to 1.5, so any branches that have been cut for that. I'm pretty sure that's just main though right?
> Tap gui/1.5.0 bug bash docs

- app-live-view/configuring-apps/spring-boot-enablement.hbs.md
> Update App Live View 1.5.0 docs with Boot 3 enablement

- app-live-view/improved-security-and-access-control.hbs.md
- app-live-view/install.hbs.md
- tap-gui/cluster-view-setup.hbs.md
- toc.md
This PR is targetted for TAP 1.5.0
> App Live View improved security docs

- app-sso/crds/authserver.hbs.md
- app-sso/crds/clientregistration.hbs.md
- app-sso/service-operators/cors.hbs.md
- app-sso/service-operators/index.hbs.md
- release-notes.hbs.md
- toc.md
> adds CORS and public client support for AppSSO

- scst-scan/app-scanning-alpha.hbs.md
Updates for app-scanning alpha.4 and minor clarifications
n/a - component is new in 1.5
> Update app-scanning instructions

- release-notes.hbs.md
> Add vulnerability fixes for 1.3.6

- api-validation-scoring/install.hbs.md
- install.hbs.md
- scst-scan/install-prisma-integration.hbs.md
- scst-scan/install-trivy-integration.hbs.md
This PR should be merged when Cluster Essentials 1.5 is out
> Remove unnecessary commands to get all tags from repository

- intellij-extension/getting-started.hbs.md
- vscode-extension/getting-started.hbs.md
- vscode-extension/using-the-extension.hbs.md
> Ide plugins/update registry instructions

- telemetry/overview.hbs.md
> Add screenshots of telemetry reports

- install-openshift.hbs.md
- install.hbs.md
- release-notes.hbs.md
- tanzu-build-service/dependencies.hbs.md
- tanzu-build-service/tbs-about.hbs.md
This is intended for TAP 1.5.0
> Add release notes for TBS 1.10

- namespace-provisioner/tutorials.hbs.md
> fix incorrect section description

- tanzu-build-service/dependencies.hbs.md
- tanzu-build-service/tbs-about.hbs.md
Please cherry-pick this to all of the TAP 1.3 branches
> [TAP 1.3] Document version of TBS used in TAP

- tanzu-build-service/dependencies.hbs.md
- tanzu-build-service/tbs-about.hbs.md
Please cherry-pick this to all of the TAP 1.4 branches
> [TAP 1.4] Document version of TBS used in TAP

- install.hbs.md
> Adds metadata store autoconfig block to the install instructions

- app-live-view/improved-security-and-access-control.hbs.md
- app-live-view/install.hbs.md
These changes are targetted for TAP 1.5.0
> Update alv security docs

- tap-gui/plugins/scc-tap-gui.hbs.md
Added context to indicate that Approve a Request shows in the stage details and not the stage.
Merge to main please.
> updated wording

- release-notes.hbs.md
> known-issues: add known issues for ide plugins

- release-notes.hbs.md
> Adding in 1.5.0 release notes for application accelerator

- release-notes.hbs.md
> Document TBS resolved issues for TAP 1.4.2

- release-notes.hbs.md
> Document TBS resolved issues for TAP 1.3.6

- release-notes.hbs.md
> VSEE-953 | Carried over Grype known issue

- getting-started/iterate-new-app.hbs.md
- intellij-extension/install.hbs.md
- partials/vscode-extension/_install.hbs.md
- workloads/iterate-functions.hbs.md
fixes https://github.com/tilt-dev/tilt/issues/5974
1.4 and 1.3
> update tilt version

- tap-portal-telemetry.hbs.md
> Updated email to delete data

- scst-scan/troubleshoot-scan.hbs.md
> [VSEE-936] Add airgap troubleshoot link from the general troubleshoot scan page

- scst-scan/app-scanning-alpha.hbs.md
add section on retrieving results
add CR spec overview
fix trivy sample
adjust section headers
add additional troubleshooting commands
add available workspaces, env, and params to integration guide
1.5 only
> Update app-scannign docs

- app-live-view/configuring-apps/spring-boot-enablement.hbs.md
- app-live-view/install.hbs.md
> Update App Live View docs for 1.5

- cli-plugins/accelerator/overview.hbs.md
> Update instructions for accelerator CLI --server-url

- release-notes.hbs.md
- scst-scan/troubleshoot-scan.hbs.md
> VSEE-953 | Updated docs-tap with scan new features 1.5.0

- gitops-reference-docs.hbs.md
- install-gitops-eso.hbs.md
- install-gitops-intro.hbs.md
- install-gitops-sops.hbs.md
- install-intro.hbs.md
- install-tanzu-cli.hbs.md
- uninstall-gitops.hbs.md
Files to be reviewed as a first draft:
- `gitops-install.*`
- `uninstall-gitops.hbs.md`
- `install-intro.hbs.md`
- `install-tanzu-cli.hbs.md`
Other files are not yet ready for review.
_(target: 1.5.0 docs, only.)_
> Include installing TAP via Tanzu GitOps RI (First Draft)

- application-accelerator/troubleshooting.hbs.md
- application-accelerator/vscode.hbs.md
- getting-started/deploy-first-app.hbs.md
Closes pivotal/acc-ide#243
1.5.0 +
> Additional Application Accelerator revisions for 1.5.0

- scst-scan/observing.hbs.md
- scst-scan/samples/blob.hbs.md
- scst-scan/samples/overview.hbs.md
- scst-scan/samples/private-image.hbs.md
- scst-scan/samples/private-source.hbs.md
- scst-scan/samples/public-image-compliance.hbs.md
- scst-scan/samples/public-source-compliance.hbs.md
> VSEE- 995 | Improve documentation on sample scans 

- install.hbs.md
> Correct kubernetes_distribution and version keys

- install.hbs.md
- tanzu-build-service/install-tbs.hbs.md
- tanzu-build-service/troubleshooting.hbs.md
Please cherry pick this to the 1.4.x line (`1-4-0`, `1-4-1`, and `1-4-2`)
> Document using shared.image_registry with TBS

- release-notes.hbs.md
This PR includes the resolved issue and added known issues for TAP 1.4.3
- 1-4-3
> Grype Release Notes

- scc/blue-green-with-packageinstall.hbs.md
- scc/delivery-with-flux.hbs.md
- scc/scc-how-to.hbs.md
> update flux delivery and blue green pages

- scst-scan/app-scanning-alpha.hbs.md
> VSEE-934 | Updated alpha App Scanning docs with feedback comments

- about-package-profiles.hbs.md
> Updated the language and framework support table

- application-accelerator/creating-accelerators/transforms/index.hbs.md
- application-accelerator/creating-accelerators/transforms/provenance.hbs.md
- toc.md
Fix https://github.com/pivotal/acc-release/issues/502
None. This is a TAP 1.5 feature
> Document App Accelerator Provenance mechanism

- tap-gui/database.hbs.md
> Adds tap-values structure to tap-gui database config

- scc/carvel-package-supply-chain.hbs.md
> Document that Azure gitops is not supported by carvel package workflow

- partials/ide-extensions/_workload-panel-intro.hbs.md
- release-notes.hbs.md
> ide-plugins: update workloads view and activity tab description

- integrations/tsm-tap-integration.hbs.md
Scan clusters are now supported, so removing mention that it isnt. Removing Namespace exclusion section as this is no longer required by TSM
1-5 
> WIP: Update tsm-tap-integration.hbs.md

- install.hbs.md
> Add bold note to add grype into multiple namespaces using namespace provisioner

- scc/carvel-package-supply-chain.hbs.md
> Require dev ns for carvel package workflow

- scc/carvel-package-supply-chain.hbs.md
> Revert "Require dev ns for carvel package workflow"

- install-gitops-sops.hbs.md
- uninstall-gitops.hbs.md
Some docs bug fixes for GitOps based installation of TAP
https://jira.eng.vmware.com/browse/TANZUSC-3466
https://jira.eng.vmware.com/browse/TANZUSC-3466
> Update docs with GitOps Installer bug fixes

- release-notes.hbs.md
> Add known issue for SA GUI for TAP 1.5.0

- toc.md
> Add azure guide to how-to TOC

- partials/scst-scan/_offline-airgap.hbs.md
> [VSEE-936] Add troubleshooting on timestamp format for airgap grype db

- install-tanzu-cli.hbs.md
> # Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
* 1-4-1
* 1-4-0
> Fixed bookmark links on Tanzu CLI install page

- opting-out-telemetry.hbs.md
- tap-portal-telemetry.hbs.md
> Pendo telemetry revision

- scst-scan/app-scanning-alpha.hbs.md
> [VSEE-934] Fix grammar and organize for app-scanning page

- release-notes.hbs.md
Please cherry pick to all 1-4-x and 1-3-x branches.
> known-issues: live update does not work with jammy

- external-secrets/about-external-secrets-operator.hbs.md
- external-secrets/install-external-secrets-operator.hbs.md
- external-secrets/vault-example.hbs.md
`main` branch only (TAP 1.5.x)
Fixes #2239
> External Secrets Operator and CLI

- release-notes.hbs.md
> Tapi release notes

- getting-started.hbs.md
> Updated getting started doc links #85

- release-notes.hbs.md
> release notes/ide plugins: update new features to specify support for spring boot 3 applications

- release-notes.hbs.md
> Add Tap Gui plugin release note 1-5-0.

- install-azure/profile.hbs.md
- install-openshift.hbs.md
- install.hbs.md
- multicluster/reference/tap-values-build-sample.hbs.md
- tanzu-build-service/install-airgapped.hbs.md
- tanzu-build-service/install-tbs.hbs.md
- tanzu-build-service/troubleshooting.hbs.md
> Update docs to use secret refs instead of plaintext creds in TBS

- app-sso/app-operators/index.hbs.md
- app-sso/app-operators/secure-spa-workload.hbs.md
- toc.md
> Adds docs for securing a single-page app with AppSSO

- hardening-guide.hbs.md
> add TAP Hardening Guide to v1.5 release

- scst-scan/install-carbonblack-integration.hbs.md
- scst-scan/install-prisma-integration.hbs.md
- scst-scan/install-scst-scan.hbs.md
- scst-scan/install-snyk-integration.hbs.md
- scst-scan/install-trivy-integration.hbs.md
- scst-scan/troubleshoot-scan.hbs.md
> VSEE-1015 | updated instructions on deactivating the metadata store

- scst-scan/install-carbonblack-integration.hbs.md
> Scanning - replaced terminology

- scst-scan/policies.hbs.md
> [VSEE-1006] Add upstream link for rego docs

- release-notes.hbs.md
> Added release notes for Application Accelerator

- intellij-extension/troubleshooting.hbs.md
> intellij: troubleshooting - remove describe issue

- scst-scan/upgrading.hbs.md
> VSEE-1007 - added instructions on upgrading scanner via Namespace Provisioner or manually

- partials/scst-scan/_offline-airgap.hbs.md
> VSEE-936 | Update Grype airgap installation

- release-notes.hbs.md
List of security fixes for 1.3.7
> Add security fixes for 1.3.7

- release-notes.hbs.md
Add security fixes for 1.4.3 to release notes
> Add security fixes for 1.4.3 to release notes

- release-notes.hbs.md
Add security fixes for 1.5.0 to release notes
> Add security fixes for 1.5.0 to release notes

- scst-scan/app-scanning-alpha.hbs.md
- toc.md
> VSEE | Changed to non-abbreviated form of SCST - Scan 2.0 in TOC and removed stray colon

- scst-scan/policies.hbs.md
- scst-scan/troubleshoot-rego.hbs.md
> VSEE-1006 | Created new file on Troubleshooting Rego and added link to file from the Policies page

- release-notes.hbs.md
> VSEE - Updated CBC release notes

- release-notes.hbs.md
> Add known issue for Carvel Package Workflow - ALM-71

- release-notes.hbs.md
> Add removal of automatic dependency updater to Breaking Changes

- cli-plugins/accelerator/overview.hbs.md
> Added complete steps for enabling TLS to acc doc

- install-gitops/uninstall.hbs.md
https://jira.eng.vmware.com/browse/TANZUSC-3485
> Add uninstall warning for manual installs

- services-toolkit/concepts/service-consumption.hbs.md
- services-toolkit/tutorials/setup-dynamic-provisioning.hbs.md
> Fixes for STK's docs

- scst-scan/install-prisma-integration.hbs.md
> prisma scanner rego updates for 1.5

- scst-scan/install-carbonblack-integration.hbs.md
- main
- 1.4 branches
- 1.3 branches
> VSEE - Updated deactivating scst store for CBC docs

- scst-scan/install-snyk-integration.hbs.md
- main
- 1.4 branches
- 1.3 branches
- 1.2 branches
> VSEE - Updated deactivating scst store for Snyk docs

- scst-scan/install-scst-scan.hbs.md
> VSEE-1015 | Updated documentation after feedback

- install-air-gap.hbs.md
- install.hbs.md
> Update environment variables used in secrets

- release-notes.hbs.md
- Reword provenance description and link to relevant section
- Remove non-user facing changes for gui plugin
> Update application accelerator 1.5 release notes

- release-notes.hbs.md
> Add release notes for 1.5.0 Visual Studio plugin

- release-notes.hbs.md
> Rephrase 1.5.0 Visual Studio plugin release notes

- security-and-compliance/harden-tap.hbs.md
Adds more verbiage to the deployment doc to align it with the rest of the document.
> Revamp deployment arch

- install.hbs.md
- scst-scan/install-scst-scan.hbs.md
- scst-scan/troubleshoot-scan.hbs.md
> [VSEE-1023] Add troubleshooting scanner to metadatastore failing to verify certificates

- scst-scan/troubleshoot-rego.hbs.md
> VSEE-1006 | Fixed technical content description

- app-sso/crds/authserver.hbs.md
- app-sso/getting-started/provision-auth-server.hbs.md
- app-sso/service-operators/metadata.hbs.md
- app-sso/service-operators/tls-scenario-guides.hbs.md
> allow client namespaces annotation is optional in AuthServer

- partials/scst-scan/_offline-airgap.hbs.md
> VSEE-936 | Added note on Namespace provisioner in enable section

- partials/scst-scan/_offline-airgap.hbs.md
> VSEE-936 | Added note on Namespace provisioner

- scst-scan/upgrading.hbs.md
- main
- 1.5 branches
- 1.4 branches
> VSEE-1007 | Responded to feedback

- scst-scan/troubleshoot-scan.hbs.md
> VSEE-1023 | Responded to feedback, added in instructions on if there are intermediate CA certs

- crossplane/about.hbs.md
Fixes a small typo.
I've also noticed a broken link on this page: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/bitnami-services-about.html. The "Next Page" link doesn't seem to work and I am unsure how to fix that? Please could you take a look at that as well?
Thanks!
Ed
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1-5-0, 1-5-1
> Fix small typo

- scst-scan/troubleshoot-rego.hbs.md
- toc.md
> VSEE-1006 | Added spdx sample

- scc/install-scc.hbs.md
> Update Carto install strings for 1.5

- scst-scan/install-prisma-integration.hbs.md
- scst-scan/install-trivy-integration.hbs.md
> prisma/trivy - updates for disabling metadata store integration

- namespace-provisioner/reference.md
- namespace-provisioner/use-case4.md
> updates reference.md file profile for limitrange

- scst-scan/app-scanning-alpha.hbs.md
- main (1.6)
- all 1.5 branches
> VSEE-934 | Addressed feedback on scanning description and added improvements

- partials/_view-package-config.hbs.md
> Add example for a `shared` key

- scc/dockerfile-based-builds.hbs.md
> ensure 'type' is specified for examples

- application-accelerator/creating-accelerators/accelerator-yaml.hbs.md
> Documented how to customize the "Name" option.

- application-configuration-service/install-app-config-service.hbs.md
> fix command line options for acs package install

- application-accelerator/provenance.hbs.md
- toc.md
> Add additional section on Provenance

- scst-scan/troubleshoot-scan.hbs.md
- main
- 1.5 branches
- 1.4 branches
> VSEE | Fixed missing parenthesis causing broken link

- scst-store/standalone-install-scst-store-prereq.hbs.md
- toc.md
This should go in main branch only.
> Metadata Store Cert Update for independent Install

- app-sso/crds/authserver.hbs.md
> Fixes indentation issue in AuthServer CRD definition docs

- release-notes.hbs.md
Resolved Issue for 1.5.1 release notes
> Application Accelerator IntelliJ Plugin for 1.5.1

- app-sso/crds/authserver.hbs.md
- app-sso/service-operators/index.hbs.md
- app-sso/service-operators/token-settings.hbs.md
- release-notes.hbs.md
- toc.md
> Adds AppSSO AuthServer token settings docs

- multicluster/reference/tap-values-build-sample.hbs.md
- scst-scan/install-carbonblack-integration.hbs.md
- scst-scan/install-scst-scan.hbs.md
- scst-scan/install-snyk-integration.hbs.md
- scst-scan/troubleshoot-scan.hbs.md
> VSEE-1016 | updated instructions on deactivating the metadata store

- tap-gui/customize/customize-telemetry.hbs.md
- tap-portal-telemetry.hbs.md
> Customize org ID for Pendo

- scc/blue-green-with-packageinstall.hbs.md
1.5.1 
this change is also useful for 1.5.x 
/cc @Petahhh
> Update blue green deployment page to be more clear

- app-sso/service-operators/identity-providers.hbs.md
Changes should be applied to all past supported branches
> Re-framed intro paragraph to start with what is supported

- release-notes.hbs.md
- tap-gui/troubleshooting.hbs.md
This applies to 1-5-0 but won't apply to 1.6 or later.
> Add troubleshooting for TAP GUI CSP

- release-notes.hbs.md
Add vulnerability fixes in 1.5.1
> Add vulnerability fixes in 1-5-1

- toc.md
> TAP 1.4.5: Reference store connecting to db instructions in TOC

- toc.md
> TAP 1.5.1: Reference store connecting to db instructions in TOC 

- namespace-provisioner/legacy-manual-namespace-setup.hbs.md
- namespace-provisioner/provision-developer-ns.md
> Store - Update TOC to include recent DB doc

- tap-gui/tap-gui-rbac/set-up-tap-gui-permission-framework.hbs.md
> Permission framework for TAP GUI

- cartographer-conventions/troubleshooting.hbs.md
Add troubleshooting information for defining `imagePullSecrets`
> add troubleshooting docs on defining imagePullSecrets

- release-notes.hbs.md
1-5-0
1-5-1
Related story: https://jira.eng.vmware.com/browse/PDY-1577
> PDY-1577 CNRS - Fix known issues in tap1.5

- toc.md
> Update toc.md - Permission framework for TAP GUI

- cert-manager/about.hbs.md
- cert-manager/acme-challenges.hbs.md
- security-and-compliance/tls-and-certificates/ingress/issuer.hbs.md
- toc.md
See: https://docs.google.com/document/d/1iu6_Q_YL8MROmp02RkUYlSrmScQPff0VKmaJyu82UTA/edit#
[#185040812]
---
`1.6.x`
`1.5.x`
> Warn about failing ACME HTTP01 challenges and provide workarounds

- app-sso/reference/api/clientregistration.hbs.md
- app-sso/reference/api/clusterunsafetestlogin.hbs.md
- app-sso/reference/api/clusterworkloadregistrationclass.hbs.md
- app-sso/reference/api/index.hbs.md
- app-sso/reference/api/workloadregistration.hbs.md
- app-sso/reference/api/xworkloadregistration.hbs.md
- app-sso/reference/index.hbs.md
- app-sso/reference/package-configuration.hbs.md
- app-sso/reference/rbac.hbs.md
Updates the reference section with:
* RBAC
* New APIs
* Package configuration
`1.6.x`
> Add reference for new APIs

- security-and-compliance/tls-and-certificates/custom-ca-certificates.hbs.md
- security-and-compliance/tls-and-certificates/ingress/about.hbs.md
> TLS improvements

- release-notes.hbs.md
> Flux Source Controller Release Note

- release-notes.hbs.md
This is meant for TAP 1.5.2
- Cherry pick known issues to 1.5.1
> Added release notes for tap 1.5.2

- app-sso/reference/api/workloadregistration.hbs.md
> Link to the section on redirect URI templating

- services-toolkit/how-to-guides/dynamic-provisioning-rds.hbs.md
> Fix RDS yaml formatting

- app-sso/troubleshoot.hbs.md
> appsso: add DEBUG logs

- release-notes.hbs.md
This is meant for 1.5.2
Cherry pick to 1.5.1
> Fixing typo in SCST-Scan release notes

- namespace-provisioner/use-case3.hbs.md
> updates use-case3 file to change git secret yaml

- app-sso/reference/api/authserver.hbs.md
- app-sso/reference/api/clientregistration.hbs.md
- app-sso/service-operators/configure-authorization.hbs.md
- app-sso/service-operators/identity-providers.hbs.md
- release-notes.hbs.md
- template_variables.yaml
> AppSSO - custom user attribute claim mappings docs

- tap-gui/auth.hbs.md
Add an optional section under 'Configure an authentication provider' to describe the 'offline_access' scope
At their discretion
> [TAAP-1499] https://jira.eng.vmware.com/browse/TAAP-1499
