pivotal/docs-tap

release-notes.hbs.md

feat: [META-1099] Adding release notes for SCST-Store SBOM/Build feature for TAP 1.6

---

namespace-provisioner/ootb-supply-chain.hbs.md
namespace-provisioner/use-case1.hbs.md
namespace-provisioner/use-case2.hbs.md
namespace-provisioner/use-case3.hbs.md
namespace-provisioner/use-case4.hbs.md
namespace-provisioner/use-case5.hbs.md

These changes are intended to be for TAP 1.6

chore: Update NSP examples removing path

---

install-azure/profile.hbs.md
install-offline/profile.hbs.md
install-online/profile.hbs.md
install-openshift/profile.hbs.md
multicluster/reference/tap-values-build-sample.hbs.md

VSEE-1038 Added grype deprecation warnings to tap-values sections.

---

app-sso/reference/api/clusterworkloadregistrationclass.hbs.md

docs(app-sso): fix fenced code block language

---

tap-gui/customize/customize-telemetry.hbs.md

Yaml indent typo

---

app-live-view/configuring-apps/spring-native-enablement.hbs.md
app-live-view/improved-security-and-access-control.hbs.md

This change is targeted for only TAP 1.6

ALV - spring native and rbac doc updates

---

toc.hbs.md

add Spring native page to toc

---

intellij-extension/using-the-extension.hbs.md
vscode-extension/using-the-extension.hbs.md

Added information on how to setup native images to intellij and vscode extensions

---

bitnami-services/install-bitnami-services.hbs.md

* Crossplane and Services Toolkit are both dependencies
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.5

Update Bitnami Services pre-reqs

---

scc/azure.hbs.md

This change should apply to TAP 1.7, 1.6, 1.5.

Add info on authenticating to Azure Devops repos

---

namespace-provisioner/customize-installation.hbs.md
namespace-provisioner/troubleshooting.hbs.md
namespace-provisioner/use-case4.hbs.md

Changes in this PR are for TAP 1.6

Update nsp SA customize. Skip Grype and LimitRange

---

scst-scan/app-scanning-alpha.hbs.md
scst-scan/clusterimagetemplates.hbs.md
toc.hbs.md

VSEE-1074 | Add example of tap-values installation values

---

tap-gui/plugins/scc-tap-gui.hbs.md

Updates metadata store autoconfiguration guidance for 1.5 branches

---

install-online/profile.hbs.md
partials/_full-deps.hbs.md
tanzu-build-service/install-tbs.hbs.md

Update full deps install instructions

---

namespace-provisioner/use-case3.hbs.md

Updates description on the step2 for git authentication for private repo

---

namespace-provisioner/about.hbs.md
namespace-provisioner/default-resources.hbs.md
namespace-provisioner/issues-limitations.hbs.md
namespace-provisioner/parameters.hbs.md
namespace-provisioner/provision-developer-ns.hbs.md
namespace-provisioner/reference.hbs.md
namespace-provisioner/use-case2.hbs.md
namespace-provisioner/use-case3.hbs.md
namespace-provisioner/use-case4.hbs.md
toc.hbs.md

Changes in this PR are for TAP 1.6

NSP: Add references. Add parameters.

---

about-package-profiles.hbs.md

Adding reference to workload section

---

scst-scan/clusterimagetemplates.hbs.md

VSEE | Updated image_scanning_workspace_size to 4Gi to align with test sample

---

scst-scan/custom-ivs-samples.md

VSEE-1072 | Added sample IVS for Snyk

---

release-notes.hbs.md

Add security fixes to release notes for 1.5.2

---

scst-scan/custom-ivs-samples.md

[VSEE-1073] Add prisma docs

---

scst-scan/clusterimagetemplates.hbs.md

VSEE-998 | Included activeKeychains and updated instructions in authoring clusterimagetemplate

---

scc/gitops-vs-regops.hbs.md

Adds azure to allowable server_kind values

---

install-gitops/upgrading.hbs.md

Add upgrade docs for gitopsri v0.2.0

---

external-secrets/vault-example.hbs.md
fluxcd-source-controller/install.hbs.md
partials/_view-package-config.hbs.md
scc/git-auth.hbs.md
security-and-compliance/tls-and-certificates/custom-ca-certificates.hbs.md
tekton/install-tekton.hbs.md

Clarify the use of CA certificates in Flux, ESO, and Tekton

---

scc/git-auth.hbs.md

Fixed number of bits in ssh-keygen command

---

prerequisites.hbs.md

This needs to be updated for 1.3, 1.4 & 1.5 branches as well. Please do the needful.

Update prerequisites.hbs.md for view profile requirements

---

getting-started/deploy-first-app.hbs.md
getting-started/iterate-new-app-vs.hbs.md
toc.hbs.md

add Visual Studio to getting started

---

crossplane/reference/package-values.hbs.md
crossplane/reference/version-matrix.hbs.md
release-notes.hbs.md

This PR contains a few small updates related to Crossplane v0.2.1.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? N/A

Update docs for Crossplane v0.2.1

---

tap-gui/configurator/about.hbs.md

Tanzu Dev Portal about section

---

install-gitops/intro.hbs.md

Adding the gitOps overview along with its benefits

---

install-azure/profile.hbs.md

Azure tap install - placing loadbalancer yaml in correct spot

---

learning-center/install-learning-center.hbs.md

Adding documentation for policyEngine and the way to login on the Self-Guided workshop

Learning Center: Adding documentation for policyEngine 

---

external-secrets/vault-example.hbs.md

Vault KV Secrets Engine versioning tip

---

release-notes.hbs.md

None. Change applies to 1.6 only

Added release notes for 1.6 Tanzu Desktop Tools

---

tap-gui/configurator/about.hbs.md

Update to TDP about.md

---

api-portal/about.hbs.md

This needs to be fixed in TAP 1.6, 1.5 and 1.4.

Fix the api portal link

---

intellij-extension/troubleshooting.hbs.md
partials/ide-extensions/_ki-config-writer-pull-requester.hbs.md
vscode-extension/troubleshooting.hbs.md

vscode: update troubleshooting section

---

release-notes.hbs.md

This is an update specificall for 1.6 as indicated also in the title and the name of the branch.

Update known issues for IJ Tap 1.6

---

scst-store/use-aws-rds.hbs.md

This could also be cherrypicked to `1-5-3`, `1-4-7`, `1-3-10` branches.

Add note that db name could be postgres if not specified in RDS UI

---

scst-scan/install-app-scanning.hbs.md

This is just for the TAP 1.6 branch

Add in instructions to restart AMR observer after app-scanning is installed

---

cloud-native-runtimes/install-cnrt.hbs.md
release-notes.hbs.md

No need to cherry-pick
This is for tap 1.6.0

CNR - Update docs for version 2.3.1

---

partials/ide-extensions/_ki-projects-with-spaces.hbs.md
release-notes.hbs.md

Revised IntelliJ trouble-shooting info 'spaces in path' for Tap 1.6

---

scst-store/api.hbs.md

update scst-store's API docs

---

install-gitops/eso/hashicorp-vault.hbs.md

Fix path to vault scripts in gitops-ri 0.2.0

---

intellij-extension/troubleshooting.hbs.md
intellij-extension/using-the-extension.hbs.md

Added troubleshooting steps for IntelliJ and macOS when using KUBECONFIG

---

intellij-extension/getting-started.hbs.md
intellij-extension/using-the-extension.hbs.md
partials/ide-extensions/_config-src-img-registry.hbs.md
partials/vscode-extension/_install.hbs.md
vs-extension/getting-started.hbs.md
vscode-extension/getting-started.hbs.md

- use Local Source Proxy as preferred method
- remove source image from tiltfiles
- set source image as optional parameter
1.6 

Update source-image requirements

---

about-package-profiles.hbs.md
contour/about.hbs.md
contour/configuring-cipher-suites-and-tls-version.hbs.md
contour/install.hbs.md
release-notes.hbs.md

No need to cherry pick
These changes are for the upcoming release TAP 1.6

Contour - Update docs for new contour version

---

install-aws/profile.hbs.md
install-offline/profile.hbs.md
install-online/profile.hbs.md
install-openshift/profile.hbs.md
multicluster/reference/tap-values-view-sample.hbs.md
release-notes.hbs.md
tap-gui/configurator/troubleshooting.hbs.md

Added guest breaking change to TAP-GUI

---

install-gitops/eso/hashicorp-vault.hbs.md

- Fix ereoneous `"` in documentation
- Remove old references to AWS in vault docs

Update vault gitops install

---

partials/scst-scan/_offline-airgap.hbs.md

Summary:
* Following up from this convo https://vmware.slack.com/archives/C01RNF49PND/p1683185250600199, added grype troubleshooting commands for the listing.json
1.6

[VSEE-1042] Add more grype troubleshooting commands for validating listing.json

---

install-gitops/eso/aws-secrets-manager.hbs.md
install-gitops/eso/hashicorp-vault.hbs.md
install-gitops/sops.hbs.md

Small fixes to new paths / output in 0.2.x of Installer

---

app-sso/reference/api/authserver.hbs.md
app-sso/tutorials/service-operators/identity-providers.hbs.md

appsso: add documentation for new userinfoURI endpoint.

---

scst-scan/install-app-scanning.hbs.md
scst-scan/verify-app-scanning.hbs.md

Summary:
* Add docs on how to validate scan report results specify for format/version schema with example.
1.6 

[VSEE-1008] Add validate scan format docs

---

security-and-compliance/harden-tap.hbs.md

We can add this for the TAP 1.6 branch

Fix typo - Security Analysis GUI is the correct term

---

install-gitops/eso/hashicorp-vault.hbs.md

Minor tweaks for those who are not doing the simplest storage of secrets in vault

[Gitops Installer] Add notes for "non-default" vault behaviour

---

scst-store/deployment-details.hbs.md

Add to scst-store doc about amr deployment

---

intellij-extension/troubleshooting.hbs.md

I tested this in latest RC build for Tap 1.6 and it works fine now.
Tap 1.6 only.

Remove resolved troubleshooting related to debug functions in IntelliJ

---

source-controller/reference.hbs.md

`1-4-7`, `1-5-2`, `1-5-3`, and `main`
---
- MavenArtifact API support version with Snapshot and Latest

MavenArtifact API support version with Snapshot and Latest

---

release-notes.hbs.md

Release notes for TAP 1.6 App Accelerator and ALV

---

scc/delivery-with-carvel-app.hbs.md
scc/delivery-with-flux.hbs.md

Update note (in scc) to revert to previous version

---

getting-started/about-supply-chains.hbs.md
scst-scan/scan-types.hbs.md

Add overlay for source scanning

---

cli-plugins/build-service/command-reference/tanzu_build-service.md
cli-plugins/build-service/command-reference/tanzu_build-service_build.md
cli-plugins/build-service/command-reference/tanzu_build-service_build_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_build_logs.md
cli-plugins/build-service/command-reference/tanzu_build-service_build_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_builder.md
cli-plugins/build-service/command-reference/tanzu_build-service_builder_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_builder_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_buildpack.md
cli-plugins/build-service/command-reference/tanzu_build-service_buildpack_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_buildpack_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterbuilder.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterbuilder_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterbuilder_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterbuildpack.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterbuildpack_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterbuildpack_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterstack.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterstack_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterstack_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterstore.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterstore_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_clusterstore_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_image.md
cli-plugins/build-service/command-reference/tanzu_build-service_image_list.md
cli-plugins/build-service/command-reference/tanzu_build-service_image_status.md
cli-plugins/build-service/command-reference/tanzu_build-service_image_trigger.md
cli-plugins/build-service/overview.hbs.md
cli-plugins/tanzu-cli-plugin.hbs.md
cli-plugins/tanzu-cli.hbs.md

This is for 1.6.0 and all future versions of tap

Add docs for tbs-cli-plugin

---

install-tanzu-cli.hbs.md

add v1.6.0 plugin group version for plugin install

---

template_variables.yaml

update tanzu cli to 0.90.1

---

scst-store/amr/architecture.hbs.md
scst-store/amr/overview.hbs.md

AMR alpha/beta warning

---

cli-plugins/insight/cli-overview.hbs.md
cli-plugins/insight/triaging-vulnerabilities.hbs.md
scst-scan/triaging-and-remediating-cves.hbs.md

Add example of vulnerability triage using insight cli

---

scalability.hbs.md

Updates to scale best practices page

---

release-notes.hbs.md
tap-gui/troubleshooting.hbs.md

Workaround to support IVS in TAP GUI for TAP 1.6.0

---

getting-started/about-vulnerability-scan-store.hbs.md
getting-started/add-test-and-security.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scst-scan/triaging-and-remediating-cves.hbs.md
scst-store/overview.hbs.md
tap-gui/plugins/scc-tap-gui.hbs.md

docs [META-1131]: Remove redundant links to the enable CVE scan section

---

scc/canary-deployment.hbs.md
scc/config-deploy-multi-env.hbs.md
scc/scc-how-to.hbs.md

Add guide to canary deployment with Carvel Packages

---

release-notes.hbs.md

Add security fixes to release notes for 1.4.7

Add security fixes to release notes for 1.4.7

---

release-notes.hbs.md

Add security fixes to release notes for 1.5.3

Add security fixes to release notes for 1.5.3

---

scst-store/amr/architecture.hbs.md

Missing new line above comment line made the line actually be rendered.
TAP 1.6.x (main)

fix comment

---

toc.hbs.md

Add Canary deployment new page to the table of contents

---

release-notes.hbs.md
tap-gui/troubleshooting.hbs.md

Add overlay to IVS workaround

---

install-gitops/eso/aws-secrets-manager.hbs.md
install-gitops/eso/hashicorp-vault.hbs.md
install-gitops/sops.hbs.md

Addressing some bugs in documentation for gitops story

---

release-notes.hbs.md

Add security fixes to release notes for 1.3.10

Add security fixes to release notes for 1.3.10

---

namespace-provisioner/ootb-supply-chain.hbs.md
scst-scan/scan-types.hbs.md
scst-scan/troubleshoot-scan.hbs.md
toc.hbs.md

Source scan optional

---

tap-gui/cluster-view-setup.hbs.md

Add app-scanning to k8s-reader

---

release-notes.hbs.md

Add vuln triage feature to 1.6 release notes

---

cli-plugins/insight/cli-docs/tanzu_insight_triage_update.hbs.md

Fix format issue under insight triage update documentation

---

release-notes.hbs.md

Add links to vuln triage 1.6 release notes

---

cli-plugins/accelerator/command-reference/tanzu_accelerator_push.hbs.md

Adding Local Source proxy links for App Acc

---

vs-extension/using-the-extension.hbs.md

update project generation steps to use App Accel

---

tap-gui/configurator/building.hbs.md

https://jira.eng.vmware.com/browse/ESBACK-326

add to tpb-config.yaml example

---

install-tanzu-cli.hbs.md

This PR depends on a template variable added in another PR #2731 
Add TanzuNet and GitHub release as options for binary download/install
TAP 1.6.x

update cli/plugin install instructions

---

template_variables.yaml

url_verson added for Tanzu CLI docs links

---

prerequisites.hbs.md

Prereq Grammar Updates

---

install-tanzu-cli.hbs.md

Adds next steps for NPC & Openshift

---

release-notes.hbs.md

Add Tanzu CLI

---

install-aws/resources.hbs.md

Updates Create AWS Resources for 1.25 and minor spelling

---

install-aws/resources.hbs.md
install-online/profile.hbs.md
local-source-proxy/install.hbs.md
local-source-proxy/prereqs.hbs.md
local-source-proxy/reference.hbs.md

LSP: profile sample updated

---

install-aws/profile.hbs.md

Editorial changes and syncing content from online install

---

install-online/profile.hbs.md

Fixes flag in online install command

---

install-aws/resources.hbs.md

Add's reference to tbs-full-deps repository

---

install-tanzu-cli.hbs.md

replace TAP 1.6 version with template variable for durability

---

namespace-provisioner/customize-installation.hbs.md
namespace-provisioner/troubleshooting.hbs.md
namespace-provisioner/use-case3.hbs.md
namespace-provisioner/use-case6.hbs.md
namespace-provisioner/use-cases.hbs.md
toc.hbs.md

Changes in this PR are for TAP 1.6

Add NSP grype airgaped usecase

---

scst-scan/app-scanning-troubleshooting.hbs.md
scst-scan/ivs-create-your-own.hbs.md

VSEE-1081 | added information about podTemplateScurityContext in app-scanning and trobleshooting

---

install-aws/resources.hbs.md

Includes additional capabilities included in TAP 1.6 which where not present in previous releases.
This is for TAP 1.6

Updates AWS Resources Page for TAP 1.6

---

install-aws/resources.hbs.md

Addresses formatting error on final footnote

---

local-source-proxy/prereqs.hbs.md

Adds instruction to create ECR repository and changes name

---

tap-gui/configurator/building.hbs.md

Deletes directive to `set-app-config`

---

getting-started/iterate-new-app-intellij.hbs.md
getting-started/iterate-new-app-vscode.hbs.md
release-notes.hbs.md
vscode-extension/troubleshooting.hbs.md

Extension update

---

tap-gui/configurator/running.hbs.md

> # Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
> 
> It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
> writer, except where earlier branches require factual changes to the content.
> For more information about the branches, see https://github.com/pivotal/docs-tap#branches
This commit doesn't need to be cherry-picked to any other branch. `main` will suffice. Thanks!

Remove unnecessary section from TDP YTT overlay docs

---

install-tanzu-cli.hbs.md

add tap_version variable and add durable x-link to internet-restricted installation instructions

---

tap-gui/tap-gui-rbac/set-up-tap-gui-prmssn-frmwrk.hbs.md

Disclosure about App Accelerator and Permission Framework

---

vs-extension/troubleshooting.hbs.md
vs-extension/using-the-extension.hbs.md

This update should be applied to all version branches.

update solution for debug session termination

---

scst-scan/clusterimagetemplates.hbs.md

[VSEE-1124] Fix registry params fields

---

contour/configuring-contour-with-domainmapping.hbs.md
toc.hbs.md

- Fixes request forwarding issues with DomaingMapping and autoTLS enabled

Add docs for header propagation with contour

---

scst-scan/integrate-app-scanning.hbs.md

Simplify workarounds for Scan 2.0 for 1.6.1

---

release-notes.hbs.md

chore: noting the deprecation of tekton cluster tasks

---

release-notes.hbs.md

this is for 1.6.1 release notes

Update tbs release notes

---

install-tanzu-cli.hbs.md

slight tweak to binary cli installation directions

---

release-notes.hbs.md

add tanzu CLI 1.0 GA note and provide durable external link

---

install-gitops/sops.hbs.md

https://jira.eng.vmware.com/browse/TANZUSC-4320

Add basic_auth config to sops page

---

install-tanzu-cli.hbs.md

updating the cli files name to download from tanzunet

updating the cli files name to download from tanzunet

---

install-gitops/eso/aws-secrets-manager.hbs.md
install-gitops/eso/hashicorp-vault.hbs.md
install-gitops/sops.hbs.md
install-gitops/upgrading.hbs.md

https://jira.eng.vmware.com/browse/TANZUSC-4314

Add instructions for patch versions

---

api-auto-registration/installation.hbs.md
api-auto-registration/key-concepts.hbs.md

Migrate the spec.location to the new format and announce deprecation

---

cli-plugins/apps/getting-started/installation.hbs.md

Please backport this change also to TAP 1.6.1

replace VERSION with template variable

---

install-gitops/reference.hbs.md
troubleshooting-tap/troubleshooting-gitops.hbs.md

[Gitops] Add error case for secret engine of vault

---

cli-plugins/tanzu-cli.hbs.md

simplify and update CLI and plugin install

---

template_variables.yaml

AppSSO - bump version to v5.0 for TAP 1.7

---

learning-center/about.hbs.md
learning-center/cve-mitigation.md
release-notes.hbs.md

CVE mitigation options for CVE-2023-26114 on Learning Center

CVE mitigation for CVE-2023-26114 on Learning Center

---

scst-scan/bring-your-own-scanner.hbs.md

Servers to services

---

tap-gui/configurator/building.hbs.md

Update building.hbs.md with new instructions on identifying foundation image

---

tap-gui/configurator/building.hbs.md

Updated TDP config to remove gitlab

---

scc/ootb-supply-chain-testing-with-jenkins.hbs.md

fix: fix typos in the jenkins cluster task docs

---

api-auto-registration/key-concepts.hbs.md

Add a note about using k8s service cluster DNS with static url

---

install-gitops/eso/aws-secrets-manager.hbs.md
install-gitops/eso/hashicorp-vault.hbs.md
install-gitops/sops.hbs.md

https://jira.eng.vmware.com/browse/TANZUSC-3960

Add documentation in-line for airgapped mode in gitops

---

release-notes.hbs.md
vscode-extension/troubleshooting.hbs.md

vscode: remove window debug issue

---

scc/delivery-with-carvel-app.hbs.md
scc/delivery-with-flux.hbs.md

We should cherry-pick it to:
- main
- 1-6-2.
Jira ticket: [ALM-129](https://jira.eng.vmware.com/browse/ALM-129)

Update instructions for GitOps delivery with Flux CD and Carvel App

---

api-auto-registration/configuration.hbs.md
api-auto-registration/installation.hbs.md
api-portal/install-api-portal.hbs.md
app-live-view/improved-security-and-access-control.hbs.md
app-sso/how-to-guides/platform-operators/installation.hbs.md
authn-authz/install.hbs.md
developer-conventions/install-dev-conventions.hbs.md
external-secrets/install-external-secrets-operator.hbs.md
integrations/tsm-tap-integration.hbs.md
scc/install-ootb-delivery-basic.hbs.md
scc/install-ootb-sc-basic.hbs.md
scc/install-ootb-sc-wtest-scan.hbs.md
scc/install-ootb-sc-wtest.hbs.md
scc/install-ootb-templates.hbs.md
scc/install-scc.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scst-policy/install-scst-policy.hbs.md
scst-scan/install-scanners.hbs.md
scst-scan/install-scst-scan.hbs.md
scst-scan/troubleshoot-scan.hbs.md
scst-store/install-scst-store.hbs.md
spring-boot-conventions/install-spring-boot-conventions.hbs.md
tap-gui/accessing-tap-gui.hbs.md
tap-gui/catalog/catalog-operations.hbs.md
tap-gui/database.hbs.md
tap-gui/install-tap-gui.hbs.md
tap-gui/integrations.hbs.md
telemetry/install-telemetry.hbs.md
troubleshooting-tap/troubleshoot-using-tap.hbs.md

These changes should be applied to TAP 1.5.x, 1.6.x, and 1.7.x

Correct `--package-name` flag to `--package`

---

cloud-native-runtimes/install-cnrt.hbs.md
release-notes.hbs.md

No need to cherry-pick to other branches

PDY-1684 Move contour specific parameters under cnrs.contour.*

---

scst-scan/clusterimagetemplates.hbs.md
scst-scan/ivs-carbon-black.hbs.md
scst-scan/ivs-create-your-own.hbs.md
scst-scan/ivs-grype.hbs.md
scst-scan/ivs-prisma.hbs.md
scst-scan/ivs-snyk.hbs.md
scst-scan/ivs-trivy.hbs.md
tap-gui/troubleshooting.hbs.md

Add scanner-name annotation to IVS

---

release-notes.hbs.md

Add SCC and OOTB component versions to release notes for TAP 1.6.2

---

install-tanzu-cli.hbs.md
template_variables.yaml

These are specific to the TAP 1.5.x line

Update Tanzu CLI/plugin installation instructions for TAP 1.5.4

---

release-notes.hbs.md

None, although this is the sibling PR to #2826

Document TBS known issues for TAP 1.4.8

---

release-notes.hbs.md

None, although this is the sibling PR to #2827

Document TBS known issues for TAP 1.3.11

---

release-notes.hbs.md

Add security fixes to release notes for 1.5.4

Add security fixes to release notes for 1.5.4

---

release-notes.hbs.md

Add security fixes to release notes for 1.4.8

Add security fixes to release notes for 1.4.8

---

tap-gui/configurator/building.hbs.md
tap-gui/configurator/concepts.hbs.md
tap-gui/configurator/external-plugins.hbs.md

Update configurator docs to refer to npmjs.com

---

app-sso/reference/api/clientregistration.hbs.md

appsso: explain when clientregistrations are used.

---

release-notes.hbs.md

Separate PRs created for v1.6.1 & v1.6.2 already

Added section on Tanzu Developer Tools for Visual Studio in the v1.6.1

---

release-notes.hbs.md

Add known issue for tap in 1-5-4

---

cloud-native-runtimes/install-cnrt.hbs.md
release-notes.hbs.md

PDY-1684 Change the verbiage for new configs under cnrs.contour.*

---

scc/delivery-with-carvel-app.hbs.md
scc/delivery-with-flux.hbs.md

- 1-6-1 (was done in #2810)
Jira ticket: [ALM-129](https://jira.eng.vmware.com/browse/ALM-129)

Update instructions for GitOps delivery with Flux CD and Carvel App - main

---

workloads/using-functions.hbs.md

This should be cherry-picked to all previous, currently supported, branches that include functions.
So, 1-6-3, 1-5-5, 1-4-9.

Warn about Functions (Beta) deprecation for <=1.6.3

---

release-notes.hbs.md

[#185291896] - Upgrade to cert-manager 1.12.x
---
`1.7.x`
_

docs(cert-manager): update release notes

---

app-sso/reference/api/clusterunsafetestlogin.hbs.md

`1.7.x`
_
---
[#185686470] - Spell out ClusterUnsafeTestLogin

docs(app-sso): spell out ClusterUnsafeTestLogin

---

release-notes.hbs.md

Updated to clarify that IVS 2.0 is supported for SCC GUI

---

eventing/about.hbs.md
release-notes.hbs.md

add deprecation warning to tap docs

---

install-tanzu-cli.hbs.md
release-notes.hbs.md
template_variables.yaml

TAP 1.7.0 - modernize Tanzu CLI & plugin install to 1.0.0

---

cli-plugins/apps/tutorials/create-update-workload.hbs.md

This change should be applied for TAP 1.6

docs: Remove maven sample with yaml/json parameters

---

release-notes.hbs.md

add ACS resolved issues for 1.5.5

---

application-configuration-service/about.hbs.md
release-notes.hbs.md

application configuration service docs for 1.6.3

---

cloud-native-runtimes/about.hbs.md
cloud-native-runtimes/how-to-guides/garbage_collection.hbs.md
cloud-native-runtimes/how-to-guides/index.hbs.md
release-notes.hbs.md
toc.hbs.md

- Update TOC
- Add release notes
- Add deprecation note

Add docs for CNRs garbage collection

---

getting-started/air-gap-workload.hbs.md
tanzu-build-service/tbs-workload-config.hbs.md

files updated with NuGet examples for .NET applications.

---

cli-plugins/insight/cli-docs/tanzu_insight.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_image_add.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_report.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_report_get.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_report_list.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_source_add.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_triage.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_triage_list.hbs.md
cli-plugins/insight/cli-docs/tanzu_insight_triage_rebase.hbs.md

draft: chore: [AMR-548] Update Insight CLI autogenerated docs

---

integrations/tsm-tap-integration.hbs.md

Additional branches to backport:
1-6-0
1-6-1
1-6-2
1-6-3

Updating TAP-TMS integration to use Where For Dinner vs Hungryman.

---

scst-scan/install-app-scanning.hbs.md

Fix missing prereq for Scan 2.0

---

release-notes.hbs.md

Adds Package Supply Chain 1.7 fixes to release notes

---

application-configuration-service/about.hbs.md
release-notes.hbs.md

Application Configuration Service docs for 1.7.0

---

scc/blue-green-with-flagger.hbs.md
scc/scc-how-to.hbs.md

add new page for blue-green deploy with flagger

Add page for blue-green with flagger

---

install-azure/profile.hbs.md
install-offline/profile.hbs.md
install-online/profile.hbs.md
install-openshift/profile.hbs.md
multicluster/reference/tap-values-build-sample.hbs.md
release-notes.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scst-scan/samples/private-image.hbs.md
scst-scan/samples/private-source.hbs.md
scst-store/multicluster-setup.hbs.md

VSEE-1092 | Added release note on deprecation

---

cli-plugins/insight/triaging-vulnerabilities.hbs.md

Add insight triage rebase example documentation

---

scst-store/amr/install-amr-observer.hbs.md

This note should be part of the 1.6.x TAP docs

Add note on amr observer not support self-signed registries

---

scst-scan/integrate-app-scanning.hbs.md

Change Default Scanner to Trivy with Scan 2.0

---

vscode-extension/troubleshooting.hbs.md

Added troubleshooting steps when using devcontainers on Windows

---

service-registry/install-service-registry.hbs.md

This is only for main and the 1.7 release

Fix copy/paste typo in service-registry install

---

spring-boot-conventions/configuring-liveliness-readiness-startup-probes.hbs.md
spring-boot-conventions/install-spring-boot-conventions.hbs.md
toc.hbs.md

This change is targeted for TAP 1.7 only

configure probes in spring boot conventions

---

install-openshift/profile.hbs.md

Update profile.hbs.md OpenShift versions for 1.7

---

app-sso/reference/known-issues.hbs.md

docs(app-sso): mention "unregister by deletion" semantics

---

release-notes.hbs.md

Update release-notes.hbs.md TKr 1.26.5 limitation.

---

scst-store/amr/configuration.hbs.md
scst-store/amr/install-amr-observer.hbs.md
scst-store/amr/troubleshooting.hbs.md
scst-store/deployment-details.hbs.md

[TAP 1.7.x] Update amr-observer tap-values

---

app-sso/how-to-guides/service-operators/index.hbs.md
app-sso/how-to-guides/service-operators/session-settings.hbs.md
toc.hbs.md

appsso: add session expiry docs

---

release-notes.hbs.md
services-toolkit/how-to-guides/authorize-claim-provisioner-classes.hbs.md
services-toolkit/how-to-guides/troubleshooting.hbs.md
services-toolkit/reference/api/rbac.hbs.md

This needs to go into
- main / 1.7

Services Toolkit: Changes to claim mechanics and resulting RBAC

---

spring-boot-conventions/config-probes.hbs.md
spring-boot-conventions/configuring-liveness-readiness-startup-probes.hbs.md
toc.hbs.md

This change is targeted for TAP 1.7 only

Update key to livenessProbe

---

service-registry/configure-workloads.hbs.md

this change is only for main/1.7.9

improve instructions for service registry resource claim

---

app-sso/how-to-guides/getting-started.hbs.md

appsso: update some of the language in the getting started guide

---

scst-scan/ivs-grype.hbs.md
scst-scan/ivs-trivy.hbs.md

DRAFT: [VSEE-1170] | IVS Sample Updates

---

release-notes.hbs.md

Add security fixes to release notes for 1.3.12

Add security fixes to release notes for 1.3.12

---

release-notes.hbs.md

Add security fixes to release notes for 1.5.5

Add security fixes to release notes for 1.5.5

---

api-auto-registration/api-curation.hbs.md

Remove mention of enable SCG in installation values

---

intellij-extension/getting-started.hbs.md

This really affects all versions of TAP so should be cherry-picked to as many versions as 
we are still reasonably maintaining docs for. (I.e. in theory: all branches... in practice: as many as you can/want to manage :-)

Launch IntelliJ from CLI please

---

install-gitops/eso.hbs.md
install-gitops/sops.hbs.md

1.5.x cherry-pick of https://github.com/pivotal/docs-tap/pull/2790

[Gitops] Add instructions for patch versions 1.5.x

---

vscode-extension/dev-containers.hbs.md

Added documentation about using local file mounts with DevContainers for Tanzu Developer Tools for VS Code

---

scst-store/api.hbs.md

chore: [AMR-549] Update SCST Store API docs

---

partials/scst-scan/_offline-airgap.hbs.md

VSEE | Added placeholder for pathing

---

cli-plugins/insight/cli-overview.hbs.md
cli-plugins/insight/query-sbom-reports.hbs.md
toc.hbs.md

chore: [AMR-547] Adding Insight CLI report examples and use cases

---

prerequisites.hbs.md

chore: [AMR-588] Update docs to include 'amr-graphql' in DNS records

---

scst-store/amr/graphql-query.hbs.md

chore: [AMR-533] Add instructions on how to connect to AMR GraphQL using cURL

---

api-auto-registration/api-curation.hbs.md
api-auto-registration/troubleshooting.hbs.md

Add known issue for conflicting groupId and version, update spec endpoint info

---

troubleshooting-tap/troubleshoot-install-tap.hbs.md

Just the main branch. This PR only applies to tap 1.7.

Document possible service binding error at install

---

scst-scan/install-app-scanning.hbs.md

Add concurrent scans config

---

tap-gui/plugins/scc-tap-gui.hbs.md

Fix default value to enable triage UI

---

release-notes.hbs.md
scst-store/database-index-corruption.hbs.md
scst-store/troubleshooting.hbs.md
toc.hbs.md

Chore: [AMR-612] - Troubleshoot Postgres database Index Corruption issue

---

workloads/server.hbs.md

* suggests for readers of the server workload that Ingress is available out of the box with the package supply chain
* 1-6-3

Use Package Supply Chain for Ingress

---

api-auto-registration/api-curation.hbs.md
api-auto-registration/troubleshooting.hbs.md

Add documentation for adding additional labels for generated SCG resources

---

release-notes.hbs.md

These changes are for the 1.5.6 release

update release notes for Application Configuration Service

---

partials/scst-scan/_offline-airgap.hbs.md

Added placeholder for pathing

---

release-notes.hbs.md

[#185889177](https://www.pivotaltracker.com/story/show/185889177)
TAP 1.7.0
_

Release notes for `sso.apps.tanzu.vmware.com/5.0.0`

---

scst-store/amr/configuration.hbs.md
scst-store/amr/troubleshooting.hbs.md
scst-store/deployment-details.hbs.md

chore: [AMR-593] Update docs to use new AMR resource name

---

install-offline/intro.hbs.md
install-offline/offline-ide-extensions.hbs.md

The instructions are not specific to a TAP version. But I suggest adding these notes to Tap 1.7 and Tap 1.6 docs.

Installing IDE extension in airgapped env

---

service-registry/install-service-registry.hbs.md

These changes are for the 1.7.0 release on the main branch.

Update Service Registry install prerequisites

---

scst-scan/app-scanning-beta.hbs.md
scst-scan/install-app-scanning.hbs.md
scst-scan/integrate-app-scanning.hbs.md
scst-store/amr/architecture.hbs.md
scst-store/amr/overview.hbs.md
scst-store/deployment-details.hbs.md

Remove alpha/beta references for AMR

---

scst-store/upgrading-amr-beta.hbs.md
scst-store/upgrading.hbs.md
toc.hbs.md

chore: [AMR-636] - Added AMR upgrade page

---

tap-gui/troubleshooting.hbs.md

Please cherry-pick this PR to branches 1-6-4 and main. This is based on feedback received in the internal assist channel that the troubleshooting steps are confusing since these are known issues and based on TAP profile configurations.

RRV: removes troubleshooting steps and mention these are known issues

---

scst-scan/verify-app-scanning.hbs.md

This change is intended for 1.7 and 1.6 branches.

Fix typo in get command for IVS

---

release-notes.hbs.md

Add security fixes for 1.6.4

---

release-notes.hbs.md

Add security fixes for 1.3.13

---

release-notes.hbs.md

Add security fixes for 1.4.10

---

release-notes.hbs.md

Add security fixes for 1.5.6

---

scc/blue-green-with-packageinstall.hbs.md

should be cherry-picked to 1.6.x

fix yaml formatting 

---

vscode-extension/dev-containers.hbs.md
vscode-extension/troubleshooting.hbs.md

Updated docs on Development Containers for VScode

---

partials/scst-scan/_offline-airgap.hbs.md

VSEE-1029 | added specific instructions to get and move grype databases for the airgap deployments

---

README.md
tanzu-buildpacks/about.hbs.md
toc.hbs.md

Resolves https://github.com/pivotal-cf/tanzu-buildpacks/issues/383

Add section for Tanzu buildpacks

---

install-gitops/reference.hbs.md

vault is supported only on public IaaS in TAP

---

release-notes.hbs.md

Added release notes for AA and ALV for TAP 1.7

---

application-accelerator/creating-accelerators/transforms/replace-text.hbs.md

This is for 1.7 (main) and can be backported as-is to 1.6 branch.

Document capturing groups in ReplaceText

---

scst-store/amr/install-amr-observer.hbs.md

Update the values schema for observer

---

scst-store/amr/auth-k8s-sa-autoconfiguration.hbs.md

Setup CEH auth token manually for observer

---

application-accelerator/provenance.hbs.md
scst-store/amr/graphql-query.hbs.md
toc.hbs.md

Fix https://github.com/pivotal/acc-release/issues/613
This applies to 1.7 only (main)

Document AA - AMR integration

---

release-notes.hbs.md
upgrading.hbs.md

Add notes about Service binding upgrade

---

cloud-native-runtimes/how-to-guides/app-operators/resource_management.hbs.md
cloud-native-runtimes/how-to-guides/troubleshooting.hbs.md
release-notes.hbs.md

- Add release note updates
- Add fixed issues
- Cleanup outdated troubleshooting section
- Add versions CNR/Contour will ship with to TAP release notes table
This change is intended for TAP 1.7.0, so only main.

Add release notes for CNR and Contour - TAP 1.7.0

---

tap-gui/configurator/building.hbs.md

Updated TPB references to 1.0.1

---

release-notes.hbs.md

adding release note about the fix for alm-150 in package supply chain

---

tap-gui/troubleshooting.hbs.md

TDP DORA Plugin Troubleshooting

---

tanzu-build-service/dependencies.hbs.md
tanzu-buildpacks/about.hbs.md

This change only applies to TAP 1.7
Resolves https://github.com/pivotal-cf/tanzu-buildpacks/issues/390

TAP 1.7: Update buildpacks/stacks versions in tbs/deps

---

scst-scan/ivs-create-your-own.hbs.md
scst-scan/ivs-custom-samples.hbs.md
scst-scan/verify-app-scanning.hbs.md

- main
- all 1.6.x and 1.7.x branches

VSEE-1169 | Updates to creating and verifying an IVS pages

---

namespace-provisioner/customize-installation.hbs.md

docs: update namespace provisioner docs to add link to AWS resources page

---

tap-gui/plugins/scc-tap-gui.hbs.md

[TINT-624](https://jira.eng.vmware.com/browse/TINT-624)

TINT-624 — Add note for CRD permissions

---

scst-scan/ivs-carbon-black.hbs.md

[Ready for merge] Output cbc scan results to a file to be published

---

scst-scan/install-app-scanning.hbs.md
scst-scan/install-scst-scan.hbs.md

[Ready for merge] Add both deployedThroughTmc and insertUserAndGroupID properties for installing scan-controller

---

scst-scan/ivs-snyk.hbs.md

- main
- all 1.6.x and 1.7.x branches

VSEE-1183 | IVS Sample Updates - Snyk

---

tap-gui/configurator/running.hbs.md

Added Configurator note on overlay permissions

---

tap-gui/configurator/building.hbs.md

Add a note (call out) about the necessary steps in a supply chain

---

scst-store/amr/auth-k8s-sa-autoconfiguration.hbs.md
scst-store/amr/auth-k8s-sa-user-defined.hbs.md
security-and-compliance/harden-tap.hbs.md

Harden by disabling AMR autoconfig

---

scst-scan/ivs-carbon-black.hbs.md

Make CBC docs similar format as snyk docs

---

scst-scan/install-app-scanning.hbs.md

- merge to main
- cherry-pick to all versions of this page (1.6.x, 1.7.x)

VSEE-1199 | Added optional section on configuring retention policies on scan result repo

---

scst-scan/app-scanning-troubleshooting.hbs.md

- main
- all 1.7.x and 1.6.x branches

VSEE-1172 | [DOCS] Update Scan 2.0 Troubleshooting page

---

scst-scan/ivs-trivy.hbs.md

- main
- 1.6.x and 1.7.x branches

VSEE-1182 | IVS Sample updates - Trivy

---

tap-gui/configurator/building.hbs.md
tap-gui/configurator/running.hbs.md

TDP COnfigurator fuil / lite option and optomize

---

tap-gui/troubleshooting.hbs.md

Add no auth configured section to troubleshooting doc

---

scst-scan/ivs-grype.hbs.md

This disclaimer presentation was also used [here](https://github.com/pivotal/docs-tap/blob/main/authn-authz/overview.hbs.md?plain=1#L41) 

[READY FOR MERGE] Add disclaimer for IVS grype and update db size requirements

---

install-azure/profile.hbs.md

Add note regarding setting external domain after initial install

---

services-toolkit/concepts/class-claim-vs-resource-claim.hbs.md
services-toolkit/concepts/service-consumption.hbs.md
services-toolkit/how-to-guides/authorize-claim-provisioner-classes.hbs.md
services-toolkit/how-to-guides/dynamic-provisioning-tanzu-postgresql.hbs.md
services-toolkit/reference/tanzu-service-cli.hbs.md
services-toolkit/tutorials/abstracting-service-implementation.hbs.md

Main branch please. This only applies to TAP `1.7`

Services toolkit RBAC edits

---

scst-scan/bring-your-own-scanner.hbs.md

Add a prereq section on what to know before doing Scan 2.0

---

bitnami-services/how-to-guides/index.hbs.md
bitnami-services/how-to-guides/troubleshooting.hbs.md
bitnami-services/upgrading-tkr.hbs.md

We would like the docs team to take a look at the document and decide how to appropriately present the different solutions proposed. We believe the first section should belong to the TAP 1.7 docs, and the second to the TAP 1.5 and 1.6 docs.

Document Bitnami services limitations and workarounds in restricted environments

---

aws-services/uninstall-aws-services.hbs.md

None. This only applies to TAP 1.7.

Document how to uninstall AWS Services

---

release-notes.hbs.md

This change is intended for TAP 1.7.0

[VSEE-1198] Add scst scan release notes

---

tap-gui/configurator/building.hbs.md
tap-gui/configurator/private-registries.hbs.md

Add private npm registry configuration documentation

---

release-notes.hbs.md

Mention dev containers support in release notes

---

application-accelerator/creating-accelerators/creating-accelerators.hbs.md

Removed Using local-path for publishing acc

---

release-notes.hbs.md

add tap-gui no authn prov config to known issues

---

tap-gui/configurator/building.hbs.md
tap-gui/plugins/about.hbs.md
template_variables.yaml

Added TDP default plugins in `template_variables.yaml` and then referenced in relevant docs files

tdp default plugins

---

scalability.hbs.md

These changes are to be applied in TAP docs for 1.7.0

Update scale configurations and best practises based on 1.7.0 executions

---

tap-gui/customize/customize-portal.hbs.md
toc.hbs.md

CHanged TDP Runtime Customiation

---

tap-gui/plugins/about.hbs.md

Adds info about TAP, validated, and external plugins

---

api-auto-registration/api-curation.hbs.md
api-auto-registration/key-concepts.hbs.md
api-auto-registration/usage.hbs.md
api-portal/about.hbs.md
getting-started/spring-apps/use-spring-cloud-gateway-kubernetes.hbs.md
template_variables.yaml

- Fix the links into variables
Question for the tech writer: Are you able to test the links? We want to variable-ize all the links to keep it in one place to quickly check and update them as new versions come in.

Add more details about TDP entity and API curation

---

tap-gui/configurator/building.hbs.md

TDP Configurator string typo

---

troubleshooting-tap/troubleshooting-gitops.hbs.md

Update troubleshoot for gitops delete-kubernetes-auth.sh

---

release-notes.hbs.md

1.7.0 release notes for Services Toolkit

---

scst-scan/ivs-snyk.hbs.md

This change targets TAP 1.7.0 and 1.6.x.

[VSEE-1162] Add snyk2spdx Dockerfile

---

about-package-profiles.hbs.md

Add TAP GUI Client to the componenets and profiles page

---

getting-started/spring-native-guide.hbs.md

Spring native guide for developers

---

getting-started/add-test-and-security.hbs.md
release-notes.hbs.md
scst-scan/integrate-app-scanning.hbs.md

VSEE-1245 | provided solution for the unaccessible location of Trivy through OOTB Supply Chain

---

troubleshooting-tap/troubleshooting-gitops.hbs.md

Statement improvement

---

scst-scan/app-scanning-troubleshooting.hbs.md
scst-scan/install-app-scanning.hbs.md
scst-scan/install-scst-scan.hbs.md
scst-scan/troubleshoot-scan.hbs.md

VSEE-1215 | [Docs] Update 1.7 docs on restricted cluster configuration

---

tap-gui/configurator/api-docs.md
tap-gui/configurator/surface-api-reference.hbs.md
toc.hbs.md

These docs are targeted for 1.7 only. No need to cherry-pick to any other branches.

ESBACK-387 - Adds API documentation for Tanzu Developer Portal Configurator

---

release-notes.hbs.md

minor change release notes 1.7

---

release-notes.hbs.md

Condensing AppSSO release note

---

scc/install-ootb-templates.hbs.md
security-and-compliance/pod-security-for-workloads.hbs.md
workloads/spec-reference.hbs.md
workloads/troubleshoot-workload.hbs.md

Configuring Pod Security for Workloads

---

tap-gui/plugins/about.hbs.md

describe tdp plugin

---

cartographer-conventions/troubleshooting.hbs.md
release-notes.hbs.md

docs: Extend memory limit for Workload with large SBOM

---

tap-gui/configurator/building.hbs.md

Fixed TPB variables

---

tap-gui/configurator/troubleshooting.hbs.md

Added troubleshooting for OOM

---

release-notes.hbs.md

Add security fixes for 1.4.11

---

release-notes.hbs.md

Add security fixes for 1.5.7

---

release-notes.hbs.md

Add security fixes for 1.6.5

---

release-notes.hbs.md

known issue for tap-gui TANZUSC-5139

---

release-notes.hbs.md

`tap.tanzu.vmware.com/1.7.1`
_

Known issues for `cert-manager.tanzu.vmware.com/2.4.1`

---

release-notes.hbs.md

`tap.tanzu.vmware.com/1.6.5`
_

Known issues for `cert-manager.tanzu.vmware.com/2.3.1`

---

release-notes.hbs.md

`tap.tanzu.vmware.com/1.6.5`
_

Rephrase cert-manager known issues

---

release-notes.hbs.md

Adds dev portal configurator to 1.7.0 release notes

---

external-secrets/install-external-secrets-operator.hbs.md

[TANZUSC-5098]
Please apply this documentation to TAP 1.7.0 and up.

Add Openshift instruction to External Secrets Operator

---

contour/how-to-guides/configuring-envoy.hbs.md
release-notes.hbs.md

clarify envoy topic and release note

---

template_variables.yaml

bump cli version to 1.1.0

---

contour/how-to-guides/configuring-envoy.hbs.md

revert mitigation for switching envoy from daemonset to deployment

---

release-notes.hbs.md

Adds Contour v1.25.3 bump to TAP 1.7.1 release notes.

Contour 1.7.1

---

app-sso/how-to-guides/service-operators/identity-providers.hbs.md

appsso: add id_token and userinfo constraint

---

tap-gui/configurator/building.hbs.md

Fixes errant instruction when applying TDP custom supply chain

---

getting-started/air-gap-workload.hbs.md
install-offline/intro.hbs.md
install-offline/set-up-namespaces.hbs.md
namespace-provisioner/customize-installation.hbs.md
namespace-provisioner/troubleshooting.hbs.md
namespace-provisioner/use-case3.hbs.md
namespace-provisioner/use-case7.hbs.md
toc.hbs.md

Please cherry-pick to all branches util 1.5

chore: Add Workload in air-gapped with NSP

---

app-live-view/install.hbs.md
spring-boot-conventions/enable-spring-native-apps.hbs.md
toc.hbs.md

This is targeted for only the TAP 1.8 release

Update ALV docs 

---

scc/authoring-supply-chains.hbs.md
scc/install-ootb-sc-wtest-scan.hbs.md
scc/ootb-supply-chain-testing.hbs.md

Small fixes

---

scst-policy/configuring.hbs.md

Could you cherry pick this to the 1.7.x branch as well? Please and thank you!

Add in example for TKGs for image policy

---

app-live-view/configuring-apps/convention-server.hbs.md
spring-boot-conventions/about.hbs.md
spring-boot-conventions/config-probes.hbs.md

This is targeted toward TAP 1.8 docs

App Live View doc updates for Spring Boot conventions to provide better clarity

---

scst-scan/install-app-scanning.hbs.md

chore: document disabling affinity assistant for scan v2

---

spring-boot-conventions/about.hbs.md
spring-boot-conventions/config-probes.hbs.md
spring-boot-conventions/install-spring-boot-conventions.hbs.md

Update docs for Spring Boot Conventions in App Live View

---

scc/ootb-supply-chain-testing.hbs.md

chore: add a default step template into the pipeline

---

service-bindings/about.hbs.md

`1.7.0` and `1.7.1`
fyi @teddyking

Add new Known Issue for Service Bindings

---

scc/dockerfile-based-builds.hbs.md

chore: document changes required for Kaniko to work with PSA restricted

---

scc/authoring-supply-chains.hbs.md

Add stepTemplate info for when a PSA is applied

---

release-notes.hbs.md

Add security fixes for 1.7.1

---

scst-policy/configuring.hbs.md

Please cherry pick this to any other branches where this MR was cherry picked to:
https://github.com/pivotal/docs-tap/pull/3143/files
(I saw someone left a comment requesting a change after it was merged - please let me know if there's anything I can do to help)

Update tkgs to vsphere with tanzu

---

install-aws/profile.hbs.md

- 1.7.x (1.7.0 onwards)
- 1.8.0
- 1-7-1
- 1-7-2

add registry secret for aws install (TAP 1.7.x, TAP 1.8.0)

---

install-aws/profile.hbs.md
install-aws/set-up-namespaces.hbs.md

- 1.4.x (1.4.0 onwards)
- 1.5.x (1.5.0 onwards)
- 1-5-7
- 1-4-12
- 1-4-11

add registry secret and placeholder secret for aws install (TAP 1.4.x, TAP 1.5.x)

---

install-aws/profile.hbs.md
install-aws/set-up-namespaces.hbs.md

add registry secret and placeholder secret for aws install (TAP 1.6.x)

---

install-online/profile.hbs.md

The change should be cherry-picked to all 1.6 and 1.7 versions.

Update grype NSP notice

---

tap-gui/configurator/create-plug-in-wrapper.hbs.md
tap-gui/configurator/dependency-version-reference.hbs.md
tap-gui/configurator/how-to-use-surfaces.hbs.md
tap-gui/plugins/about.hbs.md

create a TDP plugin tutorial

---

cli-plugins/apps/getting-started/installation.hbs.md
cli-plugins/apps/tutorials/create-update-workload.hbs.md

remove references to apps plugin gitHub repo

---

multicluster/about.hbs.md
scc/authoring-supply-chains.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scc/ootb-supply-chain-testing.hbs.md

1.7
This work updates language that was added in PR #3139. The changes in #3139 were also meant to be backported to TAP 1.7 docs (but it does not look like that's happened yet).

Clarifying inner outer loop

---

release-notes.hbs.md
scst-scan/troubleshoot-scan.hbs.md

Added pss panic to known issues for 1.7.0 and 1.7.1 and troubleshooting also indicated that this is fixed in release 1.7.2

---

release-notes.hbs.md

docs(cert-manager): no more known issues in 1.7.2

---

release-notes.hbs.md

docs(cert-manager): no more known issues in 1.6.6

---

release-notes.hbs.md

Add security fixes for 1.7.2

---

release-notes.hbs.md

Add security fixes for 1.6.6

---

release-notes.hbs.md

Add security fixes for 1.4.12

---

scst-scan/app-scanning-troubleshooting.hbs.md

VSEE-1288 | corrected a typo in a yaml to disable affinity assistant on tekton pipeline

---

release-notes.hbs.md

Add security fixes for 1.5.8

---

service-registry/configure-eureka-servers.hbs.md
service-registry/configure-workloads.hbs.md

Updates service registry examples (TAP 1.7.x and 1.8.x)

---

release-notes.hbs.md

1.7 only
Documenting https://jira.eng.vmware.com/browse/TANZUSC-5097

TANZUSC-5097 known issue

---

install-aws/profile.hbs.md

Update to #3160
- 1.7.x (1.7.0 onwards)
- 1.8.0
- 1-7-1
- 1-7-2

add optional to secret creation in aws install (TAP 1.7.x, TAP 1.8.0)

---

install-aws/profile.hbs.md
install-aws/set-up-namespaces.hbs.md

Update to #3161 
1.6.x (1.6.0 onwards)
1-6-5

add optional to secret creation in aws install (TAP 1.6.x)

---

install-aws/profile.hbs.md
install-aws/set-up-namespaces.hbs.md

Updates to #3162 
- 1.4.x (1.4.0 onwards)
- 1.5.x (1.5.0 onwards)
- 1-5-7
- 1-4-12
- 1-4-11

add optional to secret creation in aws install (TAP 1.4.x, TAP 1.5.x)

---

tap-gui/configurator/create-plug-in-wrapper.hbs.md

fixes for wrapping a backstage plugin

---

scst-store/amr/graphql-query.hbs.md

Update certificate name

---

contour/how-to-guides/index.hbs.md
contour/how-to-guides/troubleshooting.hbs.md
troubleshooting-tap/troubleshoot-components.hbs.md

add troubleshooting section to contour

---

namespace-provisioner/use-case6.hbs.md

Please cherry pick this into the 1.7.x branch. Thanks!!

Fix linebreak

---

scc/dockerfile-based-builds.hbs.md

Added label "part-of" in workload sample of example1 docker workload deployment steps

Added label "part-of" in workload sample of example1 docker workload deployment steps

---

app-live-view/connector-deployment-modes.md
app-live-view/improved-security-and-access-control.hbs.md
app-live-view/install.hbs.md
toc.hbs.md

This is targeted for only TAP 1.8 release

Connector deployment modes in ALV

---

cli-plugins/accelerator/overview.hbs.md

The indentation of `ingress` was off.

Fix indenting

---

release-notes.hbs.md

Add security patches to 1.7.3 release notes

---

release-notes.hbs.md

Add security patches to 1.6.7 release notes

---

release-notes.hbs.md

Add security patches to 1.5.9 release notes

---

release-notes.hbs.md

Updating patched CVEs for 1.5.9 release for AppConfigService

---

app-live-view/configuring-apps/external-observability-tools.hbs.md
toc.hbs.md

Add documentation in AppLiveView section about how to add external observability tools

---

app-live-view/configuring-apps/external-observability-tools.hbs.md

This is targeted for TAP 1.8 release

Add workaround for datadog agent issue on aks

---

release-notes.hbs.md

Only for TAP 1.5.10
See gh-3220 and gh-3221.

appsso: 1-5-10 scopes fix

---

authn-authz/binding.hbs.md

fix EOF placement

---

namespace-provisioner/use-case3.hbs.md

**this change is applicable to the branches - 1-7-3 and 1-6-7**

remove known limitation blurb as this has been addressed since TAP 1.6

---

tap-gui/configurator/building.hbs.md

Update building.hbs.md t fix tdp/tpb typo

---

aws-services/install-aws-services.hbs.md
aws-services/reference/package-values.hbs.md
aws-services/reference/supported-services.hbs.md
aws-services/reference/supported-topologies.hbs.md
release-notes.hbs.md

* Adds Amazon MQ (RabbitMQ) service
* Update release notes

Add AWS Services docs for TAP 1.8

---

release-notes.hbs.md

Updates the release notes for the packages contributed by the services toolkit team.

1.8 release notes from services toolkit team

---

service-bindings/install-service-bindings.hbs.md

Fix outdated servicebinding install doc. Please cherry pick to TAP 1.7 docs as well. Thanks!

Fix outdated servicebinding install doc

---

tap-gui/plugins/application-accelerator-git-repo.hbs.md

Add a note for self-hosted GitLab

---

aws-services/reference/version-matrix.hbs.md

No. This PR is for 1.8 TAP only. Thanks!

Add a version matrix for aws services

---

tap-gui/configurator/building.hbs.md

Update TDP Configurator id

---

aws-services/install-aws-services.hbs.md
aws-services/reference/package-values.hbs.md
aws-services/reference/supported-topologies.hbs.md

None, this is only for TAP 1.8.

Fix AWS Services docs for TAP 1.8

---

bitnami-services/reference/version-matrix.hbs.md

Only for 1.8 tap please. Thanks!

Add version matrix for bitnami services

---

release-notes.hbs.md

docs(cert-manager): add release notes for TAP 1.8.x

---

release-notes.hbs.md

docs(app-sso): release notes for TAP 1.8.x

---

release-notes.hbs.md

Please also cherry-pick this MR to the 1.7.4 branch as well.

[AMR-679] Adding release notes for MDS to include fix for the GraphQL last page bug

---

tap-gui/configurator/building.hbs.md

Update regex for configurator

---

tap-gui/configurator/dependency-version-refs.hbs.md

Draft: Add dependency version for TAP 1.8

---

tap-gui/configurator/dependency-version-refs.hbs.md

Update vmware-tanzu dependency table to refer only to tap 1.8

---

prerequisites.hbs.md

Update prerequisites.hbs.md with K8s versions and OpenShift support

Update prerequisites.hbs.md with K8s versions and OpenShift support

---

supply-chain/catalog/about.hbs.md
supply-chain/catalog/conventions.hbs.md
supply-chain/catalog/idioms.hbs.md
supply-chain/how-to/about.hbs.md
supply-chain/how-to/troubleshooting.hbs.md

Add documentation for Conventions Component

---

prerequisites.hbs.md

Update prerequisites.hbs.md with TKGi support

Update prerequisites.hbs.md with TKGi support

---

release-notes.hbs.md

scst store doc changes for 1.8.0

---

install-offline/profile.hbs.md

It can be added to all previous versions.

Add repository examples for registries

---

application-accelerator/creating-accelerators/transforms/open-rewrite-recipe.hbs.md

Fix https://github.com/pivotal/acc-release/issues/705
This applies to TAP 1.8 onward only

Update OpenRewrite recipes supported by app accelerator

---

application-accelerator/creating-accelerators/using-local-engine-server.hbs.md
toc.hbs.md

Add doc for App Accelerator Local server

---

release-notes.hbs.md

- Links are under the assumption that [this PR](https://github.com/pivotal/docs-tanzu-buildpacks/pull/1904) will be merged and published.
---
This is only relevant for 1.8

[1.8.0] release notes: Add notes for buildpacks+stacks

---

scst-scan/overview.hbs.md
scst-scan/recurring-scanning.hbs.md

Add Recurring Scan Feature

---

install-gitops/eso/aws-secrets-manager.hbs.md
install-gitops/eso/hashicorp-vault.hbs.md
install-gitops/sops.hbs.md
install-offline/grype-offline-airgap.hbs.md
install-offline/intro.hbs.md
install-offline/scan-offline-airgap.hbs.md
namespace-provisioner/use-case6.hbs.md
partials/scst-scan/_offline-airgap.hbs.md
scst-scan/offline-airgap.hbs.md
toc.hbs.md

None, this is a 1.8 capability.

Update Air Gap Instructions to Use Scan 2.0 with Trivy

---

release-notes.hbs.md

* I'll be cherry-picking to the other patch branches because it won't be a direct cherry-pick and needs a few tweaks

Contour for TAP 1.5.10 release notes

---

release-notes.hbs.md

* I'll cherry-pick this to 1.7 because there are going to be slight changes to the contents

Contour release notes 1 6 8

---

release-notes.hbs.md

Add security patches to 1.5.10 release notes

Add security patches to 1.5.10 release notes

---

release-notes.hbs.md

Add security patches to 1.6.8 release notes

Add security patches to 1.6.8 release notes

---

release-notes.hbs.md

Add security patches to 1.7.4 release notes

Add security patches to 1.7.4 release notes

---

supply-chain/reference/catalog/conventions.hbs.md

Add the 'valueFrom' field to the Conventions component

---

supply-chain/reference/catalog/conventions.hbs.md

Revert "Add the 'valueFrom' field to the Conventions component"

---

release-notes.hbs.md

Manohar discovered an issue with TMC and AMR observer secret collection.
This issue affects 1.7.0 - 1.7.4. We plan to fix it in 1.7.5.
This release note change pertains to 1.7.0 - 1.7.4. We plan to fix it in 1.7.5.

Document AMR observer collection issue in release notes

---

tas-migration/migrating-from-sso-for-tas.hbs.md

For the migration docs.
cc @YugangW

appsso: improve migration docs

---

cloud-native-runtimes/how-to-guides/troubleshooting.hbs.md
release-notes.hbs.md

Adds CNR upgrade bug troubleshooting

---

cloud-native-runtimes/how-to-guides/troubleshooting.hbs.md

Update CNR troubleshooting

---

supply-chain/reference/catalog/output-types.hbs.md

docs: document ALM output types

---

partials/scst-scan/_offline-airgap.hbs.md
scst-scan/recurring-scanning.hbs.md

Scan updates for PR Comments

---

contour/how-to-guides/configuring-contour-with-loadbalancer-tls-termination.hbs.md

contour: fix indentation in yaml example

---

tanzu-build-service/tbs-slsa-attestation.hbs.md

No cherry-picking required, this is for the upcoming TAP 1.8

Docs for TBS with SLSA attestations

---

toc.hbs.md

Followup to #3229 
No cherry picking required.

Add TBS SLSA docs to ToC

---

cloud-native-runtimes/how-to-guides/observability.hbs.md

* 1-7-5
* 1-7-4
* 1-6-9
* 1-6-8
* 1-5-10
* 1-5-11

Updates broken link to Prometheus docs

---

partials/_set-up-namespaces.hbs.md

1-7-5
1-7-4
1-6-9
1-6-8
1-5-10
1-5-11

Updates link to a more specific page for dev namespaces

---

application-accelerator/creating-accelerators/using-local-engine-server.hbs.md

Fix typos in local-engine-server doc

---

release-notes.hbs.md

App Accelerator and App Live View Release Notes for TAP 1.8

---

release-notes.hbs.md

1.8
Closes [ESBACK-678](https://jira.eng.vmware.com/browse/ESBACK-678)

note tdp configurator version jump to release notes

---

release-notes.hbs.md

Minor edit to release notes tap 1.8

---

about-package-profiles.hbs.md

1.7.  These were missed in that Release

Fix SCST status in profiles

---

application-accelerator/creating-accelerators/transforms/chain.dot
application-accelerator/creating-accelerators/transforms/chain.svg
application-accelerator/creating-accelerators/transforms/combo.dot
application-accelerator/creating-accelerators/transforms/combo.svg
application-accelerator/creating-accelerators/transforms/combo1.dot
application-accelerator/creating-accelerators/transforms/combo1.svg
application-accelerator/creating-accelerators/transforms/combo2.dot
application-accelerator/creating-accelerators/transforms/combo2.svg
application-accelerator/creating-accelerators/transforms/conflict-resolution1.dot
application-accelerator/creating-accelerators/transforms/conflict-resolution1.svg
application-accelerator/creating-accelerators/transforms/conflict-resolution2.dot
application-accelerator/creating-accelerators/transforms/conflict-resolution2.svg
application-accelerator/creating-accelerators/transforms/loop1.dot
application-accelerator/creating-accelerators/transforms/loop1.svg
application-accelerator/creating-accelerators/transforms/loop2.dot
application-accelerator/creating-accelerators/transforms/loop2.svg
application-accelerator/creating-accelerators/transforms/merge.dot
application-accelerator/creating-accelerators/transforms/merge.svg
application-accelerator/creating-accelerators/transforms/open-rewrite-recipe.dot
application-accelerator/creating-accelerators/transforms/open-rewrite-recipe.svg
application-accelerator/creating-accelerators/transforms/replace-text1.dot
application-accelerator/creating-accelerators/transforms/replace-text1.svg

Adapt diagram colors for accessibility

---

tap-gui/catalog/catalog-operations.hbs.md

This can be applied to all supported versions of TAP.

clarify instructions for setting up Yelb Catalog

---

supply-chain/platform-engineering/how-to/installing-supply-chains/about.hbs.md
supply-chain/platform-engineering/how-to/installing-supply-chains/install-authoring-profile.hbs.md
supply-chain/platform-engineering/how-to/installing-supply-chains/install-manual.hbs.md
supply-chain/platform-engineering/how-to/installing-supply-chains/post-install-configuration.hbs.md

chore: adding docs for installing supply-chain

---

scst-scan/recurring-scanning.hbs.md

Add more recurring scan config info

---

release-notes.hbs.md

Add security patches for 1.8

---

getting-started/air-gap-workload.hbs.md
install-offline/intro.hbs.md
partials/scst-scan/_offline-airgap.hbs.md
release-notes.hbs.md
scst-scan/offline-airgap.hbs.md
scst-scan/verify-app-scanning.hbs.md

Minor updates to Scan Components for 1.8

---

crossplane/reference/version-matrix.hbs.md

Small MR to bump versions in crossplane version matrix.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.8.x

Bump crossplane version matrix

---

supply-chain/development/how-to/about.hbs.md
supply-chain/development/how-to/create-workloads.hbs.md
supply-chain/development/how-to/discover-workloads.hbs.md
supply-chain/development/how-to/observe-runs.hbs.md

https://jira.eng.vmware.com/browse/TAPSC-60
https://jira.eng.vmware.com/browse/TAPSC-61
https://jira.eng.vmware.com/browse/TAPSC-62
N/A

Add how-to sections for tanzu workload commands

---

release-notes.hbs.md

Updates to DORA Metrics for TAP v1.8.0.

Adds drop-down filters for DORA Metrics

---

fluxcd-source-controller/use-flux-sc.md
scc/building-from-source.hbs.md

Documentation for git repository authentication with Custom CA

---

supply-chain/reference/catalog/output-types.hbs.md

Documentation for the Source Component output

---

supply-chain/development/how-to/install-the-cli.hbs.md
supply-chain/platform-engineering/how-to/install-the-cli.hbs.md

docs: tanzu cli workload and supplychain plugin installation docs

---

supply-chain/reference/catalog/output-types.hbs.md

This is a beta feature introduced in 1.8 and beyond so this only needs to go to `main`

Add buildpack build output

---

scalability.hbs.md

Please cherry pick this into the 1.7 and 1.8 branches. Thank you!

Update amr-observer size recommendations

---

release-notes.hbs.md

Adds CNR 2.5.1 release notes

---

scst-scan/tanzu-supply-chain/create-supply-chain-with-app-scanning.hbs.md

Fix listing and add link to tanzu supply chains

---

supply-chain/development/how-to/observe-runs.hbs.md

Add tanzu workload run get docs

---

release-notes.hbs.md

Adds Contour release notes for TAP 1.8

---

scst-store/use-external-database.hbs.md

Fix acroynms

---

release-notes.hbs.md

Update Verbiage for CycloneDX release notes

---

release-notes.hbs.md

doc known issues in alm-catalog

---

scst-scan/recurring-scanning.hbs.md

Add note about the scan step

---

scst-scan/recurring-scanning.hbs.md
scst-store/multicluster-setup.hbs.md

This is for TAP 1.8 and up. Thanks!!

Recurring scans edit

---

getting-started/add-test-and-security.hbs.md

Add direct to recurring scanning

---

release-notes.hbs.md

Adding notes for Service Registry

---

tanzu-build-service/dependencies.hbs.md

This change only applies to TAP 1.8
Part of https://github.com/pivotal-cf/tanzu-buildpacks/issues/435

TAP 1.8 buildpack/stack docs

---

release-notes.hbs.md

TAP 1.8 only please and thank you!

Add known issue for TANZUSC-6133

---

supply-chain/reference/catalog/about.hbs.md
supply-chain/reference/catalog/output-types.hbs.md

I hope this is more consistant

fix catalog and types

---

scst-scan/integrate-app-scanning.hbs.md

OOTB scanning: Fix indentation and property name

---

release-notes.hbs.md

TAP 1.8 and up please =) 
Thank you!

Remove recommendation to use scan 2.0

---

supply-chain/development/how-to/install-the-cli.hbs.md
supply-chain/platform-engineering/about.hbs.md
supply-chain/platform-engineering/how-to/deploying-supply-chains/install.hbs.md
supply-chain/platform-engineering/how-to/installing-supply-chain/install-authoring-profile.hbs.md
supply-chain/platform-engineering/how-to/installing-supply-chain/post-install-configuration-nsp.hbs.md
toc.hbs.md

docs: PE Section updates for Tanzu Supply Chains

---

supply-chain/development/tutorials/deploy-your-first-workload.hbs.md
supply-chain/platform-engineering/tutorials/my-first-supply-chain.hbs.md

docs: Dev tutorial - Deploy your first workload

---

scalability.hbs.md

No cherry-pick needed as these changes are coming as part of 1.8.0 scale testing.

Update AMR observer example resources as same defined in table for scale env

---

supply-chain/known-issues.hbs.md

docs: supply-chain-openshift-known-issue

---

release-notes.hbs.md

This issue is fixed in TAP 1.8.0, as well as TAP 1.7.5

SCST Store resolved issue

---

cloud-native-runtimes/how-to-guides/troubleshooting.hbs.md
release-notes.hbs.md

Updates CNR resolved issue

---

partials/_full-deps.hbs.md

No cherry-picks necessary
To use nested lists it needs exactly 4 spaces, and the sub-list must use `1.` for it to auto-increment.
Before:
After:

Fix whitespace and styling with TBS deps

---

tap-gui/cluster-view-setup.hbs.md

TANZUSC-6139 documentation task
None
@RichardJJG

documents workaround TANZUSC-6074

---

prerequisites.hbs.md

vsphere for TKGi
please update https://github.com/pivotal/docs-tap/blob/main/k8s-matrix.hbs.md as well.

Update prerequisites.hbs.md adding vsphere for TKGi

---

aws-services/install-aws-services.hbs.md

Fix Subnet ID definition in aws services

---

partials/_full-deps.hbs.md

This needs to be in 1.8.0 if possible and future 1.8 versions

Fix typo full deps install

---

partials/scst-scan/_offline-airgap.hbs.md

Missed Tag on Trivy AirGap relocate

---

release-notes.hbs.md

This is for TAP 1.8 and up
Thanks!

Add workaround for missing store ca issue

---

multicluster/reference/tap-values-build-sample.hbs.md

Please cherry pick this into the 1.8 branch as well. 
Thanks!

Fix typo for app_scanning

---

spring-boot-conventions/about.hbs.md
spring-boot-conventions/enable-prometheus-scraping.md
toc.hbs.md

Add docs for prometheus scraping support in Spring Boot Conventions 

---

install-openshift/profile.hbs.md

Update profile.hbs.md adding OpenShift 4.15

---

bitnami-services/reference/package-values.hbs.md

Update bitnami package values

---

release-notes.hbs.md

This should be part of the 1.7.x line

Add SCST Scan store CA cert known issue for 1.7 branch

---

release-notes.hbs.md

Add security patches for 1.8.1

---

release-notes.hbs.md

Add security patches for 1.7.5

---

release-notes.hbs.md

Remove deprecated services toolkit APIs

---

release-notes.hbs.md

Update release-notes.hbs.md removing the fixed known issue from 1.8.1

Update release-notes.hbs.md removing the fixed known issue from 1.8.1

---

release-notes.hbs.md

Please cherry pick this to the 1.8.x TAP line as well.
Thanks!

Add SCST Policy TUF default known issue

---

release-notes.hbs.md

Please cherry pick this to the 1.8.x branch as well.
Thanks!

Fix work around and add more detail to KI

---

scalability.hbs.md

Update how to scale services toolkit

---

services-toolkit/how-to-guides/troubleshooting.hbs.md

There can still be issues with managed resources if Synced=True

---

tas-migration/buildpacks/index.hbs.md

document ca cert expiry issue for scst-store

---

crossplane/how-to-guides/troubleshooting.hbs.md
release-notes.hbs.md

Add a known issue and workaround for a TLS verification issue with the Crossplane Package in TAP 1.8.0 and 1.8.1.
**Which other branches do you want a technical writer to cherry-pick this PR to (if any)?**
1.8.0 and 1.8.1. This issue will be fixed in 1.8.2

Add known issue for Crossplane for TAP 1.8.0/1

---

scst-store/amr/configuration.hbs.md

* 1-8-2
* 1-8-1
* 1-7-6
* 1-7-5

Update example amr observer config

---

release-notes.hbs.md

Deprecate service offering APIs from services toolkit

---

fluxcd-source-controller/about.hbs.md
fluxcd-source-controller/install.hbs.md
scalability.hbs.md
scc/building-from-source.hbs.md
scc/delivery-with-flux.hbs.md
scst-store/amr/architecture.hbs.md

- updateGitRepository API to v1
- add instructions for increasing resource limits
TAP 1.9.0

Update Flux Source Controller documentation

---

scst-store/amr/configuration.hbs.md

Typos in amr config

---

developer-conventions/install-dev-conventions.hbs.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 
n/a
This change was requested [here](https://jira.eng.vmware.com/browse/TANZUSC-6316)

Update developer-conventions install docs to specify conventions pre-requisite

---

app-sso/how-to-guides/service-operators/curate-service-offering.hbs.md

Targets TAP versions:
- 1.6
- 1.7
- 1.8
- 1.9

appsso: fix ClusterWorkloadRegistrationClass spec

---

scst-store/multicluster-setup.hbs.md

This is just for the 1.9.x branch. Thanks!

Add command to decode the cert

---

cartographer-conventions/install-conv-service.hbs.md
source-controller/install-source-controller.hbs.md

Condensed install log for CC and TSC

---

app-sso/how-to-guides/service-operators/identity-providers.hbs.md

Please apply to TAP 1.7, 1.8 and 1.9.

appsso: improve identity-providers docs

---

supply-chain/platform-engineering/how-to/installing-supply-chain/installing-manually.hbs.md

docs: fix package install command in manual installation docs

---

upgrading.hbs.md

Not sure if this is the best place to put this, but we'd like to call out this breaking change in the upgrade docs as well as we anticipate that users will run into this issue.
This is just for the 1.9.x branch (I'm not sure if this should carry over to future branches... maybe since users can potentially upgrade from 1.7, 1.8 -> 1.10)

Add note about breaking change in upgrade docs

---

supply-chain/platform-engineering/how-to/installing-supply-chain/installing-manually.hbs.md

Please cherry pick this to the 1.8.x branch as well.
Thanks!!

Add manual install commands for trivy-component

---

aws-services/how-to-guides/troubleshooting.hbs.md
release-notes.hbs.md

* Adds resolved issues for AWS Services and Crossplane for TAP 1.8.2

Stk 1.8.2 resolved issues

---

release-notes.hbs.md

- https://jira.eng.vmware.com/browse/TANZUSC-6327
Needs to be applied to 1.8.2, let me know if I should be the one opening that PR myself :)

Add resolved issue to ALM Catalog release notes

---

release-notes.hbs.md

Adding ALV and AA Release notes for TAP 1.9

---

getting-started/add-test-and-security.hbs.md
release-notes.hbs.md
scst-scan/create-scan-template.hbs.md
scst-scan/explanation.hbs.md
scst-scan/install-prisma-integration.hbs.md
scst-scan/install-scanners.hbs.md
scst-scan/install-scst-scan.hbs.md
scst-scan/install-snyk-integration.hbs.md
scst-scan/install-trivy-integration.hbs.md
scst-scan/integrate-app-scanning.hbs.md
scst-scan/observing.hbs.md
scst-scan/policies.hbs.md
scst-scan/results.hbs.md
scst-scan/samples/blob.hbs.md
scst-scan/samples/overview.hbs.md
scst-scan/samples/private-image.hbs.md
scst-scan/samples/private-source.hbs.md
scst-scan/samples/public-image-compliance.hbs.md
scst-scan/samples/public-source-compliance.hbs.md
scst-scan/scan-1-0.hbs.md
scst-scan/scan-crs.hbs.md
scst-scan/scan-types.hbs.md
scst-scan/triaging-and-remediating-cves.hbs.md
scst-scan/troubleshoot-rego.hbs.md
scst-scan/upgrading.hbs.md

Deprecate scan 1 0

---

release-notes.hbs.md

Add security patches for 1.8.2

Add security patches for 1.8.2

---

release-notes.hbs.md

Add security patches for 1.7.6

Add security patches for 1.7.6

---

release-notes.hbs.md

Add security patches for 1.6.10

Add security patches for 1.6.10

---

release-notes.hbs.md

Add security patches for 1.5.12

Add security patches for 1.5.12

---

release-notes.hbs.md

Update services release notes

---

supply-chain/platform-engineering/how-to/supply-chain-authoring/configure.hbs.md
toc.hbs.md

[TAPSC-166](https://jira.eng.vmware.com/browse/TAPSC-166)

Add how-to guide for SC overrides/defaults

---

prerequisites.hbs.md

Strengthen Production Phrasing for AMR and MDS DB 

---

release-notes.hbs.md

Add known issue for Cartographer Conventions

---

tanzu-build-service/dependencies.hbs.md

This change only applies to 1.9. Part of pivotal-cf/tanzu-buildpacks#482.

TAP 1.9 buildpack/stack docs

---

getting-started/add-test-and-security.hbs.md
release-notes.hbs.md
scst-scan/create-scan-template.hbs.md
scst-scan/explanation.hbs.md
scst-scan/install-prisma-integration.hbs.md
scst-scan/install-scanners.hbs.md
scst-scan/install-scst-scan.hbs.md
scst-scan/install-snyk-integration.hbs.md
scst-scan/install-trivy-integration.hbs.md
scst-scan/observing.hbs.md
scst-scan/policies.hbs.md
scst-scan/results.hbs.md
scst-scan/samples/blob.hbs.md
scst-scan/samples/overview.hbs.md
scst-scan/samples/private-image.hbs.md
scst-scan/samples/private-source.hbs.md
scst-scan/samples/public-image-compliance.hbs.md
scst-scan/samples/public-source-compliance.hbs.md
scst-scan/scan-1-0.hbs.md
scst-scan/scan-crs.hbs.md
scst-scan/scan-types.hbs.md
scst-scan/triaging-and-remediating-cves.hbs.md
scst-scan/troubleshoot-rego.hbs.md
scst-scan/upgrading.hbs.md

Revert Scan 1.0 Deprecate

---

scst-scan/creating-scan-policy-template.hbs.md

Scan policy docs

---

tap-gui/http-proxy.hbs.md

Adds explanation of NO_PROXY defaults

---

supply-chain/reference/api/component.hbs.md
supply-chain/reference/api/supplychain.hbs.md

Update documentation for Supply Chain API

Sc api update 1 9

---

release-notes.hbs.md

Add Buildpack release notes

---

bitnami-services/reference/version-matrix.hbs.md

Update bitnami version matrix

---

bitnami-services/about.hbs.md

All versions where this package exists.  1.10/1.9/1.8/1.7/1.6/1.5

Add Bitnami upgrade warning

---

release-notes.hbs.md

Add Bitnami 1.10 breaking change

---

release-notes.hbs.md

Tap gui.1.7.6 release notes

---

release-notes.hbs.md

Fix scst known issues for 1.9
