troubleshooting.md
Hi @jncd, I have added the Service Account Error to the troubleshooting doc. I did not add the third error about the timeout. I think it might be worth waiting for some more evidence from the users before we add that.
=> Add Service Account Error to the doc

install.md, overview.md, uninstall.md
Draft: Added secretgen-controller pre reqs and TAP to Tanzu Application Platform.
[WIP]
=> Added secretgen-controller pre req and TAP abbreviation

install.md
Also included Store links above.
=> Instructions to install Supply Chain Security Tools - Scan

install.md
Samples are now included in the package so no extra step needed
=> Update Accelerator install instructions

install.md
You can see the sample formatting on my repo: 
https://github.com/fombico/docs-tap/blob/main/install.md#-install-api-portal
=> Add docs for API portal

install.md
Regarding the app title - it is actually called "API portal" (where 'portal' is in lowercase). 
My PM told me to lowercase it in our code and other documentation.
=> Update API portal docs to use imperative language

install.md
Adding these instructions to help users get up and running for the first time.
=> Add first install yaml files to help users get up and running

install-general.md
Updated EULA acceptance steps to reflect the latest changes for TAP Beta2 EULA user experience.
=> Updated EULA acceptance steps in install-general.md 

install.md
https://vmware.slack.com/archives/C01G0P79LSE/p1632937200087400
=> convention service is required for alv

install-general.md
some portion of instructions was inside the code quotes so adjusted properly
=> formatting updates

scst-scan/explanation.md, scst-scan/overview.md, scst-scan/release-notes.md, scst-scan/running-scans.md
=> Redecoration on text style

install.md
the example output only had a few packages so I've updated to reflect the full set of packages that a user can expect to see in the list for beta2
=> add all packages returned by `package list` command

install.md
version of cnr is 1.0.2 now so updated it.
also fixed some inline links
=> update cnr version , fix links

scst-scan/running-scans.md, toc.md
Made CRD names consistent through the file.
Added example for the public image scan.
Added viewing vulnerabilities in the TOC.
=> Added public image scan sample

install.md
=> Removed codeblock formating for pre-reqs

install.md
Small PR to spell out what SCP mean (Services Control Plane).
=> Clarify SCP naming

install-general.md
NOTE: There is a long term good recommendation we left behind around updating the CLI. Not sure if that's the appropriate way to handle this.
=> Update docs around updating Tanzu CLI

install.md
Separated out commands from output
=> Fix code blocks for easy copy/pasting

install-general.md
=> Updated flux crd install section

install.md
Updated commands to install and verify convention service, source controller, and service bindings
=> Ease copy pasting of install commands

install-general.md
Update TAP Beta2 products which EULA needs to signed separately to reflect the improved UX
=> Update EULA product lists

install.md
=> Updated convention service section -brief intro

install.md
`--poll-duration` doesn't appear to be a CLI option.
=> Updating TBS install to use poll-timeout

scst-scan/samples/README.md, toc.md
=> Fixing navigation

install.md
to explain more about the two separate components which make up the service
=> adding convention service explanation

scst-scan/explanation.md, scst-scan/overview.md
=> Updated links to prevent them from outdating

scc/default-supply-chains.md
This commit should be reverted when the params are consistent
=> Fix service account for source-to-url SupplyChain

vscode-extension/usage.md
Authored-by: Anthony Pensiero <apensiero@vmware.com>
=> Add required configuration settings

install.md
carto has to be installed prior to a supply chain so I'm moving those install inscructions above.
=> move cartographer above default-supply-chain

install-general.md
Per discussion with Valentina in Slack.
=> Add GKE as supported

install.md
Fixing some formatting/consistency issues.
=> Update install.md with minor revisions

install-general.md
Move kubectl prereq towards the top as following instructions require kubectl
=> Move kubectl prereq towards the top

install-general.md
Resolves https://jira.eng.vmware.com/browse/TANZUSC-327 for TBS
=> Add TBS blurb in pre-req

install.md
Addresses https://vmware.slack.com/archives/C02D60T1ZDJ/p1633360041410200
=> Add more context to verify TBS install

install-general.md
=> chg `tanzu-cli-0.5.0-dev` to `tanzu-cli-0.5.0`

install.md
Sorry @jncd I missed a list...
=> Add newline before numbered list

install.md
- Removing duplicated entry in the TOC for default supply chains
- Remove unnecessary steps in the installation of the default supply chains
=> Removing unnecessary default supply chain steps

install-general.md
Best effort to address TANZUSC-322 and TANZUSC-328.
=> Add additional pre-reqs, fix other pre-reqs

install.md
Addressed https://github.com/pivotal/docs-tap/issues/96
=> Rephrase required CLI plugin wording

install-general.md
=> Update wording for CLI plugin warning

getting-started.md
Various text edits until Debug your Application section.
=> Edits up until Debug your Application

install.md
=> Remove step on API portal to remove image pull secret

getting-started.md
=> Edits until Section 3

getting-started.md
Various edits up until the Install Source & Test to URL section.
=> Edits up to Install Source & Test to URL

getting-started.md
=> Edits from Use Cases on

install.md
Resolves https://jira.eng.vmware.com/browse/TANZUSC-438.  Will add in out put later.
=> Use tanzu CLI to verify TBS install

getting-started.md
Add space before new-line backslash
=> Update getting started

install.md
Signed-off-by: Kavitha Krishnan <krishnanka@vmware.com>
=> Update the docs to have delete command for webhook

install.md
Added TAP GUI prereqs and install info
=> Initial TAP GUI Commit

install.md
Changed Tanzu Application Platform UI to Tanzu Application Platform GUI
=> Updated Tanzu Application Platform GUI Naming

scst-store/cli.md, scst-store/configure_cli.md, scst-store/enable_encrypted_connection.md, scst-store/querying_the_metadata_store.md, scst-store/using_metadata_store.md, toc.md
Also fix a couple bulleted lists
=> Change title to be more clear

install.md
removed references to internal teams in public documentation
=> Removing references in internal teams

install.md
@jncd can you please merge it when you have a chance? Thank you!
=> Updating TAP repo to build.5

install.md
Reflecting all of the supply chains installed.
=> Updating install docs

install-general.md
based on all the feedback from bug bash, this is an attempt to resolve the many issues associated with installing the Tanzu CLI.
- that the links pointing to TKG install and TCE install at the bottom of the file will resolve properly when on docs.vmware.com - can you update if needed?
=> complete overhaul of Tanzu CLI install section

install-components.md
updated instructions for convention service, source controller, and spring boot convention.
=> fix inline links and update install instructions

getting-started.md, scc/default-supply-chains.md, scst-scan/overview.md, troubleshooting.md
Found some broken links. I'm not sure if there are more.
=> Fix broken links

install-components.md
- Remove config for developer conventions - we don't have any optional
config
- Make more similar to other conventions docs with a "verify install"
step
=> Improve docs

getting-started.md, install.md
We've added some additional documentation to the TAP profile install in order to make it easier when using profiles. We've also now updated the Getting started to account for the inclusion of the Catalog file in the accelerator bundle.
=> TAP GUI Addition to Profile Install

install-general.md
also removed link at very bottom of page which shouldn't have been there
=> fix bullet formatting on CLI installation

getting-started.md
was missing the value for --type --- it's been added now==> "--type web \"
=> fix --type flag in workload create

components.md
Note that currently this link is not active but it will be once it has been bumped from staging.
=> Update link to new Services Toolkit docs url

getting-started.md
To clarify you do not need a profile.
=> Update instructions on services usecase 2

install-components.md
=> Promote services-toolkit 0.4.0-rc.2 to 0.4.0

install-general.md
Addresses https://jira.eng.vmware.com/browse/TANZUSC-569
=> Clarify rate limiting warning pre-req

troubleshooting.md
- Add section for when there are no build logs or no builds
=> Add details for troubleshooting tbs

install-components.md
* removed copy and paste crust
* grouped optional steps under a single step
=> Refactor CNR installation steps

release-notes.md
Added new component spring boot convention
Added known issues for Tanzu Apps CLI plugin
=> Updated release notes for beta3 with dev-framework team changes 

install.md
@jncd , I updated the install profile docs to just two profiles: Full & Dev Light.
cc @mpriamo
=> Update profiles to only Full & Dev Light

install-components.md
File names were mismatched from previous step.
=> Update default supply chain values file

install-general.md
0.3.0 release has 0.10.0 within it :)
=> Update cli version to look for 0.10.0

getting-started.md, install-components.md, install.md, learning-center/local-install-guides/deploying-to-kind.md, learning-center/local-install-guides/deploying-to-minikube.md
I have not tested this fully yet, I just removed all the build numbers.
I'm going to try to test now to ensure that none of those build versions are required for any of the components to work.
=> Updating all build versions

install-components.md, learning-center/local-install-guides/deploying-to-kind.md, learning-center/local-install-guides/deploying-to-minikube.md
Updated install instructions. 
Fixed indenting to make sure instructions are under correct section
=> Learning Center Updates

install.md
- I thought this would be a good way to represent how to fill
out this value but a user was confused by it so I am removing the example.
=> Remove confusing example for password value

install-components.md, install.md
Move the recommendation to use the default namespace up, before the actual procedure.
=> Move default namespace up

install-components.md
Signed-off-by: Behrouz Soroushian <bsoroushian@vmware.com>
=> Changes to parameters and also requirements of scan component

getting-started.md
Hi there,
This PR contains numerous updates to Section 5 - Services Journey of the TAP Getting Started guide.
I'd like to request that this PR be merged onto the current Beta 3 live docs site, as well as into `main` ahead of TAP Beta 4 (will I need to open a separate PR for that?).
Thanks!
Ed
=> Updates to Services Journey

install-general.md
Removed duplicate bullet point recommending the use of a paid registry to avoid rate-limiting.
=> Removed duplicate bullet point

install-components.md
https://github.com/vmware-tanzu-private/vscode-tanzu-tools/pull/99
Authored-by: Harsha Nandiwada <hnandiwada@vmware.com>
=> Tools now support non-default namespace

getting-started.md
I'm pretty sure we mean 'Using accelerator.yaml'
=> application.yaml -> accelerator.yaml

install.md
Signed-off-by: Debbie Chen <dechen@pivotal.io>
=> Added Supply Chain Security Tools - Store to TAP 'full' profile

convention-service/troubleshooting.md, service-bindings/troubleshooting.md
Fixed troubleshooting documentation for convention service and service bindings
=> Fix troubleshooting docs

spring-boot-conventions/about.md
Removing comment that shows online for spring boot conventions
=> Remove comment that shows online

scst-store/overview.md
I upload a demo I made to YouTube and I embedded it onto the overview.
=> Add video demoing SCST - Store

install-components.md
=> Draft: Update services-toolkit to latest release candidate

install-components.md, install.md, scst-scan/viewing-reports.md, scst-store/deployment_details.md, scst-store/overview.md, scst-store/use_aws_rds.md, toc.md
- Better introduction to video, alt text
- Better organization of deployment configuration
=> Improve Store docs

install-components.md, install.md
The previous instructions were unclear or incorrect.
=> Improve instructions for using Dockerhub with supply chain

install-components.md
This change should be visible ONLY on docs for beta4 and later
=> beta4+ docs update - rm FluxCD pre-req 4 source-controller

install.md
Updated the `tap-values.yml` with the values for contour.
=> Updated the tap-values.yml for contour ingress

scst-store/overview.md
=> tiny tweak on demo text

install-general.md
Only apply this to beta4+ docs
=> beta4+ only - switch order of instructions for Tanzu CLI upgrade

install-general.md
Also removed kapp controller and secret gen
=> Added placeholder for Tanzu Pre-reqs

getting-started.md, scst-sign/configuring.md, scst-sign/known_issues.md
- Fix non-enumerated lists (replace dashes for asterisks).
- Add more spacing in enumerated lists for numbers to render correctly.
=> docs: Update formatting

getting-started.md, install-components.md, install.md, release-notes.md, scc/default-supply-chains.md, scst-scan/choreographer.md, scst-scan/create-scan-template.md, scst-scan/explanation.md, scst-scan/overview.md, scst-scan/policies.md, scst-scan/release-notes.md, scst-scan/running-scans.md, scst-scan/samples/blob.md, scst-scan/samples/private-image.md, scst-scan/samples/private-source.md, scst-scan/scan-crs.md, toc.md
Update package name and version
Remove manual store setup as new packages have default configuration
=> Update scan package to 1.0.0

convention-service/self-signed-registry-workaround.md, release-notes.md
Added Convention Service Self Signed Registry Workaround documentation
=> Convention Service Self Signed Registry Workaround

getting-started.md
Fixing this link, please close this if there is already a plan for fixing up these links.
=> Fix broken setup developer namespace link

getting-started.md
Hi there,
These are changes to " Section 5: Consuming Services on Tanzu Application Platform", based on the team's feedback from running through the guide during bug bash.
Please could you take a look and merge / push to the staging site when possible. Thanks!
=> More refactoring to Services Toolkit

install-components.md
Update from version 0.1.2 to 0.2.0
=> Update version source controller

install.md
add a default `ceip_policy_disclosed` and clarification on type expected
=> update tap profiles install doc

install.md
Please merge and push to staging as this bug is tripping a number of people up at the moment. THanks.
=> URGENT: fixed TAP-GUI app_config

install-intro.md
Added tanzu dev tools installation step as step 7 on install intro page
=> Additional installation step added to intro page

getting-started.md
Some suggestions for improving the getting started guide
=> Update accelerator parts of Getting Started

getting-started.md, install-components.md, scst-store/install_cli.md, scst-store/overview.md, scst-store/querying_the_metadata_store.md
Edits for clarity, formatting, better convention
=> Small fixes for Store

install.md
This looks like a typo. This needs to be a proper variable assignment.
=> Fix typo to be proper variable assignment

install-components.md, install.md
Adding `tap-values.yml` examples for the grype package.
Signed-off-by: Conor Nosal <cnosal@pivotal.io>
=> Addressing changes for VSEE-339

scst-store/overview.md
And there isn't necessary going to be a CLI plugin to replace it.
=> Be clear that insight CLI is beta

scst-store/overview.md
Remove reference that we're making a CLI plugin
=> [beta-3] Clarify that insight CLI is in beta

scst-sign/configuring.md
Signed-off-by: Andrés Torres <andrest@vmware.com>
=> Explain how to create image patterns and wildcard rules in our image policy

install-general.md
=> update to tanzu cluster essentials 1.0.0

scst-scan/explanation.md, scst-scan/overview.md
VSEE-349: More Docs Edits
- Update Grype release version
- Update CRD names
=> Doc updates for VSEE-349

install.md
=> use tanzu-package-repo-global ns for adding tap repo

install-components.md
Waiting until package is merged into `tap-packages`
=> Promote instructions for services-toolkit to 0.5.0

getting-started.md, install-components.md, release-notes.md, scst-sign/configuring.md, scst-sign/known_issues.md, scst-sign/release-notes.md, troubleshooting.md
This change has been approved for GA:
- https://jira.eng.vmware.com/browse/TANZUSC-650
- https://jira.eng.vmware.com/browse/TANZUSC-652
=> Upgrade SCST sign API version to v1beta1

getting-started.md
Please ensure this gets into Beta 4 (if applicable)
=> Fixed title formatting

getting-started.md, vscode-extension/install.md
This is for Beta 4/GA
Authored-by: Harsha Nandiwada <hnandiwada@vmware.com>
=> Minimum Tilt version is 0.23.2

getting-started.md, scst-scan/release-notes.md
Updated workload section to include scanning specific info. Added known issue to release notes for network issue.
=> Scanning Known Issue and Scanning Supply Chain Workload Update

install-general.md, install.md, tap-gui/database.md, tap-gui/integrations.md, toc.md
=> Modified TAP-GUI to Ingress by default added database and integrations

getting-started.md
Updated Section 1 - parts related to TAP GUI. Together with Sonja Ely.
=> Section 1 related to TAP GUI

getting-started.md, install-components.md, install.md
This should be included in beta 5 docs
=> Install changes for tbs 1.4

scst-store/cli_installation.md, scst-store/release_notes.md
Also add comment about CLI compatibility.
This should not be merged with any other branch.
=> Release notes for Store 1.0.1

scst-scan/overview.md
=> Update provided grype version to v0.27.2

scst-scan/results.md
=> Reword scan results for VSEE-341

install.md
=> Added exclude note to address TANZUSC-641

scst-scan/release-notes.md
Just latest (ie 0.5.0 and 1.0.0)
=> Clarified known issues.

getting-started.md
=> Made changes to title sections and sizing

getting-started.md
=> Updates to the Supply Chain section 4

release-notes.md
Please promote to beta 5 and 1.0 docs
=> Added 1.0 known issues

install.md
Please promote to Beta 5 and 1.0 docs
=> Updated profile name, formatting of table

install-general.md
Please promote to Beta 5 and 1.0 docs
=> Updated formatting, profile name, headings

overview.md
Please promote to Beta 5 docs and 1.0 docs.
=> Updated profile name

getting-started.md
=> Changes to Application Accelerator

developer-conventions/about.md, vscode-extension/usage.md
=> beta4 dev conventions docs

getting-started.md
=> Changes to section III content

release-notes.md
=> Added security release note for TANZUSC-532

getting-started.md
=> Changes to section 1 

getting-started.md
=> Changes to section 2

install.md
Need to prioritize getting this in please
=> added git_ops to values file defaults

getting-started.md
=> Changes to section 4; vulns query section add w/edits

install.md
=> Typo in ssh_secret line for git_ops section values

getting-started.md
=> Edits to prerequisites and section 1

getting-started.md
=> Added Beta 5 workaround for RRV plugin

getting-started.md
=> Add Tilt note about production cluster

getting-started.md
=> Added new images to section 3 w/brand colors

release-notes.md
Please promote to beta 5 and 1.0
=> Updated features section

getting-started.md
=> Changes to the "Deploy your application" section

getting-started.md
=> Changes to "TAP GUI" section

getting-started.md
=> Changes to "Live update your application" section

getting-started.md
=> Changes to "Debug your application" section

getting-started.md
=> Changes to "Monitor your running application" section

getting-started.md, release-notes.md, scst-sign/release-notes.md
Fixed a minor issue and added release notes for the following GA approved changes:
- https://jira.eng.vmware.com/browse/TANZUSC-695
- https://jira.eng.vmware.com/browse/TANZUSC-742
=> Add SCST Sign beta4 release notes

getting-started.md
=> "Supply Chain" changes w/images

install-components.md
Create documentation for shared `contour` package, which has a few options users may want to set.
Update documentation for `cert-manager`, which is now available as a package.
=> Add documentation for `contour`.

uninstall.md
=> add missing rm from CLI uninstall dirs

tap-gui/plugins/runtime-resource-visibility.md
=> Update Runtime resources docs

tap-gui/plugins/runtime-resource-visibility.md
=> Add a link to access TAP Initilizer

release-notes.md
Please promote to beta 5 and 1.0 docs
=> Added known issue for SSC

convention-service/about.md, convention-service/creating-conventions.md, convention-service/reference/bom.md, convention-service/reference/convention-resources.md, convention-service/reference/image-config.md, convention-service/reference/pod-convention-context.md, convention-service/troubleshooting.md
Beta5 & GA
This contains important reference on new feature included for those releases, delayed due to some technical discussions.
=> Added docs for SBOM feature convention controller

tap-gui/plugins/runtime-resource-visibility.md
=> Improve 'Before you begin' section in Runtime Resource Visibility

getting-started.md
=> Removed Beta 5 Workaround for GA

install.md
=> typo, will prevent successful supply chain deployment

release-notes.md
=> Add known issue for app accelerator

release-notes.md
=> Add Known Issue with App Live View in Release Notes

scst-scan/release-notes.md
Add release notes for known CVEs which are false positives with details.
=> Add release notes for known CVEs for SCST Scan

overview.md
=> removed warning

install.md
=> Added example of REGISTRY-CREDENTIALS-SECRET Grype

learning-center/getting-started/training-portal.md, learning-center/getting-started/workshops.md, learning-center/runtime-environment/custom-resources.md, learning-center/runtime-environment/system-profile.md, learning-center/runtime-environment/workshop-environment.md
=> Learning Center Updates for GA

install-components.md
=> Update sct sign tap beta version reference

install-components.md
=> Simplifying the command with conventional values

install-general.md
=> added Pre-req DNS section

install-general.md
=> simplify update CLI/plugins from previous TAP install

install-general.md
=> add cd $HOME/tanzu to clean plugin installation

install-general.md
=> fix broken on-page link to cli/plugins

install.md, tap-gui/accessing-tap-gui.md
=> Fix indentation TAP-GUI target

install-components.md
=> Reversed changes in #757 and added clarification

scst-scan/observing.md
=> Add missing pull secret to scan troubleshooting

scst-sign/known_issues.md
Expand the examples and mention that the race condition known issue may happen in the profiles installation of TAP.
=> Add more information about failure in profiles

release-notes.md
=> Add release note on SBOM issue

install-general.md, install.md
=> typo in TAPGUI Blank catalog filename

getting-started.md, release-notes.md
Hi there,
This PR adds known limitations for services toolkit.
Thanks,
Ed
=> Add known limitations for services toolkit

overview.md
Modified intro text, alphabetized list of components. Please promote to 1.0
=> Overview page enhancements

release-notes.md
added bullets and put components in alphabetical order
=> alphabetized known issues

install-general.md, install.md
=> clarify k8s version and add dev namespace to install.md step.

install.md
=> fixed spacing on indents for sample values files

release-notes.md
=> add known issue for vscode tanzu dev tools

getting-started.md
=> Services usecase table update

learning-center/local-install-guides/deploying-to-kind.md, learning-center/local-install-guides/deploying-to-minikube.md
=> Update TAP package refs to 1.0.0 and LC package refs to 0.1.0

install-components.md, release-notes.md
=> Sign component - kube dns issue + version change

getting-started.md, install-components.md, troubleshooting.md
> Which other branches should this be merged with (if any)?
Not sure which branch but sticking with the default `main`. ~@jwntrs any insight for which branch?~
```
Supply Chain Choreographer -> 0.1.0
Catalog -> 0.5.1
TAP -> 1.0.0
```
=> Tap catalog/54 - Update OOTB version numbers to 0.5.1

getting-started.md
which really changed the meaning.
=> 2nd sentence had mixed up words

tap-gui/accessing-tap-gui.md
Applies to 1-0 branch (not just 1.0.1)
=> Update TAP-GUI command typo in branch 1-0

getting-started.md, install-components.md, troubleshooting.md
This should be updated in 1-0 docs and main branches.
=> Update App Accelerator version to 1.0.0

scc/ootb-supply-chain-testing.md
All other bullets in this list end in periods
=> Consistent Punctuation

getting-started.md
- Ensures consistency among the supply chains when describing the same steps.
- Ensures the title to supply chain descriptions consistently use the word supply chain (or in this case, not)
- Resolves Indent Issue
=> Minor Editorial Updates for Getting Started Page

release-notes.md
Only in main (this change is only for 1.0.1, NOT 1.0.0)
=> Issue resolved, removing known issue.

install-general.md
Needs to be on the 1.0 branch.
=> Removed TCE/TKG reference

components.md
Update TAP 1.0 documentation to include 0.5.0 of services-toolkit, as this is the version being shipped.
also needed in main.
=> Update the services toolkit documentation link

learning-center/about.md, learning-center/troubleshooting/known-issues.md
No
Looks like our known issues page did not get in. Might have been the previous merge issue.
Would like to get this into current docs but ok if it gets into 1.0.1.
=> Adding back learning center known-issues.md page

getting-started.md
=> Section 3 in Add your app section modified

install-components.md, install-general.md
=> TAP GUI catalog naming and link on TanzuNet

release-notes.md
- Note looks like none of the known issues from 1.0.0 were automatically
carried over to 1.0.1, so I just added what I know won't be fixed.
=> Update known issues for 1.0.1

install-components.md, install-general.md
=> Link to PostgreSQL config doc

install-general.md
=> Clarify registry storage pre-requisite

tap-gui/accessing-tap-gui.md
Branch for 1.0.0 and 1.0.1 please.
=> Accessing TAP-GUI Typos in code block

release-notes.md
Which other branches should this be merged with (if any): none
=> Update known issues for scst - scan

troubleshooting.md
[PDY-726](https://jira.eng.vmware.com/browse/PDY-726)
Branch for TAP 1.0. I believe the branch is `1-0`
=> Add troubleshooting section for tap-telemetry secret bug

getting-started.md
=> Added link to TAP GUI in Section 1

components.md
=> Added TAP-GUI to Components page

tap-gui/about.md
=> Added App Accelerator to the list of plugins

getting-started.md
=> Removed a note that is outdated

scst-scan/results.md
This is a fix to docs-stage1.1 (main)
Please cherry-pick to 1.0
=> scst-scan fix broken link to policies.md page

scst-store/sca_scans/CVE.md, scst-store/sca_scans/metadata-store-image-1.0.2-cyclonedx.xml
These are the vulnerability scan results for Store 1.0.2. Please merge into `main` and `1-0`.
=> Add vulnerability info for Store 1.0.2

install-components.md
=> Alv 1.0.2 version update

learning-center/runtime-environment/workshop-definition.md
=> [EDU-172] Add documentation for namespace custom security policy on Learning Center

install-components.md
Fix documentation for installing grype-scanner.
=> Fix grype scanner install to specify grype-values.yml

release-notes.md
This is only for the `1-0` branch
=> Adding v1.0.1 release notes for app accelerator

tap-gui/auth.md, tap-gui/upgrades.md, toc.md
=> Added tap-gui upgrade steps and typo on auth

scst-store/sca_scans/CVE.md, scst-store/security.md
=> Updated to link to our security results

install-components.md
https://vmware.slack.com/archives/C02P2UZHJ4F/p1643973902185209?thread_ts=1643972876.450159&cid=C02P2UZHJ4F follow-up from this comment to clarify targetImagePullSecret argument look more like a placeholder and provide context on it.
Please cherry-pick this to 1-0 branch!
=> Make targetImagePullSecret argument look like a placeholder and provide context

install-components.md
Other branches to include in: 1.0
- Assume tap has been installed air-gapped already
This is a second attempt at this initial PR: https://github.com/pivotal/docs-tap/pull/827
=> Add offline install for TBS component

install-components.md, scst-store/additional.md, troubleshooting.md
Please merge this into both `main` and `1-0`.
=> Reference the correct version of Store that will go into TAP 1.0.1

scst-sign/logs.md
=> Add logs/reasons for scst-sign component

getting-started.md
=> Add Note to Install OOTB Testing+Scanning Section

install-general.md
=> Tanzu cli version changes for tap-1.0.1

release-notes.md
=> Added fixes for tanzu developer tools

prerequisites.md
=> TKG support

prerequisites.md
=> Revert "Update prerequisites.md"

cli-plugins/apps/command-reference/tanzu_apps_workload_apply.md, cli-plugins/apps/command-reference/tanzu_apps_workload_create.md, cli-plugins/apps/command-reference/tanzu_apps_workload_update.md, release-notes.md
=> Add release notes for Tanzu CLI

release-notes.md
Carried 1.0.0 through to 1.0.1 as apps did not change.
1.0.0 and 1.0.1.
=> Updated Scan and Grype known issues.

prerequisites.md
=> Added GKE Regional Recomendation to Prereqs

scst-store/upgrading.md
This and the creation of this file should be in both Tap 1.0 and 1.1
=> Clarify scst store upgrade troubleshooting

release-notes.md
Got it ready for the bug bash.
=> Cleaned up 1.1.0 release notes

getting-started.md, release-notes.md
Hi there,
These changes provide updates related to Services Toolkit documentation. Specifically:
* Add list of resolved issues (relevant to TAP version 1.0.2)
* Add a few notes regarding setup of `ClusterResource` with implications for the `tanzu service instance list` command
* Update the sample apps used
These updates are relevant to TAP version 1.0.2 (NB: They do not apply for TAP 1.0.1)
Thanks!
Ed
=> Update services toolkit 0.5.1

release-notes.md, scst-scan/install-scst-scan.md
=> Update release-notes with resolved issues and update grype version

install.md
TAP_VERSION variable is defined in the beginning of the document. To be used instead of VERSION
=> Consistent version name

troubleshooting.md
=> EULA error troubleshooting entry

troubleshooting.md
=> Added links to component troubleshooting

release-notes.md
Which other branches should this be merged with (if any)? only 1-0
=> Reword known issues

release-notes.md
Which other branches should this be merged with (if any)? only 1-0
=> scst - Remove issues fixed in build 2

troubleshooting.md
I added a troubleshooting scenario that I personally faced and I struggled thru it to solve. These extra details will have other users to find out the failed reconciled packages.
=> Added more troubleshooting details

install-components.md, services-toolkit/install-services-toolkit.md, troubleshooting.md
Hi there, this is a small PR to bump the version of services-toolkit from 0.5.0 to 0.5.1.
These changes should be pulled into `main` as well as the `1-0` branch.
Thanks!
Ed
=> Update versions of stk to 0.5.1

scst-sign/install-scst-sign.md
Add limit and requests for cpu and memory configurations for SCST Sign
=> [SCST Sign] Add limit and requests for cpu and memory configurations

getting-started.md, scc/ootb-supply-chain-testing.md
=> docs: update Tekton test pipelines to avoid test supply chains failing

migrate-profile.md, toc.md
Which other branches should this be merged with (if any)? 
1.1 and Higher
=> Added Profile migration steps 

spring-boot-conventions/reference/CONVENTIONS.md
=> Updated documentation for spring boot conventions

release-notes.md
=> Update grype known issues

release-notes.md
=> Move resolved issue that resurfaced into known issues

release-notes.md
=> Added profile info

overview.md
=> Table changes up until Developer Conventions

migrate-profile.md
=> One last edit to Migrate (add link)

getting-started.md
=> Added note on TAP GUI database and app_config

install.md
=> Updated profiles

tap-gui/plugins/runtime-resource-visibility.md
=> Updated RRV Plugin docs

install-tanzu-cli.md
=> updating plugin install instructions

install.md, release-notes.md, tap-gui/plugins/install-application-live-view.md
These changes are targeted only for the 1.1 release
=> update app live view sections for 1.1

getting-started.md
=> Clarify non-working use cases

overview.md
=> Added TLC to Overview Summaries

overview.md
=> Updated Table to include Default Roles

install.md
=> fixed typo

cli-plugins/apps/command-reference/tanzu_apps_workload_apply.md, cli-plugins/apps/command-reference/tanzu_apps_workload_create.md, cli-plugins/apps/command-reference/tanzu_apps_workload_delete.md, cli-plugins/apps/command-reference/tanzu_apps_workload_list.md, cli-plugins/apps/command-reference/tanzu_apps_workload_update.md
=> Update apps plugin 0.5.0 docs

release-notes.md
=> Added two bullets under TAP GUI

tap-gui/plugins/scc-tap-gui.md
This will need to be included in TAP 1.1. 
Images will be updated further on Monday. As well as additional links to relevant documentation
=> Add new content for SCC Plugin

getting-started.md
Update the services-toolkit getting started guide to reflect the separation of resource claims from workload creation.
N/A
=> Separate claims from workload creation in STK usecases

tap-gui/plugins/install-application-live-view.md
=> Update version of app live view to 1.0.2

scst-sign/install-scst-sign.md
=> Update sign to 1.0.2

getting-started.md, install-tanzu-cli.md, install.md, upgrading.md
=> Kdhaduk tap 1.0.2

getting-started.md
All these commands need the developer namespace to be specified to make them work.
=> Added required namespace switch

scst-scan/explanation.md
Which other branches should this be merged with (if any)? Please cherry-pick to 1-0 after docs are no longer frozen.
=> Remove line that is no longer needed

scst-scan/install-scst-scan.md
Update docs to specific optional usage of grype-values.yml to configure grype-scanner.
Which other branches should this be merged with (if any)? 1.1, 1.0
=> Update docs to specific optional usage of grype-values.yml to configure grype

install.md, multi-cluster/getting-started.md, multi-cluster/installing-multicluster.md, multi-cluster/reference/tap-values-build-sample.md, multi-cluster/reference/tap-values-run-sample.md, multi-cluster/reference/tap-values-view-sample.md, toc.md
=> Remove Light and Initial Multi-cluster docs

multi-cluster/getting-started.md, multi-cluster/reference/tap-values-run-sample.md
=> Aditional multicluster edits

multi-cluster/getting-started.md
=> Added more Multi-cluster details

install.md
Updating the steps for relocating the Images from Tanunet to different registries.
=> Update install.md include steps for relocating TAP images from Tanzunet to a different container registry

tap-gui/cluster-view-setup.md
=> Update tap-gui multi-cluster view docs

install.md
adding reference to Prerequisites.
=> Update install.md to include reference to pre-reqs for container image registry requirements

getting-started.md
Merge into 1-0 only.
I'll make a separate PR for main branch (if necessary)
=> Fix broken links for Store 1.0

getting-started.md
This should only be for main branch. It only applies to 1.1. The changes for 1.0 are in another PR.
=> Fix broken link in Store 1.1

vscode-extension/install.md
per slack https://vmware.slack.com/archives/C02P2UZHJ4F/p1647849252252619
Applies to 1.0 - 1.1+
=> Changed VSCODE Config to include Mac menu ref

install-tanzu-cli.md
=> Update Cluster Essentials install instructions

release-notes.md
added notes for apps cli plugin, source controller, spring boot conventions, and service bindings
NONE
=> updates from dev-productivity-framework team

release-notes.md, tap-gui/plugins/install-application-live-view.md
=> Update release notes and app live view for 1.1.0

source-controller/install-source-controller.md
=> Updated source controller install

install-components.md, release-notes.md, scst-sign/install-scst-sign.md
=> Update docs for scst-sign 1.1.0

prerequisites.md, upgrading.md
=> Updated k8s version prereqs in install and upgrade

scst-sign/logs.md
- Added more log explanations
- Updated variable name formatting
For v1.1.0+
=> Scst sign log update

install.md, multicluster/reference/tap-values-build-sample.md, tanzu-build-service/install-tbs.md
- This should only be full or lite
This should be in main and 1-1
=> Update descriptor_name valid values

tap-gui/plugins/scc-tap-gui.md
=> updated plugin to plug-in

tap-gui/about.md
=> Added Supply Chain Choreographer plug-in

tap-gui/plugins/scc-tap-gui.md
updated screen shots and text
TAP 1.1 release please
=> second attempt at pr

application-accelerator/install-app-acc.md
=> Add ingress.enable_tls property for accelerator

release-notes.md, scst-scan/install-scst-scan.md
Added release notes, new features, breaking changes and configuration changes for SCST - Scan
This addresses: 
- VSEE-485 & VSEE-452
This should be merged in just for TAP 1.1.0
Thanks
=> Changes to Supply Chain Security Tools - Scan

release-notes.md
Added known issue with ConfigMap error as well as details about the Supply Chain Choreographer plug-in
must be included with tap 1.1 please
=> Included known issues and new release SCC plug-in

release-notes.md
=> Add release notes for app accelerator

scst-store/add-data.md, scst-store/additional.md, scst-store/cli-docs/insight.md, scst-store/install-scst-store.md, scst-store/overview.md, scst-store/query-data.md
Reworked query-data page, fixed "insight create" to "insight add", removed need for "Additional Resources" page, clarified "source commit" throughout
=> Reworked query.md and add.md based on feedback

release-notes.md
=> SCST - Scan | Adding mitigated CVEs and fixing typo

multicluster/installing-multicluster.md, multicluster/reference/tap-values-view-sample.md
1.1+, addresses https://jira.eng.vmware.com/browse/TANZUSC-1074
=> Updated multicluster docs with RBAC

learning-center/workshop-content/building-an-image.md
=> New learning center base environment image tag

authn-authz/overview.md, authn-authz/sca-scanning-results.md, authn-authz/sca-scans/tap-auth-v101-beta1-grype-results.md, scst-sign/logs.md
=> Document security scan results for tap-auth

release-notes.md
DOCS TEAM - I added some links to the release notes --- can you please doublecheck and make appropriate fixes so they will work as expected when rendered in the docs site?
=> add source controller and apps plugin changes

release-notes.md, tap-gui/plugins/install-application-live-view.md
=> Add 1.1.0 ALV doc

install-components.md, install.md, multicluster/reference/tap-values-build-sample.md, tanzu-build-service/install-tbs.md, tanzu-build-service/tbs-about.md, troubleshooting-tap/troubleshoot-install-tap.md
- Also add context for what descriptors are
This should only be merged into 1.1
=> Update user config for descriptor_name for TBS

tap-gui/plugins/scc-tap-gui.md
updated screenshot and sections
merge with main
=> Removed screen shot for cve list

release-notes.md
Added known issue of CVE details not appearing on image or build scan
merge to main
=> Added known issue for SCC plugin

authn-authz/binding.md
=> docs: [TAA-39] change command verbs for tap-auth

release-notes.md
=> Update release notes to exclude json logging

getting-started.md
Hi,
This PR contains a few small updates to URLs in Section 5: Consuming Services on Tanzu Application Platform.
Which other branches should this be merged with (if any)? None - these changes are for TAP 1.1.
=> STK: A few small URL updates

learning-center/local-install-guides/deploying-to-minikube.md
Resolves [Issue #1050](https://github.com/pivotal/docs-tap/issues/1050)
=> Secret creation is omitted in minikube instructions

scst-store/overview.md
=> Link to ingress configuration from Store overview

spring-boot-conventions/reference/CONVENTIONS.md
this should be applied to TAP v1.1+ docs
=> additional copy for management port update

release-notes.md
=> Added known issue for missing store secretimport.

multicluster/about.md
=> Added 'Iterate'

getting-started.md
=> Updated Scan + Store Getting Started

release-notes.md
=> Recommit scan CVE fixes.

cli-plugins/apps/create-workload.md
=> Added setup dev namespace to cli plugin

overview.md
=> Added info to profiles section.

release-notes.md
=> Added info under 'Installing'

cli-plugins/apps/create-workload.md, scst-scan/install-scst-scan.md
=> Adding error logs and troubleshooting command for the rbac cli

scst-scan/samples/public-source-compliance.md
Removing the 'delete resource' section
* TAP 1.1
=> SCST - Scan Improvements for TAP 1.1

upgrading.md
=> Removed specific versions from upgrades

release-notes.md
=> Added Kubernetes version support to release notes

release-notes.md
=> Updated Release Notes for Cluster-Essentials Issues

release-notes.md
[PSTAR-592](https://jira.eng.vmware.com/browse/PSTAR-592) for context
Which other branches should this be merged with (if any)? I'll open a separate PR to disclose this CVE in past versions
=> declare CVE fix in TAP GUI

release-notes.md
[PSTAR-592](https://jira.eng.vmware.com/browse/PSTAR-592)
=> disclose CVE in past versions of TAP GUI

release-notes.md
[PSTAR-593](https://jira.eng.vmware.com/browse/PSTAR-593), [TINT-90](https://jira.eng.vmware.com/browse/TINT-90)
=> disclose supply chain multicluster bug

release-notes.md
=> combine supply-chain + tap-gui known issues

getting-started.md, scst-sign/configuring.md
Signed-off-by: Denny Hoang <dhoang@vmware.com>
=> Note namespace exclusion for scst-sign

tap-gui/upgrades.md
This is applicable to any supported version. Thank you.
=> command change from "tap" to "tap-gui"

tap-gui/cluster-view-setup.md
Update to add scanpolicies resources.
Original MR: https://gitlab.eng.vmware.com/project-star/pstar-backstage-poc/-/merge_requests/386
=> Update to add scanpolicies resources

install-tanzu-cli.md
and improve readability of overall page with links to sections and some explanations.
=> consolidate cli/plugin install and simplify copy

tap-gui/plugins/install-application-live-view.md
=> Update to App Live View 1.1.1

overview.md
=> Update App Live View TAP profiles

release-notes.md
Which other branches should this be merged with (if any)? only 1-1
=> Update release notes for scan-controller and grype-scanner 1.1.1-build.1

release-notes.md
This is required for the 1.1.1 release. Please let me know if I've done anything incorrectly.
please merge with 1.1.1 branch
=> Added fixed issues under SCC plug-in

overview.md
Hello,
There were missing marks for the view profile. So:
-  I added tick mark for Source Controller for view profile
-  I added tick mark for Flux Source Controller for view profile
=> List of packages for view profile modified

multicluster/installing-multicluster.md, scst-scan/install-scst-scan.md, scst-scan/observing.md
Updated troubleshooting section with information on disabling metadata store during installation and added link to scst-sign multicluster support in the multicluster section.
Which other branches should this be merged with (if any)? 1-1 and main
=> Updated scst-scan instructions for disabling metadata store

release-notes.md
Which other branches should this be merged with (if any)? only 1-1
=> Added known issues for scan v1.1.1

scst-scan/overview.md
Which other branches should this be merged with (if any)? 1-1 and main
=> Added 'Note on Vulnerability Scanner'

scst-scan/overview.md
Which other branches should this be merged with (if any)? 1-1 and cherry-pick to main please
=> scst-scan v1.1.1 Updated wording in Vulnerability Scanner sections

scst-scan/observing.md
Which other branches should this be merged with (if any)? 1-1 and main
=> scst-scan - formatted yaml and console commands to not be in a single block

tap-gui/database.md, tap-gui/integrations.md, tap-gui/support-menu.md, tap-gui/troubleshooting.md
[PSTAR-609](https://jira.eng.vmware.com/browse/PSTAR-609) for some (scant) context.
@RichardJJG in our Slack discussion I mentioned some confusion around comments in these snippets, but less address that separately (if ever) -- correct indentation is much more urgent.
Which other branches should this be merged with (if any)? This will be relevant for 1.2 as well!
=> fix TAP GUI values-file snippets

install-tanzu-cli.md
And added inline link to Windows install instructions for convenience and discoverability
=> improve setting path on Windows (step 9)

app-live-view/app-config.md
=> Fix links in App Live View page

scst-store/ingress-multicluster.md
... by providing info on the SecretImport counterpart installed with the scan package
=> Clarify how adding SecretExport works

scst-scan/observing.md
Which other branches should this be merged with (if any)? merge with "main" and cherry-pick to "1-1"
=> Scst scan update troubleshooting section on incompatible Syft Schema Version

install-tanzu-cli.md
based on going through the process, the instructions were a little bit off.
**Please cherrypick these windows-related updates back to TAP 1.0.0 and above** 
cc @BarrAndrea
=> update windows CLI and plugin install

scst-scan/observing.md
Which other branches should this be merged with (if any)? please merge with main and cherry-pick to 1-1
Signed-off-by: Behrouz Soroushian <bsoroushian@vmware.com>
=> scst-scan Fixed formatting for error message block

scst-scan/observing.md
Which other branches should this be merged with (if any)? please merge with main and cherry-pick to 1-1
=> scst-scan remove syft-schema-version

cli-plugins/insight/cli-installation.md, install-tanzu-cli.md
=> docs: remove not supporting windows for insight plugin

install-components.md, install.md.hbs
This pull request adds info about AppSSO into the profiles section.
=> Add AppSSO to profile info

tap-gui/tap-gui-naming-customization.md
Which other branches should this be merged with (if any)? 1.2+ version
=> TAP GUI Customization update

workloads/queue.md
=> Fix the `queue` supply chain and usage description

release-notes.md
=> Add App Live View 1.1.2 docs

workloads/Iterate on your function
Would it be possible to make the functions beta section a folder and add this file as a drop down item within it?
=> Create Iterate on your function

scst-scan/install-scst-scan.md
Which other branches should this be merged with (if any)? Please merge with main and cherry-pick to 1-1
=> scst-scan - updated version of grype included in 1.1.2 release

tap-gui/plugins/learning-center.md
=> changed docs to reflect an operators perspective

scst-scan/offline-airgap.md
=> DRAFT: Added airgap support.

tap-gui/tap-gui-rbac/assigning-kubernetes-roles.md, tap-gui/tap-gui-rbac/setup-tap-gui-rbac-eks.md, tap-gui/tap-gui-rbac/setup-tap-gui-rbac-gke.md, tap-gui/tap-gui-rbac/setup-tap-gui-rbac.md, tap-gui/tap-gui-rbac/view-resouces-rbac.md
1.2 feature documentation. EKS and GKE RBAC enablement and related topics, all in one folder
=> [#180914617] RBAC for K8s API Calls docs

release-notes.md
Please merge with 1.2 main and review for formatting errors
=> Added Supply Chain Plug-in details

scst-scan/create-scan-template.md
Signed-off-by: Behrouz Soroushian <bsoroushian@vmware.com>
Needed for 1.2.0
=> DRAFT: [Scan] how to write scantemplate for pluggable scan component

tap-gui/customize/customize-branding.md
=> Customizing TAP GUI branding add-on

tap-gui/tap-gui-rbac/setup-tap-gui-rbac-eks.md, tap-gui/tap-gui-rbac/setup-tap-gui-rbac-gke.md, tap-gui/tap-gui-rbac/setup-tap-gui-rbac.md, tap-gui/tap-gui-rbac/view-resouces-rbac.md
=> Edits to TAP GUI RBAC docs

tap-gui/customize/customize-branding.md
=> Additional edits for TAP GUI Customization

getting-started/consume-services-walkthrough.md
STILL DRAFT until someone from STK says so but making it not draft so it can be merged when I'm away on vacation.
- also includes new ClusterInstanceClass API.
Which other branches should this be merged with (if any)? N/A
=> Use the `class` `claimable` subcommands.

application-accelerator/creating-accelerators/composition.md, application-accelerator/creating-accelerators/transforms/conflict-resolution.md, application-accelerator/creating-accelerators/transforms/index.md, application-accelerator/creating-accelerators/transforms/invoke-fragment.md
Fix https://github.com/pivotal/acc-release/issues/275
=> Add documentation for the composition feature

application-accelerator/creating-accelerators/transforms/open-rewrite-recipe.md
=> Update example following OpenRewrite version bump

scst-scan/install-snyk-integration.md
=> Fix code block indentation.

application-accelerator/creating-accelerators/composition.md, application-accelerator/creating-accelerators/transforms/invoke-fragment.md
=> Fix markdown syntax, fix some typos

scst-store/overview.md
=> docs: [META-618] use new demo video for insight plug-in

scc/git-auth.md, scc/gitops-vs-regops.md, scc/install-ootb-sc-basic.md, scc/install-ootb-sc-wtest-scan.md, scc/install-ootb-sc-wtest.md
Document new gitops flow. Specify new tap-values available.
=> Document multi-cluster gitops

install-tanzu-cli.md
=> update CLI core/plugin installation instructions

intellij-extension/using-the-extension.md
=> clarify intellij docs bugbash feedback

release-notes.md
=> Added resolved issues

intellij-extension/using-the-extension.md
=> docs: 1 session at a time

intellij-extension/using-the-extension.md
=> docs: command f9 to build project

scst-scan/create-scan-template.md
Emphasize guidance on writing a new template
Only applies to 1.2+
=> update scantemplate authorship

getting-started/consume-services-walkthrough.md
Which other branches should this be merged with (if any)?: None, TAP 1.2 only.
=> Update STK docs with new aggregating rbac label

learning-center/about.md, learning-center/airgapped-environment.md, learning-center/getting-started/learning-center-operator.md, learning-center/install-learning-center.md, learning-center/troubleshoot-learning-center.md, learning-center/workshop-content/about.md, learning-center/workshop-content/workshop-instructions.md, toc.md
These changes are for docs v1.2
=> 1 2 lc updates

release-notes.md.hbs
=> Remove a line from release notes for TAP GUI 1.1.2

tap-gui/plugins/scc-tap-gui.md
still needs images added. To be done before eod June 2. 
please merge with 1.2 documentation.
=> Added details for 1.2

getting-started.md
=> Create command should be Update

release-notes.md.hbs
=> Add CVE fixed for TAP GUI in TAP 1.1.2

multicluster/reference/tap-values-view-sample.md, prerequisites.md, scst-store/deployment-details.md, scst-store/ingress-multicluster.md
Documentation for changes to TAP - [MR](https://gitlab.eng.vmware.com/tap/tap-packages/-/merge_requests/799)
=> chore: [META-642] Add docs regarding TAP-level setting shared.ingress_domain

learning-center/runtime-environment/workshop-definition.md
Changes should be added to v1.0, v1.1 and v1.2 of docs
=> EDU493- add branch referencing requirement to docs

install-components.md, services-toolkit/install-services-toolkit.md, troubleshooting-tap/troubleshoot-install-tap.md
Small PR to bump the version of services toolkit to 0.7.1.
Which other branches should this be merged with (if any)? N/A - this is for TAP 1.2.
=> Bump stk to 0.7.1

application-accelerator/creating-accelerators/accelerator-crd.md
=> Add Fragment CRD documentation

scc/install-ootb-sc-basic.md
=> Fixed name of ootb supply chain basic maven.repository.secret_name

scc/git-auth.md
Track github docs, which specify using both username and password in token login flow.
=> Git authenticate with username and token

scst-scan/install-snyk-integration.md
=> docs: improve configuring supply chains with Synk integration

vscode-extension/using-the-extension.md
Which other branches should this be merged with (if any)? None.
=> VSCode: Added instructions on how to see the current context and how to set the namespace for the current context

learning-center/install-learning-center.md, learning-center/local-install-guides/deploying-to-kind.md.hbs, learning-center/local-install-guides/deploying-to-minikube.md.hbs
=> LearningCenter- Clarification in docs, Add supported values section

application-accelerator/creating-accelerators/creating-accelerators.md
=> Add intro to fragments to creating acc doc

cartographer-conventions/creating-conventions.md
=> Cartographer Conventions minor fixes

authn-authz/permissions-breakdown.md, source-controller/about.md, source-controller/install-source-controller.md, source-controller/reference.md
=> Updated docs for Source Controller v0.4.1

app-live-view/troubleshooting.md
=> Update App Live View Troubleshooting doc

getting-started/iterate-new-app.md, intellij-extension/installation.md, vscode-extension/installation.md
Older versions had a bug where using live update would trigger a full supply chain build
Tilt issue: https://github.com/tilt-dev/tilt/pull/5694
=> Fix: updated recommended tilt version

getting-started/consume-services.md
=> Add in label that will add workloads to gui.

scst-scan/install-snyk-integration.md
=> Fix indentation and variable naming.

tap-gui/tap-gui-rbac/setup-tap-gui-rbac-with-gke-auth.md
=> Fixed a typo

release-notes.md.hbs, source-controller/about.md
=> Add known issues for convention controller; note for source controller for TAP 1.2.0

release-notes.md.hbs
=> Update Live Hover description

intellij-extension/glossary.md, intellij-extension/using-the-extension.md
=> update source image descriptions

install.md.hbs, scst-store/deployment-details.md, scst-store/ingress-multicluster.md, scst-store/install-scst-store.md
=> Clean up store - ingress multicluster docs

release-notes.md.hbs, scst-scan/observing.md, troubleshooting.md
=> Scst scan 1.1.2 docs update

tap-gui/tap-gui-rbac/setup-tap-gui-rbac-with-gke-auth.md
=> Fixing section naming

tap-gui/tls.md, toc.md
=> add tap gui configure tls section

app-live-view/install.md
=> Change keyword backend to back-end

application-accelerator/creating-accelerators/accelerator-crd.md, application-accelerator/vscode.md, release-notes.md.hbs
* Updating release notes to elaborate further on new features
* Add in hyperlinking for quick referencing of new/updated features
* Add `git.subPath` to `accelerator-crd.md` for both Accelerator and Fragment specs
=> Update v1.2 release notes for app accel

intellij-extension/getting-started.md, intellij-extension/installation.md, intellij-extension/known-issues.md, intellij-extension/using-the-extension.md
=> docs: known issues page

vscode-extension/live-hover.md
=> docs: update description for live hovers

scst-scan/install-snyk-integration.md
Add docs on how to opt out of snyk thru configuring supply chain and uninstall.
N/A
=> [VSEE-625] Add docs on how to opt out of using snyk

scst-scan/install-snyk-integration.md
Add snyk api token generation docs
N/A
=> [VSEE-625] Add snyk api token generation docs

getting-started/consume-services.md, getting-started/set-up-services.md
Which other branches should this be merged with (if any)? TAP 1.2 changes
=> Change services toolkit advanced usecase docs

components.md
Add buildpacks documentation as component (sub-bullet of VMware Tanzu Build Service)
Which other branches should this be merged with (if any)? Not sure.
=> Add VMware Tanzu Buildpacks to Components

app-live-view/configuring-apps/spring-boot-enablement.md, app-live-view/configuring-apps/steeltoe-enablement.md
=> App Live View : update cmd in doc when workload image not built with TBS

scst-scan/install-snyk-integration.md
Add note explaining snyk scanning is in beta
N/A
=> [VSEE-625] Add note explaining snyk scanning is in beta

tap-gui/catalog/catalog-operations.md
[TANZUSC-1414](https://jira.eng.vmware.com/browse/TANZUSC-1414)
Which other branches should this be merged with (if any)? this affects all currently released versions of TAP, so at least 1.0 and 1.1 should get this change as well.
=> mention scoped route requirement for gitlab

tap-gui/cluster-view-setup.md
=> add tap-gui cluster tls verify config docs

release-notes.md.hbs
=> docs: add to rl notes

application-accelerator/vscode.md, cli-plugins/accelerator/overview.md
=> Fixed link to acc-server expose configuration

scst-scan/install-snyk-integration.md
Applied capitalizations and modified text in configure supply chain
N/A
=> [VSEE-625] Applied capitalizations and modified text in configure supply chain

scst-scan/install-snyk-integration.md
* Add prereq to point out snyk api token creation
* Changed from json to yaml for snyk token secret
* Changed verifying imagescan yaml formatting to be declarative
N/A
=> [VSEE-625] Updates to snyk install page

vscode-extension/installation.md
=> fix preference path

scst-scan/offline-airgap.md
Adding instructions to include more ca certs in case is needed by the end-user.
=> [VSEE-631] Adding notes to add extra ca's if needed

release-notes.md.hbs
TAP 1.2 new features for AppSSO
=> Adding AppSSO new features

release-notes.md.hbs
=> Updated SCC known issues

about-package-profiles.md
These updates are for TAP 1.2 docs release only
=> Added Application Single Sign-On component

app-sso/about.md, app-sso/getting-started.md, app-sso/install-appsso.md, toc.md
=> add appsso/install and appsso/getting-started

getting-started/set-up-services.md
Which other branches should this be merged with (if any)? Nope
=> Remove command that is leftover from yaml removal.

getting-started/about-consuming-services.md
Hi there,
This pr contains a few small updates to consuming services section.
Thanks
Ed
Which other branches should this be merged with (if any)? N/A - target for TAP 1.2 only.
=> Few small updates to STK and services

tap-gui/non-standard-certs.md
=> Fix spacing in tap gui custom CA docs

application-accelerator/vscode.md
=> Update VSCode extension installation

install-intro.md
=> Update hyperlink for AWS Quickstart section

release-notes.md.hbs, scst-scan/install-scst-scan.md, scst-scan/policies.md, scst-scan/upgrading.md, toc.md, upgrading.md
Adding instructions to upgrade to a newer version of SCST - Scan
Adding instructions specific to upgrade to 1.2.0
Please verify that the link pointing to Release Notes in scst-scan/upgrading.md is pointing to the right file (lines 27 and 111). Thank you!
=> [VSEE-655] upgrading scst - scan docs

release-notes.md.hbs
This PR is targeted for TAP 1.2.0.
=> Add SCST TAI release notes

release-notes.md.hbs, scst-scan/install-snyk-integration.md, scst-scan/observing.md, scst-scan/policies.md
Which other branches should this be merged with (if any)? For TAP 1.2
=> Added sample scan policy for Snyk Scanner

getting-started/ecr.md
=> Ecr support

install.md.hbs, scst-scan/install-scst-scan.md
Clarifying Metadata Store integration installation and reducing error-prompting configuration with SCST - Scan
=> [VSEE-610] Updating metadata store integration docs

release-notes.md.hbs
Which other branches should this be merged with (if any)? TAP 1.2 only
=> Add Services Toolkit release notes (TAP 1.2 documentation)

scst-scan/install-snyk-integration.md
=> Fix spelling of namespace

release-notes.md, scst-scan/observing.md
Adding a known issue for scst-scan 1.0.3 and troubleshooting instructions to workaround this.
This is meant for 1.0.3
=> VSEE-642 - 1.0 - Adding known issue and troubleshooting instructions

scc/ootb-supply-chain-testing-scanning.md, scc/ootb-supply-chain-testing.md
=> Fix missing slashes.

release-notes.md.hbs, source-controller/reference.md
Which other branches should this be merged with (if any)? Only merge to branch `1-2`. 
**NOTE** - Please note, `main` was updated with a separate PR https://github.com/pivotal/docs-tap/pull/1379
=> TAP 1.2 Clarification with Source Controller MavenArtifact

release-notes.md.hbs
=> added log output to release notes

release-notes.md.hbs
TAP GUI not affected by the source scan issue
=> Removed a known issue

tap-gui/customize/customize-your-portal.md
=> Customizing default route in TAP GUI

cloud-native-runtimes/install-cnrt.md, install-air-gap.md.hbs, multicluster/reference/tap-values-build-sample.md, scst-scan/install-snyk-integration.md, tekton/install-tekton.md
=> Fix broken links and broken source scan with snyk

customize-package-installation.md
=> Fixes an indentation issue in customize-package-installation

scst-scan/install-scst-scan.md, scst-scan/observing.md
Fixing the 1-2 docs for scan
main
=> [VSEE-638] Fix small nits

install-intro.md
=> Add AWS quickstart section

release-notes.md.hbs
additional known issue added with no workaround but will be fixed in 1.2.1. I need @a-peek4  to review for word-smithing.
=> Update to line 322

scst-scan/install-snyk-integration.md
=> Fixing snippet in snyk docs

scst-scan/install-snyk-integration.md
Updated the referenced name for the scan-policy for consistency.
This is intended for 1.2.0
=> Changes to snyk scanner installation. 

prerequisites.md
=> Add note about ALV dns to pre-requisites

tap-gui/cluster-view-setup.md
Could also be merged with 1-2 and 1-1.
=> Fix missing namespace in tanzu package command

tap-gui/cluster-view-setup.hbs.md
=> TANZUSC-1525: allow view cluster to read mavenartifacts

release-notes.hbs.md
=> TBS release notes for 1.2.1 patch

release-notes.hbs.md
added resolved issues in 1.2.1 please merge with main
=> update resolved issues

release-notes.hbs.md
Affects only v1.2.0, link to a workaround.
=> Added a known issues for TAP GUI about Maven

tap-gui/troubleshooting.hbs.md
=> Added Maven artifact troubleshooting

tap-gui/tap-gui-rbac/set-up-tap-gui-rbac-eks.hbs.md
=> Removed internal note about 1.3

scst-store/using-encryption-and-connection.hbs.md
Please merge into main, 1-2-1, and 1-2-2
=> Fix formatting issues

tap-gui/plugins/runtime-resource-visibility.hbs.md
Adds changes for defaulting to first container, as well as stream reconnection
**Targets TAP 1.3 release**
=> Update docs for pod logs (TAP 1.3)

install.hbs.md
=> Updated ingress domain

install.hbs.md
Updated the learning-center domain details to "INGRESS-DOMAIN"
=> Updated the INGRESS-DOMAIN

upgrading.hbs.md
Updated the document with more details with respect to upgrading the TAP .
=> Updated upgrade steps

scst-scan/available-scanners.hbs.md, scst-scan/install-scanners.hbs.md, toc.md
Summary:
* Replace the existing install-snyk doc with a generic installation doc on how to add new scanners.
=> [VSEE-698] Generalize adding new scanners into supply chain/component installation

getting-started/config-supply-chain.hbs.md
- Make explicit that user needs to configure and apply ClusterImagePolicy
- Highlight placeholder for namespace
This should be in the 1.2 and 1.3 branches.
Thanks!!
=> Fixes for configuring supply chain for signing+verification

app-live-view/install.hbs.md
This is targeted toward TAP 1.3.0 docs only.
=> Add 1.3.0 TAP docs for App Live View - 1

application-accelerator/creating-accelerators/spel-samples.hbs.md
Fix https://github.com/pivotal/acc-engine/issues/205
Also fix some syntax errors.
This applies to all versions of TAP where this is easily mergeable
=> Document an example of how to deal with string[]

scst-policy/configuring.hbs.md
Please cherry pick this change to the `1.2` branches
I believe this includes `1-2`, `1-2-1` and `1-2-2`
=> Update policy-controller glob logic info

api-auto-registration/usage.hbs.md
Which other branches should this be merged with (if any)? Tap 1.3
Adds some more details around the supply chain changes and APIDescriptor custom CR.
=> API Auto Registration

scst-scan/install-scst-scan.hbs.md
Summary:
* Add configuration variables for scan-controller/grype to a table to display for users
N/A
=> [VSEE-693] Add configuration variables to a table to display for users

tap-gui/plugins/runtime-resource-visibility.hbs.md
- Include note about frequent reconnections
- Include clicking as a way to pause
**Targets TAP 1.3**
=> More pod logs docs updates

tap-gui/plugins/runtime-resource-visibility.hbs.md
Signed-off-by: Salomon Moreno <msalomon@vmware.com>
=> Updated RRV users doc for 1.3 version

tap-gui/customize/customize-portal.hbs.md
=> Favicon customization in TAP GUI

application-accelerator/configuration.hbs.md, application-accelerator/creating-accelerators/creating-accelerators.hbs.md
- Using local-path when authoring
- Configuring Git-Ops managed accelerators
- Configuring Git credentials secret with custom CA certs
Which other branches should this be merged with (if any)? This is for 1.3 only.
=> Add app accelerator new features content for 1.3

scst-scan/available-scanners.hbs.md
Which other branches should this be merged with (if any)? main (for 1.3.0)
=> Added link for installing Carbon Black

authn-authz/permissions-breakdown.hbs.md, getting-started/add-test-and-security.hbs.md, scc/ootb-supply-chain-testing-scanning.hbs.md, scst-scan/observing.hbs.md, scst-scan/policies.hbs.md
Which other branches should this be merged with (if any)? main
=> scst-scan - Added documentation on CVE triage workflow

install.hbs.md
=> TAP Install with TAP GUI ingress-domain for Bug Bash

scst-scan/install-carbonblack-integration.hbs.md
Because otherwise the YAML does not render correctly.
None, this is intended for the 1.3 release
=> Fix indentation of YAML block

scc/ootb-supply-chain-testing-scanning.hbs.md
Which other branches should this be merged with (if any)? main and TAP v1.2 and all patches 
- This is a typo fix for this [pull request](https://github.com/pivotal/docs-tap/pull/1454) which was merged with main and TAP v1.2 and all patches
=> Fixed typos

scst-scan/install-scanners.hbs.md
Summary:
* Fixing link
N/A. This is only for main
=> [VSEE-698] Fix link

scst-scan/offline-airgap.hbs.md
Which other branches should this be merged with (if any)? merge with main and cherry-pick to 1.2 branches, thanks!
=> VSEE-677 | Document 5 day limit on Grype vulnerability database
