pivotal/docs-tap

install.md

Here are instructions to install the metadata store. I copied the instructions from CNR and customized it.
I'm looking for some feedback. I notice that the `values.yml` for the other pacakges (like CNR) all have a section for registry, something like this:
```yaml
registry:
server: "registry.pivotal.io"
username: "TANZU-NET-USER"
password: "TANZU-NET-PASSWORD"
```
Are these configuration settings supported by default by the Tanzu CLI install feature, or did each package author implement support for these values?
Second, I didn't list out all the possible configuration in our example `values.yaml`, should I? In our project README, we link to another doc where we describe each property in more detail, I'm not sure what we should do here.
Thanks for your input.

Instructions to install Supply Chain Security Tools - Store

---

install.md

Since the cluster image policy is a necessary step for the proper functioning of our webhook, we are adding these instructions to create the cluster image policy to the install docs. We currently have it in the getting started docs.

Add instructions to create cluster image policy

---

install.md

Hi there,
This PR updates the install.md page to include instructions on how to install the SCP Toolkit package.
**Note**: Install steps have essentially been copy-and-pasted from the install steps of existing components with package names updated accordingly.
**Note**: The SCP Toolkit Package has a dependency on cert manager. I've added a note to the beginning of the "Install SCP Toolkit" section referring to the official cert-manager docs for information on how to install cert-manager. I wonder if instead we want to "promote" this dependency to Prerequisites section on the "Installing Part I: Prerequisites, Cluster Configurations, EULA, and CLI" page?
Thanks!

Add SCP Toolkit to install.md

---

install-intro.md

the package plugin comes pre-installed so shouldn't be referenced directly in this copy.
there are other plugins that must be installed, so referring to them generally is appropriate.

remove reference to package plugin (step 4)

---

install-general.md

Mac prevents users from running software downloaded via a browser.
I've added steps to follow to work around this limitation.
I also updated a typo in the verification steps for installing cert-manager

add troubleshooting steps for mac CLI install

---

install.md

supply chains depend on a few pre-requisite packages.
app live view does as well...
so moved those packages above so they'll already be installed when the user gets to installing supply chains and app live view

re-order package installs based on dependencies

---

install.md

Username should come before password. This tripped a few of us up when copying and pasting credentials into this example.

Fix ordering of kp_default_repository secrets

---

install.md

If these namespaces do not exist, then the installation will fail.

Application Live connector_namespaces must exist

---

install.md

Allow creating k8s resources without having to put them in a file then `kubectl apply -f ...`.  I left this out of any of the ones where you have to replace a variable with a value pulled from the environment, but could apply those if desired. 
I probably would make a single command to pull the value then apply it, which would take a bit longer to test out, but would like to get the others in before bug bash.

simlify applying k8s resources

---

install.md

SCST - Store has a known issue where we do not allow users to the change database passwords between deployment. I warn the user in install instructions and link to the known issue doc.

Update install instruction to warn of known issue

---

install.md

The section for the source-test-to-url SupplyChain is currently a duplicate of the previous section.

Fix source-test-to-url supplychain instructions

---

install.md

remove ".com" from kp_default_repository as technically if user replaced EXAMPLE-REGISTRY with their reg url it means there be a .com on the end!

remove ".com" from kp_default_repository

---

install.md

Revamp steps 1 and 2 for the CNR installation:
* Remove references to TKG, speak about "existing Contour installations" generically
* Un-merge step 1  into two steps (install packages, gather values schema). It flows a lot better now that the schema values have detailed descriptions and defaults.
* Clearly outline the two special conditions (local cluster, existing contour) for specifying `cnr-values.yaml`, and note that the defaults are fine for all other situations
Incorporates feedback from https://jira.eng.vmware.com/browse/TANZUSC-344 and others.

Update CNR installation guide

---

install.md

Per user reports, sometimes it takes more than 15 minutes to install the CNR package due to a large number of images and occaisonaly registry slowness / errors. This manifests as a reported timeout followed by subsequent installation success when verifying the install.

Extend timeout for CNR install to 30 minutes

---

install.md

we recently updates the values schema to account for two things:
1. providing detailed information about each field (like,
`service_account and templates_namespace`)
2. introducing `templates_namespace` for configuring where
carto.run/Pipeline should look for a RunTemplate so that it works
regardless of the namespace where its submitted to.
ps.: `tempaltes_namespace` is only available in the latest version (as
of .. right now :sweat_smile:) of the package:
- registry.tanzu.vmware.com/default-supply-chain-testing/source-test-to-url@sha256:9558ebbb8423ef3c2ce0600c82c496ece3efcf58fdfb911be304784e189bb479
Signed-off-by: Ciro S. Costa <ciroscosta@vmware.com>

default supply chain: update value schema

---

getting-started.md

with the previous tekton pipeline, we wouldn't be able to get a full
test run given that `golang` image doesn't hava the necessary tools
(jdk ..), so here I update it to run the tests based of `gradle` and
then calling `./mvnw` (which is present in the workload's repo).
```
Pipeline/tanzu-java-web-app
Conditions
5m32s Ready True
5m32s RunTemplateReady True
PipelineRun/tanzu-java-web-app-4ftlb
Conditions
5m5s Succeeded True
TaskRun/tanzu-java-web-app-4ftlb-test-gvd7h
Conditions
5m5s Succeeded True
Pod/tanzu-java-web-app-4ftlb-test-gvd7h-pod-nf572
Phase  Succeeded
Container/place-tools
- 2021/10/05 16:29:02 Copied /ko-app/entrypoint to /tekton/tools/entrypoint
-
Container/place-scripts
- 2021/10/05 16:29:03 Decoded script /tekton/scripts/script-0-wn8pg
-
Container/step-test
...
- …
```

getting-started: update outputs; fix test pipeline

---

install.md

This step should have been removed in my previous PR https://github.com/pivotal/docs-tap/pull/188 to address #79.
However, when the commit titled _Revert "Update steps to install Application Live View"_ 
(sha `5d6a85d0b9fd332dd95d33ac57b721d673077b64`) went in,  it put this step back.

Remove step on API portal to remove image pull secret

---

install.md

* In this step of CNR installation, using `default`
for the service account is the straight forward
way to complete the installation
Co-authored-by: David Solomon <solomond@vmware.com>

TANZUSC-456 Update CNR install example

---

tap-gui/troubleshooting.md

Since our pods (for the time being) have a consistent `app=backstage` label you don't need an extra step to find which one to delete!

simplify "bounce the pod" instructions

---

install-tkg.md

the instructions provided on the TCI and TKG install pages are identicle.
They've been added to the install general page.
this change links to the consolidated instructions.
at the end of the instructions, a link will point the user back to this page

point CLI install to consolidated page (for TCE/TKG)

---

install-tce.md

the instructions provided on the TCE and TKG install pages are identicle.
They've been added to the install general page.
this change links to the consolidated instructions.
at the end of the instructions, a link will point the user back to this page

point CLI install to consolidated page

---

install-general.md

once the TKG/TCE-specific instructions for the Tanzu CLI have been followed, the next step is to use the CLI to install TAP on TKG/TCE.
This change updates the pointers to deep-link directly to that part of the installing TAP on TCE/TKG pages.
make sure these updated links will work properly on docs.vmware.com and if not, update accordingly -- thanks so much~!

updating links to point directly to next step

---

install.md

This to remind the reader to put the username and password in quotation marks, since if a value contains certain characters, the error message is not very helpful:
Error: accepts 1 arg(s), received 2
Error: exit status 1

Surround username and password with quotes

---

install-general.md

removed the reference to beta 2 for Updating the Tanzu CLI from previous TAP release so the instructions will remain durable through beta N and GA+
minor content updates as well

minor updates to inline links/header content

---

getting-started.md

Add note that you will also need service bindings and services toolkit if using service references as part of a workload declaration.
Please reformat if needed.

Update dependencies for default supply chain

---

install.md
release-notes.md

I wasn't sure about adding in the version for Services Toolkit in release-notes.md as it hasn't technically been added in although we are pretty certain that it will be v0.4.0.

Update remaining top level occurences of Services Control Plane Toolkit

---

install-general.md

Several users hit problems where they were attempting to install on a cluster with no LoadBalancer type, typically on VSphere. Mention this requirement, using the same language as here: https://docs.vmware.com/en/Cloud-Native-Runtimes-for-VMware-Tanzu/1.0/tanzu-cloud-native-runtimes-1-0/GUID-install.html#prerequisites-0

Mention the LoadBalancer requirement in the prerequisities

---

install-components.md

Updating the documentation for `local_dns.domain` based on updated package documentation here: https://gitlab.eng.vmware.com/daisy/tanzu-serverless/-/blob/main/config/kapp/package/package.yaml#L47

Clarify local_dns.domain usage from kapp package

---

install-components.md

so command copy/paste works
And removed the (optional) 2nd customize default settings step for service bindings because that's actually not possible today.

updating package name for service bindings install

---

getting-started.md

include --label flag/value so it will work with the TAP GUI
update link to point to the tanzu apps workload create command (please fix this if I've formatted the link incorrectly)
I'm trying to link it to this page: https://docs-staging.vmware.com/en/VMware-Tanzu-Application-Platform/0.3/tap-0-3/GUID-cli-plugins-apps-command-reference-tanzu_apps_workload_create.html

update first workload create command

---

install.md
scc/default-supply-chains.md

we're referring to the service account that must exist in the
developer's namespace as `default` everywhere, so, let's make sure
that's consistent.

ootb: don't override default serviceaccount

---

getting-started.md
install-components.md
install.md

hi folks,
with the updates brought in via 0.3.0-build.5 (see https://gitlab.eng.vmware.com/tap/tap-packages/-/merge_requests/146 - not merged yet), we had to update a couple things in the guides over here.
highlight: unfortunately, with the focus on the _developer_ experience of not having to target a specific supply chain (e.g., not having to specify `--type=web` vs `--type=web-test` but instead having cartographer "figuring out" which one to use under the hood, something to be implemented), we had to rollback support for having all 3 supply chains coming out of the box in the profiles and going back to documenting how operators should uninstall previous supply chains so the matching always works.
ps.: this should only be merged after build.5 is available (given the changes in `--type=` …

ootb: point at build.5; add notes about one supply chain in the cluster at a time

---

getting-started.md

Hello! This PR replaces the "Component Overview" section of the Services Toolkit Advanced Use Case with a link to our own component docs.
Note: I have used a link to a URL that doesn't currently exist (https://docs.vmware.com/en/Services-Toolkit/0.4/services-toolkit-0-4/GUID-overview.html), but that will exist once the linked documentation goes live. Is this the preferred approach when linking to docs in PRs? Or would you prefer if I were to link to the docs on the staging site?
Thanks!
Ed

Streamline Services Toolkit Advanced Use Cases

---

install.md

- This must be only the dockerhub-username
Sorry I missed this, this is an extension of https://github.com/pivotal/docs-tap/pull/472.
I'll put this draft mode for now until we're sure about it.

Fix bad dockerhub repo example value

---

developer-conventions/about.md
vscode-extension/about.md

Authored-by: Harsha Nandiwada <hnandiwada@vmware.com>

VSCode Tanzu IDE Extension no longer relies on Spring.

---

scst-scan/running-scans.md

It will no longer be necessary to delete and reapply scan CRs after a
ScanTemplate or ScanPolicy changes - a new scan will be triggered
automatically
Co-authored-by: Behrouz Soroushian <bsoroushian@vmware.com>

Remove scan note on scan policy changes

---

getting-started.md
install-components.md

This also includes renaming of clusterserviceresource to clusterresource.
Note that this is for a release of services toolkit that hasn't been cut yet and is being targetted for tap-beta4.

Update API group for service offering and resource claims

---

getting-started.md

For the beta 4 release.  Any place with  services.apps.tanzu.vmware.com/aggregate-to-resource-claims: "true" should be replaced with resourceclaims.services.apps.tanzu.vmware.com/controller: "true"

Update to approved agg role label and finalizer key

---

getting-started.md

This is required as part of the exclusive resource claims feature.
This is a feature for tap-beta4, it doesn't need to be ported back to previous versions.

Add update to resource claim cluster role as is now required

---

install-general.md

===========================================================
THIS CHANGE SHOULD ONLY BE VISIBLE FOR TAP DOCS BETA4 and above.
===========================================================
v.0.11.0 of the Tanzu CLI core includes a new feature called `context-aware-cli-for-plugins`.
The feature enables the version(s) of the CLI and plugins to be updated to match the versions of the components running on the targeted cluster.
The feature must be disabled until it's enhanced to support pulling the CLI and plugin binaries from a private registry requiring authentication.

BETA4+ DOCS ONLY -- disable context-aware

---

install-general.md

Small corrections to this page https://docs-staging.vmware.com/en/Tanzu-Application-Platform/0.4/tap/GUID-install-general.html#udpate-previous-tap-tanzu-cli
* Remove unnecessary backticks
* Update docs to reflect new tanzu-cli version
* Change v0.10.0 to v.0.12.0 everywhere
Please feel free to correct me where I'm wrong!

Remove backticks and update docs to reflect new tanzu-cli version

---

scc/ootb-supply-chain-testing-scanning.md

hi folks,
`scst` recently updated the `group` used for their custom resources, so we must have them updates in the references over here too.
notice that the `scst-scan/` is already using the up-to-date group, so we really just need the bump _here_.
thank you!
/cc @nedenwalker

scc: fix group used for scan objects

---

install-components.md
scc/ootb-supply-chain-basic.md

`kapp-permissions` used to make sense it those were permissions that
were indeed just intended for `kapp`, but now that we make use of it for
the supplychain to act in favor of the workload user, it makes sense to
not call it that.
Signed-off-by: Ciro S. Costa <ciroscosta@vmware.com>

scc: update role and rolebinding names

---

install-general.md

* corrected the versions of the plugins that should be installed (in the output from the various `tanzu plugins list` verifications)
* added the installation of the new `services` plugin
* updated instructions to properly disable the `context-aware-cli-for-plugins` feature AFTER the CLI core is updated and BEFORE plugins are installed, IF the CLI core was upgraded from a version prior to `v0.10.0`
* made some minor copy edits

fix versions, install steps, add services plugin

---

uninstall.md

folks may be storing other TAP-experimentation-related files in $HOME/tanzu --- so the current delete would remove all of those (potentially making people sad/upset). Updating so it deleted $HOME/tanzu/cli and below should help address that.

make file delete more exact for CLI removal

---

install-components.md

- Updating documentation so it can use the TAP fluxcd.source.controller.tanzu.vmware.com package instead of the manual installation

Updating fluxcd source-controller documentation

---

install-general.md

sudo isn't required on mac so removing.

remove `sudo` from CLI install on mac

---

install-tce.md

Signed-off-by: Garry Ing <ging@vmware.com>
This updates step 2 of installing kapp-controller to check kubectl context instead of setting context. This matches instructions in `./install-tkg.md`.

TCE install: Update kubectl context instructions

---

opting-out-telemetry.md

Discovered that the `kubectl` command was incorrect while testing this.
Also, added directions to restart the telemetry controllers to make sure that they don't use an incorrect cached value for a while.

Correct telemetry opt-out instructions

---

scst-scan/release-notes.md

This is relevant to all versions of scanlink.

Added known issue for java source scan.

---

getting-started.md

This pr updates the output examples of the `SERVICE-REF` column according to the new format in Tanzu Services Plugin v0.1.1. Where the position of the namespace and service instance have been inverted.

Update service-ref output of tanzu services plugin

---

scc/ootb-supply-chain-testing-scanning.md

hi folks,
here in this PR I propose that  rather than having the template inlined in our documentation, we refer people to installation w/ `tanzu package install` instead and point at the documentation that the scst team maintains so that instead of having to keep that up to date in two places, we can link to the best source of truth for that.
wdyt @xtreme-conor-nosal @nedenwalker?
thank you!
---
marking as a draft so we can gather insights from other folks beforehand.

ootb/scanning: improve scantemplate instructions

---

getting-started.md
install-components.md
install.md
learning-center/known-issues/about.md
scst-sign/configuring.md
scst-sign/known_issues.md
troubleshooting.md

Update `sct-sign` docs `v1beta1`group name references to `signing.apps.tanzu.vmware.com` from `signing.run.tanzu.vmware.com`

Update sct-sign docs with new v1beta1 group name

---

release-notes.md

the workaround doesn't work as expected so the references to it need to be removed.

rm references to self-signed cert workaround for convention service

---

getting-started.md

- also add warning to cross-namespace path as there currently is no path to having two apps consume from the same service instance across namespaces.
Which other branches should this be merged with (if any)? Beta 4 and Beta 5

Document path to have two or more apps consume from same service instance.

---

install-components.md
scc/ootb-delivery-basic.md
scc/ootb-supply-chain-basic.md
scc/ootb-supply-chain-testing-scanning.md
scc/ootb-supply-chain-testing.md
scc/ootb-templates.md

hi folks!
here I update install-components and `scc/`-specific documentation to account for the changes that we brought in with beta5.
the biggest changes are:
- **install-components**: new params (`gitops.*`) for the `ootb-supply-chain-*` packages
- **install-components**: add ootb-delivery-basic (it was missing before)
-**install-components**: bump cartographer and all ootb- versions
- **scc**: up-to-date documentation on how to make use of the gitops params that an operator sets / gets overwritten by a developer

ootb: update components documentation

---

install-general.md

We've reverted back to Tanzu CLI core v0.10.0 for TAP beta5/GA (beta4 had v0.12.0).
This was required because the v0.11.0+ include a feature that's incompatible with the Tanzu CLI plugins that are required for TAP (accelerator, apps, services).

** BETA5+ ONLY ** - update Tanzu CLI/Plugin install to reflect v0.10.0

---

scst-scan/release-notes.md

Following up from https://vmware.slack.com/archives/C02D60T1ZDJ/p1641234896490300, we have a known issue that the CVE print columns aren't getting populated.

Add note for release notes that CVE print columns aren't getting populated

---

scst-scan/release-notes.md

For the SCST scan release notes, under "CVE print columns are not getting populated" add a note for where to see full CVE results.

[SCST Scan] Add note where to see full CVE results

---

getting-started.md

Hi there,
This PR contains a few updates to the Services Journey section of the Getting Started Guide, namely:
* Update docs links to point to 0.5.0 rather than 0.4.0
* Fix formatting for some YAML
* Flesh out the exclusive claims piece
* Move the section binding of multiple app workloads to a
single service instance to improve readability
Please could this be merged into master and pushed to the staging site?
Thanks!
Ed

Updates to the Services Journey docs

---

service-bindings/about.md

We are not supporting the ProvisionedService resource as part of the TAP API. It will be removed in a future release.

Drop ProvisionedService resource

---

install.md

The grype.targetImagePullSecret is to pull application images to be scanned by the supply chain, not to pull the scanner image itself. Clarify that this might not be the same as tap-registry if apps are pushed to a different registry than where the TAP system components are pulled from.
This is applicable to GA (main) and beta-4 branches

Clarify image scan secret description

---

install-components.md

This is a typo because "ootb-supply-chain-testing-values.yaml" is for a file in the previous section and "ootb-supply-chain-testing-scanning-values.yaml" will be used in the next step.
I'm running thru install step, that's how I ran into this issue.

Typo in install-components section "Install Out of The Box Supply Chain with Testing and Scanning"

---

release-notes.md

Scan 1.0 was included in TAP beta 4 - the features are not new for GA.
GA (main) only

Remove scan features from GA release notes

---

release-notes.md

In release notes, for scanning release notes for "CVE print columns are not getting populated", add this note to run kubectl describe to get severity counts and cve total.

Add to release notes to display where to find severity counts and cve total

---

scst-sign/configuring.md

- Add a note in the configuration section to explain that mixing valid and invalid credentials may prevent correct authentication.

scst-sign: note in configuration about credentials

---

scst-store/cli_installation.md

Our docs pointed to the TAP beta 4 tanzunet release in order to download the `insight` CLI. However, recently someone decided to hide that release, making it invisible to users.
We have to change the documentation to point the user to the new location.
Merge this into the main and beta-4 branches.

Change the link where to download insight CLI

---

scst-sign/configuring.md

Add indentation in yaml file so that the file renders correctly

Add indentation in clusterimagepolicy yaml

---

tap-gui/integrations.md

Added instructions according to slack discussion: https://vmware.slack.com/archives/CRHUG2VQF/p1643071499176700

How to allow non-GitHub repo for TAP GUI

---

install-components.md

In order to remediate the warning in the CLI:
Warning: resource serviceaccounts/default is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
I changed apply to create and it works the same without a warning.
Both 1.0.0 and 1.0.1

Chagned Developer namespace setup to create

---

scst-sign/configuring.md

A previous edit changed `spec:` to `spec`, breaking up the example policy

Fix example policy

---

install-components.md

Looks like we'll have to revert the change from last week where we swapped apply for create. The warning is expected and we'll just have to tolerate it. This needs to change both 1.0.0 and 1.0.1 docs. THanks.

reverting a setup dev namespace change

---

getting-started.md
install-components.md
install.md

This is more consistent with the package name in tap-packages which was a point of confusion. Also, since the package is part of the profiles, there's no need to install it separately
> Which other branches should this be merged with (if any)? 
I don't think so?

Rename `tekton` -> `tekton-pipelines`

---

install.md

Update ceip value.  Legal requirements stipulate users must explicitly select `true`.

Update CEIP value in the TAP docs

---

install-components.md
install.md
prerequisites.md
tanzu-build-service/install-tanzu-build-service.md

It appears the "lite" profile has been renamed to "light", however the TBS input for `descriptor_name` must be "lite" or it will error.
@mgibson1121 
1.0

The TBS descriptor name as an input must be "lite" instead of "light" or it will error

---

release-notes.md

ALV new features and fixes to go with tap 1.0.1
For 1.0.1. Therefore should go only in **1-0** branch i think

App Live View release notes update

---

install.md

This adds the CNRS config to the "full" and "light" profile `tap-values.yaml` config files. Without this, a `tanzu apps workload create` will fail because the app will use the default `example.com` TLD

Add CNRS config so we have a domain for apps

---

.gitignore
install.md
tanzu-build-service/install-tanzu-build-service.md

1.0
- Update install instructions for automatic dependency updates in TBS component install docs
- Update install instructions for automatic dependency updates in full and lite profiles
This is a consolidation of https://github.com/pivotal/docs-tap/pull/842 and https://github.com/pivotal/docs-tap/pull/843 as well as adding info for lite profile. These PRs can be closed in favor of this one.

Tbs enable auto updates details

---

scst-sign/install-scst-sign.md

Fix API domain for SCST Sign to "signing.apps.tanzu.vmware.com"

Fix API domain for SCST Sign

---

install.md

- This field should be explicitly configured. Defaulting it to true can cause breaking changes.
1.0

Do not default enable_automatic_dependency_updates to true

---

scst-sign/install-scst-sign.md

Documentation for new feature in 1.1.0 for configuring self-signed CAs during installation of SCST - Sign Image Policy Webhook.

docs: SCST - Sign docs for self-signed CA configuration

---

scst-scan/explanation.md

Which other branches should this be merged with (if any)? main
This is a follow-up from https://github.com/pivotal/docs-tap/pull/929. We were told to do changes on main but since this is a follow-up, I didn't want to create merge conflicts. But moving forward I will try to do main changes primarily.

Fix typo for scst-scan explanation page

---

scst-store/add_data.md

Added caveat to help users add SBOMs from non-source commit or image file types

---

tap-gui/cluster-view-setup.md

Since the addition of the supply-chain plugin in 1.1.0, there are a bunch more resource types that tap-gui will be querying for. In order to avoid a bunch of 403 errors cluttering up the runtime resources page, it'd be a bit better if users gave more permissions to tap-gui's service account.
Which other branches should this be merged with (if any)? None, I think; this is brand-new in 1.1.0.

add supply-chain objects to k8s-reader role

---

install-tanzu-cli.md

updating document to add imgpkg to the path. imgpkg is needed in the install for performing TAP image relocation from Tanzunet to other Container Registries.

Update install-tanzu-cli.md to add imgpkg to the $PATH

---

release-notes.md

Added a feature deprecation note for Supply Chain Security Tools - Scan API version
Signed-off-by: Monica Chao <monicac@vmware.com>
This is applicable only for Docs 1.1.x

VSEE-460 | Deprecate `scanning.apps.tanzu.vmware.com/v1alpha1`

---

tanzu-build-service/install-tbs.md

- This user input should still be 1.0.0 even when running tap 1.0.1/2
This only needs to be merged into 1-0 branch

tbs standalone descriptor name

---

install-tanzu-cli.md

This change should be applied to TAP v1.0.0+

fix cli core *update* installation instructions

---

install-tanzu-cli.md

Document how to load CA certificates into `kapp-controller`. With the switch to recommending image relocation, users with registries secured by a private CA will fail to install the package repository or packages due to certificate trust issues.
(Validated on `kind` with an on-cluster registry created by https://github.com/evankanderson/k8s-private-local-registry)
TAP 1.0, which also contains the image relocation instructions.

Document how to enable kapp-controller to operate on relocated images in a registry with a private CA Certificate

---

tap-gui/cluster-view-setup.md

this corresponds to the fix for [TANZUSC-990](https://jira.eng.vmware.com/browse/TANZUSC-990).
Which other branches should this be merged with (if any)? Only 1.1.0 is affected

add imagerepositories to sample role

---

getting-started.md

despite the fact that the `testing` out of the box supply chain being
the one where tests get run according to the definition of a Tekton
pipeline that the developer creates, all the supply chains have a stage
in it where a tekton taskrun is created, thus, all supply chains have a
dependency on tekton.
more specifically, regardless of inner or outerloop flows, the supply
chains at the very end create this taskrun that either:
- does a `git push`, if in outerloop gitops flow
- does an `imgpkg push`, if in innerloop flow
the dependency on tekton for all supply chains is not new, being a
requirement since pre 1.0.0.

getting-started: mention Tekton as dependency for all supply chains

---

overview.md

Which other branches should this be merged with (if any)? all branches for TAP 1.1+
this checkmark needs to be set because tap-auth is also in view profile in TAP 1.1. it was decided to not change this after code freeze so we will change it (and also change the docs) for version 1.2.
Cc: @Manifaust

add checkmark to view profile for tap-auth/default roles

---

install-components.md

Update RBAC directions in namespace setup to explain service account and developer access to namespaces

---

convention-service/install-conv-service.md
install.md

- update convention-controller install to define `ca_cert_data` field
- define shared values under the `shared` top-level key
At the moment there is a single shared top-level key. More are expected
over time as packages have common bits of configuration that can be
centralized, but are not deserving of a stand-alone top-level key.

Define shared values

---

scst-scan/samples/public-image-compliance.md
scst-scan/samples/public-source-compliance.md

Fixing typos in scan image sample doc and removing duplicated information
This is meant for: 
* TAP 1.0
* TAP 1.1

SCST - Scan Docs Imporvements

---

scc/install-ootb-delivery-basic.md
scc/install-ootb-sc-basic.md
scc/install-ootb-sc-wtest-scan.md
scc/install-ootb-sc-wtest.md
scc/install-ootb-templates.md
scc/install-scc.md

Bump the versions of the SCC component to the final ones:
- carto: 0.3.0
- ootb:  0.7.0
The changes here are specific to TAP v1.1+

scc: bump versions to final versions

---

scc/building-from-source.md
scc/git-auth.md
scc/gitops-vs-regops.md

here I propose modifying the structure of the documentation that
relates to gitops in the following manner:
```
/scc
/git-auth			details about how to create the k8s secrets,
key pairs, etc related to git auth referenced
in multiple places
/building-from-source		focus on how one can build from source
code that comes either from a git
repository or local directory
/gitops-vs-regops		focus on how one might publish the
configuration produced by the supply
chain to either a git repository or an
image registry
/pre-built-image		talk about the new capability of
bringing your own container image
(see `scc:pre-built-image`)
```
this way, we can speak about the details of each different twist that
can be performed w/ regards to the supply chains depending on certain
workload config / tap …

scc: refactor gitops-related content

---

scc/pre-built-image.md

- add to the `scc/ `directory a new section called _Pre-built images_ that focuses on the new functionality out of OOTB supply chains included in TAP 1.1.0 that lets folks provide pre-built container images in their Workload definitions. 
This section is meant solely for TAP v1.1+

scc: add pre-built image section

---

scc/authoring-supply-chains.md

- add to the `scc/` directory a new section called Authoring Supply Chains that focuses on providing guidance for TAP customers on how to modify / bring their own supply chains / templates
This section is meant solely for TAP v1.1+

scc: add authoring supply chains section

---

scc/ootb-supply-chain-basic.md

Doesn't make the document perfect, but cleans it up to the point that it should be able to be followed without any missing steps or errors.
Summarizing the changes: 
- Cleaned up introduction to explain what gitops method provides more concisely
- Provided an example of what the ssh-key looks like (didn't put in known hosts as I guess that could change and I'm honestly not sure if it's required, I added what I thought was correct and it just kept updating for me automatically because I did it wrong)
- Added directions to add the secret to the service account
- Correct the example repsitory_prefix to use SSH instead of Git
- Corrected values to have dot notation instead of underscore to be consistent

Clean Up GitOps Supply Chain documentation

---

scc/ootb-supply-chain-basic.md
scc/ootb-supply-chain-testing-scanning.md
scc/ootb-supply-chain-testing.md

- authn/authz: make use of the `workload` and `deliverable` ClusterRoles
instead of providing the full Role
- overview: mention the dual capabilities of the ootb-sc packages (from
source vs pre-built images)
- basic: update the namespace setup to account for the placeholder
secret for `tap-registry` secret as, without it, one wouldn't be able
to have kpack/image etc running as they'd point at a serviceaccount
that wouldn't provide pull secrets for tanzunet
note that we're able to remove a bunch of information about gitops
because those sections are now covered under #1083 
the changes here are for TAP v1.1+

scc: update ootb-scc-*

---

install-tanzu-cli.md
install.md
multicluster/reference/tap-values-build-sample.md
tanzu-build-service/tbs-about.md

- This field defaults to false and has been a source of confusion. We want to remove
it from the main install examples/flows and only make information about it
available in more specific use-cases.
- Also remove the requirement to accept the TBS EULA which is not required.
This should be merged into main and 1-1 for the TAP 1.1 docs and for future versions.

Remove enable_auto_updates config from main install examples

---

scc/git-auth.md
scc/gitops-vs-regops.md

in recent commits, Ryan Baker provided some great suggestions for the
previous gitops section that I incorporate here in this commit, more
specifically:
- showcasing the full secret with credentials redacted
- being clear about `git-ssh` being the default name in an installation
that doesn't override that default
- better phrasing w/ regards to the need of providing credentials
regardless of whether the repository is public or not
TAP 1.1+ only

scc: incorporate suggestions from gitops cleanup

---

multicluster/reference/tap-values-run-sample.md

Which other branches should this be merged with (if any)? I think just 1.1.0 is good, which is when we introduced multi-cluster docs.

fix typo in run cluster explanation

---

tap-gui/troubleshooting.md

Help! I'm not certain that my `catalog/catalog-operations.md#-register-components` link is going to render properly. I like the idea of linking directly to a specific section in another document, but if the markdown processor that gets used to generate the real docs doesn't handle that nicely I'd be OK with just linking to the overall catalog operations page.
Back in October 2021 the claim that the TAP GUI pods aren't stateful was generally true, but since then we've exposed the "Register Entity" flow which means that the in-memory database can accumulate state that cannot be recovered after a pod gets deleted.
Which other branches should this be merged with (if any)? Since the "Register Entity" flow existed in 1.0 as well, I think this change should be made on the `1-0` branch as well. …

update "stateful pod" note

---

install.md
multicluster/reference/tap-values-build-sample.md
tanzu-build-service/install-tbs.md

This should be merged into `main` and `1-1` for the tap 1.1.x release version docs.

Update default descriptor version for tbs to 100.0.293

---

scst-sign/install-scst-sign.md

We noticed that our docs are not explicit about an additional prerequisite for  installing the SCST-Sign component.
Signed-off-by: Andrés Torres <andrest@vmware.com>
Which other branches should this be merged with (if any)? None.

Add SCST-Sign secure registry prereq

---

tap-gui/plugins/scc-tap-gui.md

Numerous questions have been asked in tap-assist about why the workload was not showing up in the visualization and this change is necessary to ensure that we don't continue to have confusion
Please push to production

Added instructions around part of label

---

install-tanzu-cli.md

link added from linux/mac and windows CLI core install instructions to the plugin install instructions.
For some reason this (critical) bit of the content (on lines 203-205) isn't showing up in the rendered public docs page 
I'm unsure why as all looks fine in the md file. Please figure out how to get that resolved.

add inline link for install/update plugins

---

install-tanzu-cli.md

fix path error for file location in Windows instructions

---

application-accelerator/vscode.md

Replaced download link for the app accelerator vscode extension

---

install-tanzu-cli.md

This change should **ONLY* be made to TAP v1.1
This change should **ONLY* be made to TAP v1.1

fix cli core install instructions

---

app-live-view/install.md
application-accelerator/install-app-acc.md
cli-plugins/accelerator/overview.md
install.md.hbs
learning-center/getting-started/learning-center-operator.md
learning-center/install-learning-center.md
multicluster/installing-multicluster.md
multicluster/reference/tap-values-run-sample.md
multicluster/reference/tap-values-view-sample.md
prerequisites.md
tap-gui/accessing-tap-gui.md.hbs
tap-gui/auth.md

TAP 1.2 when available.
This requires TAP 1.2.0-build.4, which should be built tonight.

Update usages of ingress domains to use new shared key introduced in https://gitlab.eng.vmware.com/tap/tap-packages/-/merge_requests/534

---

app-sso/about.md
install-components.md

**Draft** until:
[ ] AppSSO 1.0 docs are published to docs.vmware.com

AppSSO: bump documentation links to 1.0.0 version

---

release-notes.md.hbs

[PSTAR-623]
Not sure, it seems release notes for 1.1.2 only go into branch 1-1

Add release notes for TAP GUI 1.1.2

---

release-notes.md.hbs

This is intended for TAP 1.1.2

SCST Scan - removing known CVEs from old docs according to guidelines

---

multicluster/reference/tap-values-build-sample.md

Summary
VSEE-618 -> found an issue in #tap-assist and it was due to these docs not reflecting the 1.2.0-build.10 changes.
None

[VSEE-618] Remove scanning and put metadata store config under grype config

---

tap-gui/cluster-view-setup.md

the k8s-logging backend plugin, which powers the log viewers in RRV and supply-chain plugins, requires this permission
Which other branches should this be merged with (if any)? nope, these log viewers are new in TAP 1.2.0.

add permission for log subresource to sample role

---

release-notes.md

Which other branches should this be merged with (if any)? not sure.
At least two different teams received errors like this one. So adding this known issue about connecting to AWS EKS clusters into the general TAP known issues section

Added known issue when connecting to AWS EKS clusters

---

scc/dockerfile-based-builds.md

in tap 1.2.0, it's now possible to make use of dockerifle-based builds
by making use of a workload paramter (`--param dockerfile=...`) which
switches from the default build mechanism (kpack) to kaniko.
cc @a-peek4

scc: add entry about dockerfile-based builds

---

application-accelerator/creating-accelerators/accelerator-crd.md

Add links to Flux docs for auth and certs

---

release-notes.md.hbs

Known issue for TAP installation  on AWS EKS suggested to update to kubectl 1.24 which might not be recommended for all EKS clusters

Fix: Known issue for TAP installation 

---

app-live-view/install.md

Add details about shared.ingress_domain in ALV

---

release-notes.md.hbs

added known issue around possibility of the delivery section showing deliverables that are not relevant to the currently selected workload. 
add to main please

added known issue for SCC plug-in

---

troubleshooting.md

Our internal docs that we link to are not yet public. See internal doc changes for details.
I've guessed the URL that they will be eventually.

Adds troubleshooting link to the latest stk release.

---

release-notes.md.hbs
scst-scan/policies.md

Update scanpolicy docs to:
* Distinguish between Scan Controller ScanPolicy v1.2.0+ and before v1.2.0.
* How to get TAP GUI to view ScanPolicy
N/A

[VSEE-613] Update scanpolicy docs (TAP GUI and new scanpolicy ways)

---

scst-scan/offline-airgap.md

Modifying grype airgap docs to use patch secret to pass in grype database environment variables to the ScanTemplates.
N/A

[VSEE-631] Modifying grype airgap docs to use patch secret

---

release-notes.md.hbs

* Update release docs to distinguish between the old way and new way of configuring metadata store thru the profile yaml
** https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.2/tap/GUID-multicluster-reference-tap-values-build-sample.html -> new current way
** https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.1/tap/GUID-multicluster-reference-tap-values-build-sample.html old way
N/A

[VSEE-618] Update release docs to distinguish 1.2.0 and 1.1 and before for metadata store config

---

install-air-gap.md.hbs

Which other branches should this be merged with (if any)? N/A
Fixed TBS settings to remove settings set to default and add exclude_dependencies: true. Removed descriptor_name as TBS moved to a package as compared to pulling from Tanzu net.

Remove unneeded comment and fix tbs settings

---

getting-started/config-supply-chain.md
tanzu-build-service/tbs-image-signing.md

These articles are targeted for TAP 1.2.0.

Add Configure Tanzu Build Service to sign your image builds tutorial

---

workloads/queue.md
workloads/tcp.md

Fix tcp and queue documentation for TAP 1.2, noticed during testing.
- Both: correct links to moved and refactored files
- Both: make DEFAULT-GIT-SECRET a find&replace rather than a constant
- Queue: Fix a few missed s/tcp/queue/ replacements in the supplychain
The second and third items _could_ be backported to 1.1, but unfortunately I did them all in one commit. Sorry!

Fix tcp and queue documentation

---

getting-started/ecr.md

in TAP 1.2.x support for IaaS authentication has been added to several
components. In this commit I introduce a minimal reference of how to
have TAP setup for it.
the changes are solely for TAP 1.2.x
/cc @ryan-a-baker

Getting-started: add ECR section

---

scst-scan/install-snyk-integration.md

Fixing indentation issues in the yaml snippets in the snyk integration page. 

fixing snyk snippets indentation

---

scst-scan/observing.md
troubleshooting-tap/troubleshoot-components.md

Update the VSE troubleshooting scanning docs with:
* get logs from scan-pod 
* kubectl-describe sourcescan or imagescan
* tanzu workload command to get all logs from containers
N/A

[VSEE-649] Update VSE troubleshooting scanning docs

---

scst-scan/install-snyk-integration.md

Adding clarification in the different ways to configure Snyk with the Supply Chain Security Tools - Store deployment. 

VSEE-661 - Changing docs for Snyk Scanner Integration with Store

---

multicluster/reference/tap-values-build-sample.md
scst-scan/install-scst-scan.md
scst-scan/upgrading.md

* Follow-up from https://jira.eng.vmware.com/browse/TANZUSC-1404, in the build profile yaml starting from 1.2.0, we need to add:
```
scanning:
metadataStore:
url: "" # Disable embedded integration since it's deprecated
```
This will disable configuring metadata store thru scanning component.
* Show the scanning configuration of metadata store before v1.2.0 and v1.2.0 and after.
1.2 and main

[VSEE-610] Add scanning config to disable embedded metadata store

---

scst-scan/install-scst-scan.md
scst-scan/observing.md
scst-scan/offline-airgap.md

* Call out both metadata store url and metadata store ca secret need to be defined or not
* Add troubleshooting section to make sure `ns_for_export_app_cert` is properly defined
* Add quick typo fix for airgap docs
1.2 and main

[VSEE-638] Add troubleshoooting for ca secret could not find

---

cli-plugins/tanzu-cli.md

Update CLI plugins to match versions with the ones shipped with TAP v1.2

docs: Updating cli plugins list

---

application-accelerator/install-app-acc.md

- This should go to main and to docs for TAP 1.2

Update default for server.service_type to be ClusterIP

---

getting-started/add-test-and-security.md.hbs
scc/ootb-supply-chain-testing-scanning.md
scst-scan/policies.md
scst-scan/samples/public-image-compliance.md
scst-scan/samples/public-source-compliance.md
scst-scan/upgrading.md

Changing sample scan policy to account for edge cases. 
Fixing typo present in the sample scan policy. 

VSEE-669 | Updating scan policy to fix typo and make it more accurate.

---

release-notes.md.hbs

1.2.1 and main (anything going forward)

VSEE-676 Added maven support. Java source using Gradle still affected.

---

tap-gui/non-standard-certs.md

Don't think this doc existed in 1-1. Shouldn't be relevant for TAP 1.3.x, so I think it's just 1-2.

Fixes indentation in TAP GUI ca certs overlay

---

workloads/queue.md
workloads/tcp.md

Discovered a documentation gap from a user: https://vmware.slack.com/archives/C02D60T1ZDJ/p1658979039776139?thread_ts=1658892571.820349&cid=C02D60T1ZDJ
TAP-1.2

Add documentation for ca_cert_data key for users with private registry certs

---

getting-started/set-up-services.md

- We arent getting the latest compatibility of rmq as it bumps its
version.
Which other branches should this be merged with (if any)? 1.2.0

Download the latest rabbitmq for GSG.

---

learning-center/troubleshoot-learning-center.md

This change applies to all TAP versions, because I modified the troubleshooting section

Showing how to get the portal logs at Learning Center

---

scst-policy/configuring.hbs.md
scst-policy/migration.hbs.md

Adding a caution for some behavior that should be highlighted.
This can also be cherry-picked for 1.2.x docs.

Add caution when clusterimagepolicy not defined

---

release-notes.hbs.md

SCST-Scan did not have a new build for the TAP 1.2.1 release, so just carried forward known issues from prior release

SCST - Scan updates to release notes for TAP 1.2.1

---

release-notes.hbs.md

Summary:
* Carry over grype issue which hasn't been resolved
* Add resolved issue for fluxcd
main

[VSEE-690] Add release docs for scanning/grype for TAP 1.2.2

---

getting-started/consume-services.hbs.md
getting-started/set-up-services.hbs.md

Hi there,
This PR adds links to recently-added GCP and Crossplane use cases for Services Toolkit / Services on TAP.
Which other branches should this be merged with (if any): TAP 1.2 / 1.2.1 / 1.2.2

Add links to GCP and Crossplane CSP use cases

---

install.hbs.md
tap-gui/install-tap-gui.hbs.md

Updated documentation for the ingressDomain (hostname) references in
- `Installing Tanzu Application Platform package and profiles` page ( `Full profile` section )
- `Install Tanzu Application Platform GUI` page  ( `Procedure` section )

Updated ingressDomain references

---

api-auto-registration/usage.hbs.md

Adding some CORS related info to the api auto registration feature.
Which other branches should this be merged with (if any)? TAP 1.3

Adding CORS Documentation

---

getting-started/add-test-and-security.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scst-scan/install-carbonblack-integration.hbs.md
scst-scan/install-snyk-integration.hbs.md
scst-scan/observing.hbs.md
scst-scan/policies.hbs.md
scst-scan/samples/public-image-compliance.hbs.md
scst-scan/samples/public-source-compliance.hbs.md
scst-scan/upgrading.hbs.md

Updated sample scan policies to include a "part-of" label and added troubleshooting section adding in the label if 'Policy not defined" is encountered in the GUI' 
Which other branches should this be merged with (if any)? main and cherry-pick to 1.2 docs please

VSEE-671 Updated Scan Policies and added additional troubleshooting section

---

tap-gui/non-standard-certs.hbs.md

I elected to update the instructions as well, including how TAP GUI certs
interact with TAP certs. We could probably have these docs in a more centralized
place though.
Just 1.3

Removes old extra ca-certs docs from TAP GUI section

---

release-notes.hbs.md

Hi!
This PR adds the release notes for Services Toolkit for TAP 1.3.
NB: The release notes contain links to the Services Toolkit component documentation. I've used the staging links for now - is there a process for ensuring those staging links become production links once the TAP docs go live? Or will we need to open another PR for that?
Thanks!
Ed

Add release notes for STK 0.8 (TAP 1.3)

---

tap-gui/cluster-view-setup.hbs.md

Updates TAP GUI service account permissions on build/run

---

scst-scan/install-carbonblack-integration.hbs.md

because CBC uses CycloneDX
None, this is intended for the 1.3 release.

CBC scanner: SPDX -> CycloneDX

---

release-notes.hbs.md

This MR adds release notes for TAP 1.0.4, which is due to be made available on September 13, 2022. This patch release only contains one small change, which is a bump to the Services Toolkit package in order to address a CVE. As such, I simply copied the release notes for TAP 1.0.3, then modified them slightly for TAP 1.0.4 (adding a specific note about the fix for the CVE for Services Toolkit).
Ref https://gitlab.eng.vmware.com/services-control-plane/services-toolkit/-/issues/374
Which other branches should this be merged with (if any)? None.

Add release notes for STK for TAP 1.0.4

---

scst-store/ingress-multicluster.hbs.md

On an existing cluster, getting the AUTH_TOKEN fails with invalid base64 input as there can be more than one secret with the specified annotation, this change uses the secret referenced in the service account.
This should also be merged with the 1.2 branch.

fix: getting the AUTH_TOKEN fails if there are multiple secrets with the same annotation

---

prerequisites.hbs.md

This should be added to 1.2 branches and up

Containerd must be used in place of docker as the runtime on eks

---

cartographer-conventions/reference/convention-resources.hbs.md

Minor change to remove odd spacing on text to be linked to resource.

remove odd spacing in convention resources

---

intellij-extension/about.hbs.md

Which other branches should this be merged with (if any)? None, windows support was only added on Tap 1.3

Added windows support in overview for IntelliJ plugin

---

authn-authz/overview.hbs.md
authn-authz/role-descriptions.hbs.md
getting-started/about-consuming-services.hbs.md
release-notes.hbs.md

This PR adds information about the new "Service Operator" user role, which is available as of TAP 1.3. Note that I have not included updates to the [Detailed role permissions breakdown](https://github.com/pivotal/docs-tap/blob/main/authn-authz/permissions-breakdown.hbs.md) page as I believe this page is due to be either reworked or removed in the near future (cc @dherbrich).

Add docs for service-operator role

---

release-notes.hbs.md
scst-policy/configuring.hbs.md

This is for TAP 1.3.0
- Added release notes (features, version update, resolved issues)
- Added documentation on `static.action` `pass` and `fail` authorities
- Added documentation on `mode`s `warn` and `enforce`.

Policy Controller 1.1.0

---

scc/install-ootb-sc-basic.hbs.md
scc/install-ootb-sc-wtest-scan.hbs.md
scc/install-ootb-sc-wtest.hbs.md

TAP does not read the fields gitops.user_name or gitops.user_email This replaces those references with the proper TAP values gitops.username and gitops.email

Match docs to actual parameters

---

cert-mgr-contour-fcd/install-cert-mgr.hbs.md

* while installing contour with this doc, I was running into problems with the pkgi not reconciling. Turns out, the two example pkgis for contour don't have the same SA name. I copied the first one, and didn't realize that the sa name was different.
main

contour install docs: sync sa name in example pkgis

---

tap-gui/cluster-view-setup.hbs.md

instead of assuming the run cluster being configured is at index 0, the updated command will grab the CA data from the correct cluster by specifying the cluster name

Update sample command to setup CLUSTER_CA_CERTIFICATES

---

release-notes.hbs.md

- k8s 1.24 supported by TAP entirely
- memory requirements are not features
This goes into TAP 1.3

appsso: remove some "new features" in release notes

---

spring-boot-conventions/reference/CONVENTIONS.hbs.md

Once conventions are applied the `conventions.apps.tanzu.vmware.com` label is expected rather than the new API `conventions.carto.run`
```
metadata:
annotations:
ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
spec:
template:
metadata:
annotations:
services.conventions.apps.tanzu.vmware.com/mysql: mysql-connector-java/8.0.29
labels:
services.conventions.apps.tanzu.vmware.com/mysql: workload
```

update label added to the service intent conventions

---

cert-mgr-contour-fcd/install-cert-mgr.hbs.md
learning-center/local-install-guides/deploying-to-kind.hbs.md
release-notes.hbs.md
troubleshooting-tap/troubleshoot-install-tap.hbs.md

* a default parameter in TAP for Contour has changed in TAP 1.3.0, which can cause some issues when installing on Kind

Update tap docs and release notes for new contour default

---

spring-boot-conventions/reference/CONVENTIONS.hbs.md

For  `PodIntent` we expect applied conventions to reference the group `conventions.carto.run` 
```metadata:
annotations:
apps.tanzu.vmware.com/debug: "true"
apps.tanzu.vmware.com/live-update: "true"
autoscaling.knative.dev/maxScale: "1"
autoscaling.knative.dev/minScale: "1"
boot.spring.io/version: 2.7.3
conventions.carto.run/applied-conventions: |-
developer-conventions/debug-convention
developer-conventions/live-update-convention
developer-conventions/add-source-image-label
spring-boot-convention/spring-boot
spring-boot-convention/spring-boot-web
spring-boot-convention/service-intent-rabbitmq
appliveview-sample/app-live-view-appflavour-check
developer.apps.tanzu.vmware.com/image-source-digest: dev.registry.pivotal.io/app-live-view/test/kdv-smtp-gateway-source:latest@sha256:7ec4eb40b3e8fba …
```

update pod intent labels

---

about-package-profiles.hbs.md
install.hbs.md
scst-policy/migration.hbs.md

This change is intended for TAP 1.3.0 and 1.2.2.

Exclude image policy webhook

---

getting-started/set-up-services.hbs.md

This change is for TAP 1.3 and beyond.

Add Openshift info to Services getting started guide

---

scst-store/create-service-account-access-token.hbs.md

Signed-off-by: Garry Ing <ging@vmware.com>
Fixes an issue with the `annotations` key in the yaml not being nested under `metadata`. This is for kubernetes 1.24+.
cc @miketeve @Manifaust

Insight/Store: Fix Service Account creation yaml indentation

---

api-auto-registration/about.hbs.md
api-auto-registration/key-concepts.hbs.md
api-auto-registration/usage.hbs.md

Any ideas why the "Using App Accelerator Template" header [in this page](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.3/tap/GUID-api-auto-registration-usage.html) is not being formatted correctly? I don't see any syntax error.

Fix the header links

---

getting-started/config-supply-chain.hbs.md
scst-policy/configuring.hbs.md

Signed-off-by: Andrés Torres <andrest@vmware.com>
Only v1.3 is needed.

Add an exception policy to tap-packages images

---

migrate-profile.hbs.md

I am not sure on how to remove all the references to migrate documentation from TAP Docs. Hence creating this PR to request for the removal.
Docs for 1.2 as well should not have the migration documents. It was supposed only in TAP 1.1 when the new profiles were introduced to support for the customers to migrate from light to iterate profile after an upgrade from TAP 1.0 to 1.1.

Remove the Migrate from 1.3.0 Docs

---

workloads/web.hbs.md

The workload type is set via label. Setting an annotation will not work.
This change should be applied as far back as this file existed in a Docs-tap TAP release.
In other words - an annotation has never been used to set the workload type. It's always been a label.

fixing incorrect recommendation to use annotation

---

install-air-gap.hbs.md

* Removes ingressEnabled: true
* Fixes app_config indentation across the board
* Removes app.baseUrl backend.baseUrl and backend.cors.origin as these values can as of 1.3 be inferred from the ingress value.
* Adds required token to the gitlab integration config
* Adds explanations for GITLABURL and GITLAB-TOKEN
* Adds backend.reading.allow section with GIT-CATALOG-URL
I think this is the first TAP version to have these docs? They certainly can't be directly merged in because I deleted the app.baseUrl section and that's only relevant to 1.3. Let me know if I should make MRs that target older versions

Fixes concerns about TAP GUI airgap installation instructions

---

aws/aws-resources.hbs.md
aws/install.hbs.md
aws/set-up-namespaces.hbs.md
cartographer-conventions/troubleshooting.hbs.md
fluxcd-source-controller/about.hbs.md
fluxcd-source-controller/install-fluxcd-source-controller.hbs.md
install-intro.hbs.md

This PR will add installation docs that are specific to installing TAP on AWS.
Fully realizing this is duplicating a lot of documentation.  Has been agreed upon with the docs team and have ideas for resolving this with future doc enhancements.

Add AWS Install Documents

---

troubleshooting-tap/troubleshoot-using-tap.hbs.md

add min supported version of aws-cli

---

scst-store/create-service-account-access-token.hbs.md

Signed-off-by: Garry Ing <ging@vmware.com>
Context: I've been stepping through 1.3 installation and got to the [access token retrieval step](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.3/tap/GUID-scst-store-create-service-account-access-token.html#getting-the-access-token-3). Currently, the command returns the following on Kubernetes 1.24:
```
Error from server (NotFound): secrets "null" not found
```
This is a temporary solution, replicating the segmented blocks of before 1.24 and 1.24 (and later).
@Manifaust @julia-pu

SCST-Store/Insight: Fix access token retrieval command for Kubernetes 1.24

---

getting-started/about-consuming-services.hbs.md
getting-started/set-up-services.hbs.md

Hi - this change adds a note to recommend installation of the official rabbitmq operator provided by VMware, rather than the open source version. However the guide continues to use the open source version for sake of simplicity and getting started.
Which other branches should this be merged with (if any)? 1.2, 1.1 and 1.0

Recommend official rmq operator in GSG

---

scc/ootb-supply-chain-testing-scanning.hbs.md
scst-scan/observing.hbs.md
scst-scan/policies.hbs.md
scst-scan/triaging-and-remediating-cves.hbs.md
toc.md

Which other branches should this be merged with (if any)? main and 1.2.x branches
- If there are any merge conflicts, the purpose of this pull request was to move the "CVE triage workflow" from `scc-ootb-supply-chain-testing-scanning` to `scst-scan` as well as update links.

VSEE-754 | Moved CVE triage and remediation section to scst-scan

---

release-notes.hbs.md
scc/building-from-source.hbs.md

docs: Update supply chain docs to include the new maven flags

---

release-notes.hbs.md

There can be an issue with workloads not deploying correctly on Openshift due to SecurityContextConstraints. It was discovered as part of TANZUSC-2003, and we are trying to get out a workaround for TAP 1.3.0.
The appropriate troubleshooting steps to resolve are getting [added to the CNR docs themselves](https://gitlab.eng.vmware.com/daisy/cloud-native-runtimes-for-vmware-tanzu/-/merge_requests/131), and the link should work once the docs are published.
Is it okay to link to CNR docs through here? Or should I have the troubleshooting steps in this repo as well?
Side note: is it okay to link TANZUSC and vmware gitlab repos in here?
Which other branches should this be merged with (if any)? None, just main, to eventually become 1.3

cnr known issue on openshift

---

application-accelerator/configuration.hbs.md

Update accelerator ssh URL in configuration section

---

install-air-gap.hbs.md

Because Store takes its values from shared TLK
This is related https://jira.eng.vmware.com/browse/TANZUSC-2045
Merge into main branch, this only applies 1.3

Remove metadata store ingress values from example for Air gap install

---

install.hbs.md
release-notes.hbs.md

- Combine "kubernetes_distribution" key with the other shared keys
- fix SCST - Sign deprecation notice to be under it's own header instead of inside Scan's section

Small formatting changes

---

app-live-view/configuring-apps/convention-server.hbs.md
app-live-view/configuring-apps/steeltoe-enablement.hbs.md
application-accelerator/configuration.hbs.md
application-accelerator/creating-accelerators/accelerator-yaml.hbs.md
application-accelerator/creating-accelerators/creating-accelerators.hbs.md
application-accelerator/troubleshooting.hbs.md
cli-plugins/apps/command-reference/commands-details/workload_create_update_apply.hbs.md
cli-plugins/apps/command-reference/commands-details/workload_get.hbs.md
cli-plugins/apps/command-reference/commands-details/workload_list.hbs.md
cli-plugins/apps/create-workload.hbs.md
cli-plugins/apps/usage.hbs.md
fluxcd-source-controller/install-fluxcd-source-controller.hbs.md
getting-started/add-test-and-security.hbs.md
getting-started/deploy-first-app.hbs.md
intellij-extension/getting-started.hbs.md
multicluster/getting-started.hbs.md
scc/building-from-source.hbs.md
scc/gitops-vs-regops.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scc/ootb-supply-chain-testing.hbs.md
scc/pre-built-image.hbs.md
vscode-extension/getting-started.hbs.md
vscode-extension/live-hover.hbs.md

This commit also changes the examples to use tanzu-java-web-app instead of spring-petclinic, because spring-petclinic is not part of the accelerator repository.
This is only for 1.3

Update links to use new accelerator repository

---

prerequisites.hbs.md

updated to show the supported K8s versions to include v1.24
1.3 Branch should have this change.

updated to show the supported K8s versions to include v1.24

---

application-accelerator/configuration.hbs.md

Fix typos in accelerator configuration section

---

scst-policy/overview.hbs.md

Update the link in the policy controller documentation to link to the Tanzu Build Service image signing documentation.

Update link to Tanzu Build Service image signing from scst-policy overview

---

install-aws.hbs.md
install.hbs.md
telemetry/deployment-details.hbs.md

Which other branches should this be merged with (if any)? This change is from all releases before and including 1.3

Remove more references to installing telemetry with a profile

---

tanzu-build-service/dependencies.hbs.md

this is TAP 1.3 only
replaces https://github.com/pivotal/docs-tap/pull/1646

Update buildpack versions for tap 1.3

---

scc/parameters-reference.hbs.md

A lot of the parameters that apply to the underlying objects created according to the supplychains are scattered across multiple sections - this commit attempts at centralizing them in a single page such that one can more easily find them according to the difference resources that the most complete supply chain (ootb-supply-chain-testing-scanning) has.
jira: https://jira.eng.vmware.com/browse/TSCC-68

scc: add reference page listing all scc parameters

---

application-accelerator/configuration.hbs.md
getting-started/create-app-accelerator.hbs.md

* _Getting Started Guide_ - Add mention of GitOps capabilities as a Note under the "Using an accelerator manifest" section to improve feature discovery
* _Accelerator Docs_ - Add additional functional context regarding how manifests are handled when used in a GitOps process.
1.3 +

Adding additional context & callouts for setting up & discovering GitOps functionality with Accelerators

---

getting-started/consume-services.hbs.md
services-toolkit/about.hbs.md

Hi there,
This is a small PR to update links to the Services Toolkit Component documentation to refer to the latest release (0.8) for TAP 1.3.
**Note** These are staging links and will need to be updated to production links once our component documentation goes live (at the same time as the TAP 1.3 docs)
Also quick question - would it be possible to get a "latest" URL for our component docs, so that we don't have to update these links each time we cut a new release?
Thanks!
Ed

Update STK component docs links

---

partials/_full-deps.hbs.md

Very small change. The installation steps will fail without this change.
1.2 could also have this change

If the tag is included in relocation it will fail

---

scc/ootb-supply-chain-testing-scanning.hbs.md

In the sample `tap-values.yaml` provided, the `scanning` section should be set as a field of `ootb_supply_chain_testing_scanning` rather than a sibling as it's a field that's configured in the
`ootb-supply-chain-testing-scanning` package.
e.g., inspecting the `ootb-supply-chain-testing` package's schema:
```console
k get pkg -n tap-install ootb-supply-chain-testing-scanning.tanzu.vmware.com.0.10.0 -o yaml | vim -
```
we can see:
```
scanning:
properties:
image:
properties:
policy:
default: scan-policy
description: |
Name of the default ScanPolicy object to use to evaluate the results of scanning a container image.
type: string
template:
default: private-image-scan-template
description: |
Name of the default ScanTemplate object to use to scan a container image.
type: string
type: object …
```

scc: fix misindented section in `ootb-supply-chain-scanning` sample `tap-values`

---

app-sso/about.hbs.md
app-sso/crds/authserver.md
app-sso/getting-started/provision-auth-server.md
app-sso/platform-operators/configuration.md
app-sso/service-operators/index.md
app-sso/service-operators/storage.hbs.md
toc.md

Which other branches should this be merged with (if any)? TAP 1.4 only.
Feature targeted for TAP 1.4 release.

AppSSO: add docs for configuring AuthServer storage.

---

cert-mgr-contour-fcd/install-cert-mgr.hbs.md

This change is intended to be in TAP 1.3.1, and TAP 1.4.x. [TANZUSC-2055](https://jira.eng.vmware.com/browse/TANZUSC-2055) has more information.
If I understand correctly, by specifying 1-3-1 and main below, it will get merged to both?
Which other branches should this be merged with (if any)? main, 1-3-1

TANZUSC-2055: update contour docs to reflect new version

---

release-notes.hbs.md
upgrading.hbs.md

- Users who installed TAP 1.0 or 1.1 will have issues upgrading to TAP 1.3
- Users should follow a workaround to upgrade
- Fresh installs of TAP 1.3 or fresh installs of TAP 1.2 that are upgraded to TAP 1.3 are unaffected
- This will not be an issue in TAP 1.3.1
This is only relevant for TAP 1.3.0
Jira: https://jira.eng.vmware.com/browse/TANZUSC-2069

Add workaround for known issue with upgrading TAP

---

install.hbs.md

* Some users may assume the ingress domain dns has to be configured before installation which is confusing because that may not be possible until after the installation
* main

Adds Ingress Domain explanation

---

release-notes.hbs.md

Update release notes to link to new troubleshooting guidance for loading metadata store.
This change applies to the release notes of 1.3.0. I think 1.3.1 also has release notes for 1.3.0, so we should apply to those two branches. It does not apply to 1.4.0.

Link to troubleshooting for metadata store error

---

tanzu-build-service/openshift.hbs.md

- Adds details about what tbs configures when installing on openshift
This should be for all 1.3.x docs

Add custom scc tbs installs with

---

scc/parameters-reference.hbs.md

Similarly to how we have a reference for the parameters that can be set for workloads, here I introduce a section for Deliverable objects such that folks willing to customize some of the behaviors associated with the objects that get instantiated as a result of applying a `Deliverable` to a cluster that has `ClusterDelivery` installed (from `ootb-delivery-basic`) know what their options are.

scc: add entry reference for deliverable parameters

---

upgrading.hbs.md

updated procedure to use new repo name in case of Cluster essentials >=1.2
TAP 1.3.x

updated procedure to use new repo name

---

install-air-gap.hbs.md
install-aws.hbs.md
install-openshift.hbs.md
install.hbs.md
scst-policy/known-issues.md

The change has to be added in the following TAP versions:
1. 1.4
2. 1.3.0
3. 1.3.1
cc: @elfotografo007 @derwei @dherbrich @DennyHoang

Excluded policy controller in TAP 1.3+ installation

---

release-notes.hbs.md

Adds workaround info for a known issue with eventing package during a TAP profile upgrade. Relates to [TANZUSC-2057](https://jira.eng.vmware.com/browse/TANZUSC-2057)
1-3-0
1-3-1

add eventing known issue to the release notes

---

about-package-profiles.hbs.md

Retroactive update starting with 1.2 and up.
Closes pivotal/acc-release#429

Remove App Accelerator column

---

tap-gui/troubleshooting.hbs.md

Removed troubleshooting section pertaining to recreating a workload if the supply chain has changed or isn't present. This issue has been fixed in 1.3.1 so I removed it from the troubleshooting section

removed section

---

cloud-native-runtimes/install-cnrt.hbs.md
eventing/install-eventing.hbs.md
release-notes.hbs.md

TAP 1.3.1 includes CNR 2.0.2, which resolves an issue with Openshift.
Corresponding CNR docs changes here: https://gitlab.eng.vmware.com/daisy/cloud-native-runtimes-for-vmware-tanzu/-/merge_requests/143
Which other branches should this be merged with (if any)? none, just 1-3-1

make note of resolved issue

---

vscode-extension/troubleshooting.hbs.md

This change applies to 1.3.1 and newer. So please apply change to 1.3.1 and main branch.

Document 'UnsupportedClassVersion' workaround for vscode live-update

---

workloads/using-functions.hbs.md

Updating the missing param for deploying the function type of workload successfully
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Should be cherry picked to both 1.3.0 and 1.3.1 docs.

Updating the missing param

---

upgrading.hbs.md

updating the upgrade steps to refer to appropriate repo name
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.3.1

upgrade steps to refer to appropriate repo name

---

vscode-extension/troubleshooting.hbs.md

All branches after 1.3.1 so I think that means 1-3-2 and main.

Document IntelliJ 'corrupted launch config' workaround

---

release-notes.hbs.md

Change CVEs resolution docs to VMware required format.

---

install-air-gap.hbs.md
install-aws.hbs.md
install-openshift.hbs.md
install.hbs.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? n/a
Make the docs more clear that the tap-values.yaml is stored as a kubernetes secret.
cc: @miketeve

Add note of how tap-values is stored as a kubernetes secret

---

troubleshooting-tap/troubleshoot-using-tap.hbs.md

This should be ported to TAP 1.3 docs.

add "Builder default is not ready" item

---

release-notes.hbs.md

Under Known issues in 1.3.1 for Supply Chain Choreographer plug-in, please add these two lines to the 1.3.2 section:
- The image provider stage is not correctly reporting status failures and is instead showing a green status when it should not. This does, however,       stop the supply chain execution
- Image Provider logs are not appearing in the Stage Details section if the build fails. The logs are, however, available through the cli.

Update 1.3.2 cherry pic

---

release-notes.hbs.md

Adding a note on the LC known issues
Due to a security improvement in Learning Center, session.objects, environment.objects and session.patches are not working properly. VMware resolved this issue by Learning Center `v0.2.4` in TAP 1.3.2. 
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1-3-0 1-3-1

Learning Center issue in TAP 1.2.2

---

learning-center/troubleshoot-learning-center.hbs.md
release-notes.hbs.md

Adding a note on the LC known issues and Troubleshooting page
Due to a security improvement in Learning Center, session.objects, environment.objects and session.patches are not working properly. VMware resolved this issue by Learning Center v0.2.4 in TAP 1.3.2.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? no

Learning Center issue in TAP 1.3.0

---

release-notes.hbs.md

Adding the support for TKGs with vSphere8
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? Has to go into TAP 1.3.2 release notes alone. 

Adding the support for TKGs with vSphere8

---

app-sso/platform-operators/configuration.md

Only for 1.4.
Tagging @mamachanko for visibility.

appsso: fix typo, clarify default_authserver_clusterissuer

---

partials/scst-scan/_offline-airgap.hbs.md

Summary:
* Updating grype airgap docs to reflect 1.4 changes.
N/A

[VSEE-565] Update grype airgap docs

---

release-notes.hbs.md

Summary:
* Add security fix for python for grype scanner.
N/A

[VSEE-793] Add python security fix for grype scanner

---

application-accelerator/creating-accelerators/accelerator-crd.hbs.md

Add gitImplementation property for Accelerator CRD docs

---

partials/_view-package-config.hbs.md
scst-scan/observing.hbs.md

Summary:
* Add troubleshooting docs for incorrect configured self-signed cert.
N/A

[VSEE-837] Add troubleshooting docs for incorrect configured self-signed cert

---

prerequisites.hbs.md

updating the supported K8s versions for TAP 1.4.0
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1.4.0 only.
Refer to https://confluence.eng.vmware.com/pages/viewpage.action?pageId=789919969 for the supported K8s versions for TAP releases.

updating the supported K8s versions for TAP 1.4.0

---

app-sso/service-operators/storage.hbs.md

Improves instructions on applying a Redis CA certificate for AuthServer storage

---

aws-resources.hbs.md

Need to upgrade to version 1.23 of EKS, which also brings in the requirement to add the EBS CSI Driver.

Update K8S Version and EBS CSI Driver

---

install-aws.hbs.md

Repository must exist before relocating images.
Should go in 1.3 and 1.4

Adds instruction to create ECR repository

---

intellij-extension/troubleshooting.hbs.md
vscode-extension/troubleshooting.hbs.md

Please cherry pick to all previous branches.

extensions: add timeout error to troubleshooting

---

app-sso/app-operators/tutorials/securing-first-workload.hbs.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.3, TAP 1.4

Fixes minimum TAP version requirement bug for AppSSO+workloads doc

---

app-sso/service-operators/identity-providers.hbs.md

appsso: remove the "experimental" mention for LDAP idps

---

multicluster/getting-started.hbs.md
release-notes.hbs.md

- Added breaking change note regarding rename of deliverable TSCC-144
- Added resolved issues for TSCC-144 and TANZUSC-2682
- Updated multicluster documentation to reflect changed name of deliverable TSCC-144
None. This currently only applies to 1.4.0+

Update for external_delivery fixes for 1.4.0

---

upgrading.hbs.md

A short recommendation on the order of operation for a multicluster upgrade.
This is to address an issue testers saw when they upgraded build cluster before view cluster when upgrading from 1.3 to 1.4.
Please merge into `main`.

Order of operation for multicluster upgrade

---

release-notes.hbs.md

Because of new APIs in the metadata store to support new 1.4 features for Security Analysis GUI, we need to use the read-write access token instead of the read-only access token when configuration the GUI to talk to metadata store.
This doc warns about those breaking changes and the highlights the new configuration.

Warn of breaking changes for GUI->Store configuration

---

external-secrets/getting-started.hsb.md

This commit is for TAP 1.4.0.  It does not need to be backported to earlier releases.

Indicate that the External Secrets Operator package is ALPHA software

---

release-notes.hbs.md

Since this is for TAP 1.4, I believe this is only needed for the main branch.

Adds release notes for SA GUI for TAP 1.4

---

scc/gitops-vs-regops.hbs.md

**This should backport to 1.2 and 1.3**

Explain why https creds required for pr flow

---

tap-gui/plugins/application-accelerator-git-repo.hbs.md

Update docs to specify VS Code in turning off optional git repo creation

---

about-package-profiles.hbs.md

showing Namespace provisioner as per profiles
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1.4.0

showing Namespace provisioner as per profiles

---

app-sso/app-operators/tutorials/securing-first-workload.hbs.md

The `client.yaml` file in the sample application has the following format:
```
#@ load("@ytt:data", "data")
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
name: #@ data.values.workload_name
namespace: #@ data.values.namespace
spec:
authServerSelector:
matchLabels:
name: #@ data.values.auth_server_name
```
This means that the client registration will try to match the authorization server based on the label called "name" and not the name of the resource.
This is especially confusing because in the documentation for [Provision an AuthServer
](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-app-sso-getting-started-provision-auth-server.html) the resource name (i.e my-authserver-example) and the label "name" (i.e …

SSO: Clarify instructions for securing workload

---

vscode-extension/using-the-extension.hbs.md

This fixes one more reference to this not being possible that was missed in PR https://github.com/pivotal/docs-tap/pull/2095
Just main, for tap 1.4

Doc update: Vscode Debugging and Live update possible together

---

vs-extension/troubleshooting.hbs.md

This documents an issue found late today in the Visual Studio plugin.  It describes how to workaround not being to delete workloads in namespaces other than `default`.

Add namespace notes for VS plugin

---

release-notes.hbs.md

There is a vulnerability (CVE-2022-4378) that requires customers to know how to patch/mitigate at the host level. Adding a note to our release notes regarding that.

Add note in release notes about cve-2022-4378

---

app-sso/crds/clientregistration.hbs.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.5

Adds configuring public clients docs for AppSSO ClientRegistration CRD

---

scst-scan/install-prisma-integration.hbs.md

I made a few changes:
1. Fixed the title of the page to match what the Snyk and CB Scanners say. 
2. Made sure the scanner was marked as Alpha instead of Beta.
3. Updated the version of the package from 0.1.0-beta.8 to 0.1.4-alpha.1 (Updated release of the Prisma Scanner for TAP 1.4)

Updated with Prisma Scanner Version for 1.4 TAP

---

scst-scan/install-prisma-integration.hbs.md

Made the following changes
* adjust prisma imgpkg copy command to the correct url
* adjust prisma scanner version to latest alpha, 0.1.4-alpha.3
* remove install instructions and replace with a pointer to the general install another scanner doc
1-4-0, 1-4-1

Prisma scanner updates for alpha 3 package update

---

getting-started/add-test-and-security.hbs.md
getting-started/deploy-first-app.hbs.md
multicluster/getting-started.hbs.md
scc/building-from-source.hbs.md
scc/gitops-vs-regops.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md
scc/ootb-supply-chain-testing.hbs.md

Revise relevant `tanzu apps workload create` examples to not use the tanzu-java-web-app repository

---

namespace-provisioner/reference.hbs.md

added "reference guide" to page title because this page, rather than the overview, was coming up first in searches for "Namespace Provisioner"
TAP 1.4+

H1 page title change

---

namespace-provisioner/about.hbs.md

The reference guide, instead of this page, was coming up in rank order 1 of search results for "Namespace Provisioner" because this page included "overview" in the title. This should fix that.
TAP 1.4+

remove "overview" from H1/Title

---

scst-scan/install-prisma-integration.hbs.md
toc.md

* added instructions for finding the latest version
* added scan policy example utilizing scan passed fields from output
* updated limitations to remove ECR is no longer supported (supported in latest alpha)
* corrected docker login sample with correct registry
* added example prisma values using access keys
* updated TOC with name to align with other scanners and page title
1-4-0, 1-4-1

prisma scanner updates

---

learning-center/getting-started/learning-center-operator.hbs.md
learning-center/install-learning-center.hbs.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1-4-0

Adding the new policyEngine setting on Learning Center docs

---

cli-plugins/apps/tutorials.hbs.md

This troubleshooting step only applies to TAP v1.0 and earlier (there is no `cli/manifest.yaml` at all in the CLI binaries downloadable from TAP 1.1+).

rm troubleshooting (only applies to <= TAP 1.0)

---

release-notes.hbs.md

added resolved issue for image provider stage failure but build logs are now displayed
This needs to be merged into the 1.4 release notes.

urgent update to Resolved issues

---

release-notes.hbs.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 
- This note is only for users who upgrade from TAP 1.3 to 1.4. I believe this should be the only branch necessary. Only other one that I can think of is the 1-4-0 branch.

Add a note about the SA GUI dashboard may be empty after an upgrade

---

release-notes.hbs.md

Targeted for TAP `1.5.x`
---
* None
* Ack

Mention upgrade to cert-manager 1.11.0 in the release notes

---

release-notes.hbs.md

Add release notes for TAP GUI for TAP 1.4.1

---

README.md
about-package-profiles.hbs.md
cartographer-conventions/about.hbs.md
cartographer-conventions/creating-conventions.hbs.md
cartographer-conventions/reference/cluster-pod-convention.hbs.md
cartographer-conventions/reference/convention-resources.hbs.md
convention-service/about.hbs.md
partials/_view-package-config.hbs.md
release-notes.hbs.md

In 1.5.x Convention Controller is fully deprecated and removed from TAP builds 
- update examples to ensure relevance to current API in use 
- remove any references to the convention controller component
- ensure that  the controller resource is referenced as the convention service's controller to avoid confusion with the deprecated convention controller component 
Changes targeted for the 1.5.x0-dev branch as Convention Controller will be fully deprecated in TAP 1.5.0

remove convention controller references

---

release-notes.hbs.md

This bump also happened in TAP 1.4.0, but I don't know if it was mentioned in the release notes. Is there a process for like a retroactive release note amendment? If so, this release note also belongs in 1-4-0. Or at least in the 1.4.0 section of the 1-4-1 release notes page.

Update release notes about Contour bump

---

app-sso/app-operators/register-an-app-with-app-sso.hbs.md
app-sso/app-operators/tutorials/securing-first-workload.hbs.md
app-sso/service-operators/index.hbs.md
app-sso/service-operators/issuer-uri-and-tls.hbs.md
app-sso/service-operators/workload-trust-custom-ca.hbs.md
app-sso/troubleshoot.hbs.md
toc.md

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.4.x and TAP 1.5.x

Adds docs for Workloads trusting custom CAs for AppSSO AuthServer

---

release-notes.hbs.md

* Known issue with domainmappings, see https://vmware.slack.com/archives/C02D60T1ZDJ/p1677064059759279
This is also a problem in the TAP 1.4.x line. Can it be added to the 1.4.0 section of the release notes?

update known issues for CNR

---

tanzu-build-service/dependencies.hbs.md

This makes the docs update corresponding to
https://github.com/pivotal/build-service/pull/1058
PHP version is untouched (this comes from tbs-dependencies tile)
None. This is for 1.5 only
Closes https://github.com/pivotal-cf/tanzu-buildpacks/issues/156

tbs/dependencies: update buildpack versions for TAP 1.5

---

install-openshift.hbs.md

updated the correct K8s versions for OpenShift 4.12 with TAP 1.5

updated the correct K8s versions for OpenShift

---

prerequisites.hbs.md

updated the K8s and OpenShift versions for TAP 1.5

updated the K8s and OpenShift versions for TAP 1.5

---

release-notes.hbs.md
scc/authoring-supply-chains.hbs.md
scc/carvel-package-supply-chain.hbs.md
scc/git.hbs.md
scc/ootb-supply-chain-basic.hbs.md
scc/ootb-supply-chain-reference.hbs.md
scc/ootb-template-reference.hbs.md
scc/workload-reference.hbs.md
toc.md

This PR is for TAP 1.5 only.
We introduced a new guide on how to use this workflow at scc/carvel-package-supply-chain.hbs.md. I'm not sure if that was the right spot or if there should be separate guides for operator/developer, so let me know if there's anything that I need to correct! Thanks.

Add docs for using ootb-supply-chain-basic Carvel Package Workflow

---

app-sso/service-operators/configure-authorization.hbs.md
app-sso/service-operators/identity-providers.hbs.md

Add caution note about requesting roles/groups scope from upstream OpenID provider

---

install.hbs.md

We need this change in 1.5 and main branch.

fix: META-991 - Updated Doc to get ingress cert from ClusterIssuer

---

getting-started/create-app-accelerator.hbs.md

This is for TAP 1.5 and also 1.4 docs

Add link to docs for acc server URL

---

intellij-extension/about.hbs.md
vs-extension/about.hbs.md
vscode-extension/about.hbs.md

Add a note to VSCode, IntelliJ and Visual Studio plugins pages to indicate the carvel package new supply chains are not supported

Note that plugins are not compatible with carvel package sc

---

integrations/spring.hbs.md
toc.md

- Add instructions for using ACS to inject configuration into an existing Spring app to allow service discovery.
> Note: this is topic is still partial. Spring Cloud Gateway
documentation should be coming shortly.
These changes are for TAP 1.5 only. It doesn't appear that there is a `1-5` branch yet, so I don't think they need to be cherry picked.

Add a new topic for Spring workloads in TAP

---

release-notes.hbs.md

docs: Update namespace provisioner and apps plugin release notes

---

namespace-provisioner/about.hbs.md
namespace-provisioner/ootb-supply-chain.md
namespace-provisioner/use-case1.md
namespace-provisioner/use-case3.md
namespace-provisioner/use-case4.md

Updates the namespace provisioner docs for TAP 1.5

---

release-notes.hbs.md

API UIDs can not be found by API Auto Registration
This bug is also present in TAP 1.4.x and this commit should be cherry-picked for 1-4-2 branch

Add API Auto Registration know issue to release notes

---

prerequisites.hbs.md

adding TKGs support starting from vsphere8
1.5.0 live docs
1.5.1 branch

adding TKGs support starting from vsphere8

---

namespace-provisioner/legacy-manual-namespace-setup.hbs.md
namespace-provisioner/provision-developer-ns.md

Can you please check that the link I've added actually clicks through to the sub-section of the page it's targeting?
It's hard for me to know since I can't view it in the staging/live context. Thank you!
Please cherry pick these changes back to TAP 1.5

Add link to additional users setup from NSP ns setup

---

scc/azure.hbs.md
scst-store/additional.hbs.md
scst-store/connect-to-database.hbs.md

This change will need to go into respective branch for the following TAP releases:
TAP 1.5.1 (`1-5-1`)
TAP 1.4.5 (unavailable at the time of creating this MR)
TAP 1.3.8 (unavailable at the time of creating this MR)

Update Store Docs for TAP 1.5.1, 1.4.5, 1.3.8

---

release-notes.hbs.md

In TAP 1.5.1 there is a bug with the scst store, AMR deploy does not work. 
I was told to make a doc JIRA and update the release notes with this issue. I've made this [JIRA ticket](https://jira.eng.vmware.com/browse/TAAP-1432), please let me know if this is correct or if it's another JIRA I should be making

Specify amr deploy bug in 1.5.1 release notes

---

app-live-view/improved-security-and-access-control.hbs.md
install-aws/profile.hbs.md
install-azure/profile.hbs.md
install-offline/profile.hbs.md
install-online/profile.hbs.md
install-openshift/profile.hbs.md
multicluster/reference/tap-values-view-sample.hbs.md
tap-gui/accessing-tap-gui.hbs.md
tap-gui/install-tap-gui.hbs.md

That's been the default since TAP 1.0
Any of them

Removes instructions to set service_type to ClusterIP for TAP GUI

---

getting-started/iterate-new-app-intellij.hbs.md
getting-started/iterate-new-app-vscode.hbs.md

Add information about working with gradle projects
Gradle support is only officially added for TAP 1.6. So this only needs to be merged into main branch and no cherry-picking.

Update intellij iterate section and vscode iterate section

---

services-toolkit/tutorials/setup-dynamic-provisioning.hbs.md

To deploy the RabbitMQ Cluster Operator the file name is `cluster-operator.yml`, not `.yaml`. For confirmation see https://github.com/rabbitmq/cluster-operator/releases/
All going back to `1-5-0`

Fix incorrect file extension

---

template_variables.yaml

AppSSO is erroneously published as version `4.0.0`, however `4.0.0` will be released in TAP 1.6

AppSSO - fix version for tap 1.5

---

toc.hbs.md
workloads/service-to-service-communication.hbs.md
workloads/web.hbs.md

Move service to service communication section to a separate page under "Workloads".

move service to service communication to a separate page under workloads

---

install-aws/resources.hbs.md

This content  adds context to make follow the install guide for AWS easier and less confusion.  It would be best to cherry pick back to 1.4 and 1.5.

AWS workload registries

---

install-offline/tbs-offline-install-deps.hbs.md
install-online/profile.hbs.md
partials/_full-deps.hbs.md
release-notes.hbs.md
upgrading.hbs.md

This is for the 1.6.x version line and above (does not need to be cherry picked to older versions)

Update tbs full deps install instructions

---

getting-started/add-test-and-security.hbs.md
scst-scan/scan-types.hbs.md

Adding a quick explanation for why source scan was moved to opt-in for default supply chain and placeholder for instructions on how to add source scan back in to supply chain.  This is temporary for bug bash and steps will be added within the next week.
None.  Just main branch.

Add opt-in Source Scan note

---

tap-gui/plugins/scc-tap-gui.hbs.md

A slightly modified note could be added to 1-5-0, 1-5-1, 1-5-2. The automation works slightly differently on 1.5 which would be the following block
```markdown
> **Note:** if your configuration includes a `/metadata-store` block the
> automation **will not** overwrite the proxy block you provide. In order to use
> the automation you must delete the block at
> `tap_gui.app_config.proxy["/metadata-store"]`
```
basically it omits "create the kubernetes resources for used in autoconfiguration nor will it"

Adds note to metadataStoreAutoconfiguration docs

---

getting-started/air-gap-workload.hbs.md

`1.6.x`
This change qualifies for all previous versions which document how to "Deploy an air-gapped workload on Tanzu Application Platform" in a similar fashion.

docs(air-gap-workload): simplify with write-only stringData

---

tap-gui/cluster-view-setup.hbs.md

Without this additional permission the tap-gui will have the following log entry: 
```
{"ts":"2023-06-12T20:07:09.203Z","level":"warn","meta":{"service":"backstage","type":"plugin","plugin":"kubernetes"},"msg":"Received 403 status when fetching \"/apis/scanning.apps.tanzu.vmware.com/v1beta1/scantemplates\" from cluster \"build\"; body=[{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"scantemplates.scanning.apps.tanzu.vmware.com is forbidden: User \\\"system:serviceaccount:tap-gui:tap-gui-viewer\\\" cannot list resource \\\"scantemplates\\\" in API group \\\"scanning.apps.tanzu.vmware.com\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"group\":\"scanning.apps.tanzu.vmware.com\",\"kind\":\"scantemplates\"},\"code\":403}\n]"} …
```

Add scantemplates to k8s-reader role

---

namespace-provisioner/customize-installation.hbs.md

Updating NSP document for customization options as separate headers for 1.6

updates customize installation section to separate options as headers

---

prerequisites.hbs.md

OpenShift 4.12 and 4.13 will be supported.
Vsphere 8 with Tanzu will support TKR 1.25 ~July 2023.
Only into 1.6 branch.

Update prerequisites.hbs.md for OpenShift and Vsphere with Tanzu support

---

install-tanzu-cli.hbs.md

This is the new Tanzu CLI and plugin installation instructions for TAP 1.6+
There should be two tabs which describe the installation procedure.
The content for the tabs was copied from the new Tanzu CLI docs here: https://docs.vmware.com/en/VMware-Tanzu-CLI/0.90.0/tanzu-cli/index.html 
and here's the actual markup page: https://github.com/vmware-tanzu/tanzu-cli-docs/edit/main/user-guide/index.md

Update Tanzu CLI/Plugin install instructions - this PR should include two TABS on the docs site

---

services-toolkit/how-to-guides/dynamic-provisioning-tanzu-postgresql.hbs.md
services-toolkit/how-to-guides/index.hbs.md
services-toolkit/tutorials/abstracting-service-implementation.hbs.md
services-toolkit/tutorials/setup-dynamic-provisioning.hbs.md
toc.hbs.md

This PR updates naming from "VMware Tanzu RabbitMQ" to "VMware RabbitMQ for Kubernetes" and "VMware Tanzu Postgresql" to "VMware SQL with Postgres for Kubernetes"
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? N/A

Update naming of data services

---

learning-center/workshop-content/building-an-image.hbs.md

Changing the docs to use a way to get the image id dynamically on LC

Learning Center: Command to get the image id dynamically 

---

app-sso/tutorials/service-operators/token-signature.hbs.md

`1.6.x`
This needs to be backported as far as AppSSO's documentation reaches. Ty! ❤️

docs(app-sso): don't base64-encode the token signature key twice

---

prerequisites.hbs.md

Remove TKGs support for 1.6 for now as K8s 1.25 from TKGs(vsphere 8.0.x) are not concrete yet. Will add the support back once the GA of TKGs with k8s 1.25 happens.

Remove TKGs support for 1.6 for now

---

api-auto-registration/key-concepts.hbs.md

Adds information about additional status fields for the API Descriptor

Adds information about additional status fields for the API Descriptor

---

install-tanzu-cli.hbs.md

In order to avoid the following warning from apt update command, the `arch=amd64` should be added to the `tanzu.list` file.
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://storage.googleapis.com/tanzu-cli-os-packages/apt tanzu-cli-jessie InRelease' doesn't support architecture 'i386'
```

add arch=amd64 to apt setup

---

scc/gitlab.hbs.md

This fixes a typo around yaml markup that I made on the gitlab installation doc for scc. The markup was broken, this now renders correctly when I preview on github.
No cherry-pick, just TAP 1.6.

fix markdown yaml formatting on scc/gitlab.hbs.md

---

services-toolkit/how-to-guides/dynamic-provisioning-rds.hbs.md
services-toolkit/reference/known-limitations.hbs.md

This PR updates the how-to guide for configuring dynamic provisioning of AWS RDS PostgreSQL instances with the following changes:
* Ensure the APIs used in the `Composition` match those provided by the `Provider` that we recommend
* Recommend and make use of AWS Provider Family (previously the more monolithic AWS Provider)
* Also updated the know limitation related to degradation of performance with a link to Provider Families 
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? N/A

Update aws rds how to guide

---

multicluster/reference/tap-values-build-sample.hbs.md

Summary:
* There was an accident in this commit https://github.com/pivotal/docs-tap/commit/55f383c564ef86296f0ab9df7cddad7cf121d3a8#diff-a68bbab45012ea9eb058dbae1d1788d89baa9c81a995425adfa09574316deace where `grype:` was the parent key of `metadataStore` but then in the commit the `metadataStore` was placed into the `ootb_supply_chain_testing_scanning` which is incorrect.
1.6

[VSEE-1067] Fix formatting

---

multicluster/reference/tap-values-build-sample.hbs.md

Summary:
* Remove metadataStore block because it doesn't belong to any component in this tap-values.
1.6

[VSEE-1067] Remove metadataStore block

---

application-accelerator/configuration.hbs.md
application-accelerator/creating-accelerators/accelerator-yaml-sample.hbs.md
application-accelerator/creating-accelerators/accelerator-yaml.hbs.md
partials/application-accelerator/_configuration.hbs.md

- This is for 1.6.0 docs
- This change can safely be backported to older docs as well
- this only changes the icon URL to use the current samples repo:
```
-  iconUrl: https://raw.githubusercontent.com/simple-starters/icons/master/icon-cloud.png
+  iconUrl: https://raw.githubusercontent.com/vmware-tanzu/application-accelerator-samples/main/icons/icon-cloud.png
```

Update URLs used for accelerator icon

---

services-toolkit/tutorials/direct-secret-references.hbs.md

Update the direct secret references tutorial for services toolkit to add instructions on which clusters to target if running a multicluster topology of TAP.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? TAP 1.5

Update direct secret references tutorial

---

install-gitops/sops.hbs.md

Removing basic auth flow from gitops sops

---

scalability.hbs.md

The referenced field was removed in TAP 1.5 when the backing orchestration replaced Jobs with Tekton TaskRuns. TTL was a Job-specific feature - the latest TaskRun for each ImageScan/SourceScan is retained indefinitely.

Remove Scan TTL from scalability.hbs.md

---

scst-scan/app-scanning-troubleshooting.hbs.md
scst-scan/ivs-create-your-own.hbs.md

[VSEE-1081] Fix broken link to security context info

---

tap-gui/troubleshooting.hbs.md

TAP 1.6.1 no longer needs the app-config step

---

release-notes.hbs.md

Not sure why the preview in this MR doesn't work but it does here in my repo branch https://github.com/pivotal/docs-tap/compare/main...rxl7906:docs-tap:VSEE-1117?short_path=9707337#diff-9707337ff7669eeeef77ed0ea8d0331063a18d427f3a85ac04244bd8faa19979
The workaround has been tested in an SSP env and works.
1.6.1 (aka main)

[VSEE-1117] Add release notes for supply chain bug 1.6.1 with hardcoded clusterimagetemplate

---

release-notes.hbs.md

This is for the upcoming TAP 1.6.1 release so should not be cherry-picked to any other branches.

Update versions for SCC and OOTB for TAP 1.6.1

---

install-openshift/profile.hbs.md

updated OpenShift versions

---

spring-cloud-gateway/install-spring-cloud-gateway.hbs.md

In Tanzu CLI v0.90.0 --package-name got removed in favor of --package
It should be backported to 1.6 and 1.5 as well.
Perhaps the docs team wants to verify if other parts of the documentation are also out of date in regard to this parameter.

Update Spring Cloud Gateway install command

---

app-sso/how-to-guides/service-operators/identity-providers.hbs.md
app-sso/reference/api/authserver.hbs.md

Adds display name field for OpenID and SAML providers in AuthServer CR (TAP 1.7)

---

cli-plugins/insight/triaging-vulnerabilities.hbs.md

This PR will make the message that the ability to triage vulnerabilities is alpha more prevalent than it previously was.  Please cherry pick back to 1.6.

Make alpha message more prominent

---

install-aws/profile.hbs.md
install-aws/resources.hbs.md
install-azure/profile.hbs.md
install-offline/tbs-offline-install-deps.hbs.md
install-online/profile.hbs.md
install-openshift/profile.hbs.md
partials/_full-deps.hbs.md
upgrading.hbs.md

This should be brought back to 1.6.1 and carried forward to all future versions. The current instructions will result in install failures and need to be replaced.

Fix incorrect TBS full deps docs

---

app-sso/how-to-guides/app-operators/secure-spa-workload.hbs.md
app-sso/how-to-guides/service-operators/cors.hbs.md

appsso: clarify response_type code with CORS

---

release-notes.hbs.md

Summary:
* Add release note about resolved OOTB supply chain bug concerning clusterimagetemplate not being updated for supplychain
1-6-2 only

[VSEE-1119] Add release note about resolved OOTB supply chain bug

---

app-sso/reference/api/clusterunsafetestlogin.hbs.md

Add issuerURI to ClusterUnsafeTestLogin Status API

---

scst-scan/scan-types.hbs.md

This adds a missing value to the overlay to tell image provider to use source-scan as it's test rather than source-tester, as well as fixes the indentation on the secret.  
1.6 

Fix source-scan overlay

---

app-sso/how-to-guides/getting-started.hbs.md

docs(app-sso): ClusterUnsafeTestLogin prints its issuer URI

---

install-gitops/upgrading.hbs.md

[main] Align gitops upgrade commit version with {{ vars.tap_version }}

---

install-gitops/upgrading.hbs.md

[1.6.x] Align gitops upgrade commit version with {{ vars.tap_version }}

---

app-sso/reference/package-configuration.hbs.md

TAP `1.7.x`
Please, backport to TAP `1.6.x`. Ty!

docs(app-sso): how to safely customize default_workload_domain_template

---

cli-plugins/apps/tutorials/create-update-workload.hbs.md

This change should be done for TAP 1.6

docs: Organise maven related title

---

cli-plugins/apps/create-workload.hbs.md

This change should be done for TAP 1.4 and TAP 1.5

fix: Add maven sample by using flags

---

install-tanzu-cli.hbs.md
release-notes.hbs.md
template_variables.yaml

This change should go live when TAP 1.6.3 GA's

TAP 1.6.3 - modernize Tanzu CLI & plugin install to 1.0.0

---

install-tanzu-cli.hbs.md
release-notes.hbs.md
template_variables.yaml

This change should go live with TAP 1.5.5 GA's

TAP 1.5.5 - modernize Tanzu CLI & plugin install to 1.0.0

---

install-tanzu-cli.hbs.md
release-notes.hbs.md
template_variables.yaml

These changes should go live when TAP 1.4.9 GA's

TAP 1.4.9 - modernize Tanzu CLI & plugin install to 1.0.0

---

install-tanzu-cli.hbs.md
template_variables.yaml

This change should go live when TAP v1.3.12 GA's

TAP 1.3.12 - modernize Tanzu CLI & plugin install to 1.0.0

---

application-accelerator/creating-accelerators/accelerator-yaml-sample.hbs.md

Removed the ‘toggle’ input type from Documentation

---

app-sso/how-to-guides/service-operators/token-settings.hbs.md

* Updates the `token-viewer.yaml` to the latest and greatest revision
* The token viewer can be deployed when the `restricted` Pod Security Standard is enforced
`1.7.x`
`1.4.x`
`1.5.x`
`1.6.x`
Thank you!

Up-to-date, restricted token viewer

---

scst-store/amr/graphql-query.hbs.md

feat: [AMR-616] - Update GraphQL query page to remove location Alias

---

scst-scan/clusterimagetemplates.hbs.md

[VSEE-1179] Remove trivy display report step because it is not needed

---

app-sso/how-to-guides/service-operators/configure-token-signature.hbs.md
app-sso/reference/api/authserver.hbs.md

- the minimum is 2048
[#185338123]
Please cherry-pick back to including `TAP 1.3` (`1.3`, `1.4`, `1.5`, `1.6`), and include it in the latest (`1.7`)

appsso: add signing key size constraint

---

local-source-proxy/prereqs.hbs.md
local-source-proxy/troubleshoot.hbs.md

This pull request documents ports and protocols required to run Local Source Proxy.
Specifically, it documents requiring tcp/5002 to be open between the control plane and worker nodes.
All releases that include LSP.

Document ports and protocols for LSP.

---

intellij-extension/about.hbs.md
vscode-extension/about.hbs.md

Probably just Tap 1.7 and later? 
However... this is really not specific to a version of TAP. 
The sandbox environment will most likely be kept up to date so it is always on a 'recent' version of TAP, which means that going back in time and adding a note like this into older versions of the docs makes little sense (you won't get an old version of TAP on the sandbox... and in the future once 1.8 is released you then won't even get a 1.7 version of sandbox anymore soon thereafter.

Add a pointer to Tap Sandbox from Vscode/IntelliJ about sections

---

scc/delivery-with-flux.hbs.md

This change is intended for TAP 1.7. 

Ensure a compatible version of Flux Kustomize Controller

---

scst-scan/troubleshoot-scan.hbs.md
scst-store/cluster-specific-scanner-configurations.hbs.md
scst-store/multicluster-setup.hbs.md
scst-store/upgrading.hbs.md
toc.hbs.md
upgrading.hbs.md

This is for 1.7.
The existing docs for upgrading SCST - Store only have instructions for troubleshooting. With 1.7, we introduce the AMR component. In a full profile, the AMR does not need any user configuration. However, in a multicluster TAP, the user does need to do some configuration.
In a previous PR, we had already updated the SCST - Store multicluster docs page. In this MR, we refer to those instructions by expanding the Upgrading doc and linking to the multicluster doc. After that, we also add a link to the TAP upgrading doc.

docs: 1.7 upgrade docs for store

---

scst-store/amr/configuration.hbs.md
scst-store/amr/install-amr-cloudevent-handler.hbs.md
scst-store/amr/install-amr-observer.hbs.md
scst-store/deployment-details.hbs.md

This change is for 1.7.
Back in 1.6 we had instructions for enabling AMR explicitly using a values file. Now that AMR is on by default I want to update the docs to reflect that.

Remove explicit instructions to install AMR using values

---

api-auto-registration/key-concepts.hbs.md
api-auto-registration/troubleshooting.hbs.md

The known issue listed in the overall TAP 1.7 release note might be overlooked by our users if they go straight to the troubleshooting section of our product. So I added a troubleshooting section that has the reworded version of the known issue.
None

Add tokenRelay field, add the known issue back to troubleshooting section

---

release-notes.hbs.md

These changes are for the 1.7.0 release

add missing release notes for app config service

---

release-notes.hbs.md
scst-scan/troubleshoot-scan.hbs.md

Add release notes to mention docker fields and related sub-fields are deprecated/removed in TAP 1.7

---

scst-scan/install-scst-scan.hbs.md

Add metadataStore properties, remove certIssuer and KubeRbacProxy because they were removed in 1.7

---

scst-scan/install-app-scanning.hbs.md

This PR is missing the correction of the workspace.storageSize default value being 2Gi instead of 100mi which is in this [PR](https://github.com/pivotal/docs-tap/pull/3011/files) 

[Read for merge] Add note to say storage class should not have per-node limit

---

cli-plugins/insight/query-data.hbs.md

Updating this document on the updated way to fetch an image digest using tanzu cli. Also removing information about fetching source scan results, as it is not yet supported as part of the OOTB experience.
(cherry picked from commit 26e4f7b5aded3f158dbcde0c8f33b8078323e35d)
* TAP 1.5.6

feat: [AMR-552] Update the CLI "Query vulnerabilities, images, and packages" section

---

scst-scan/ivs-carbon-black.hbs.md

Summary:
* Add disclaimer for carbon black cli usage
* inline steps for carbon black configuration similar to scan 1.0
1.6

Add disclaimer, cb cli docs, and cb image reference

---

install-aws/profile.hbs.md
install-azure/profile.hbs.md
install-gitops/upgrading.hbs.md
install-offline/profile.hbs.md
install-online/profile.hbs.md
install-openshift/profile.hbs.md
multicluster/reference/tap-values-build-sample.hbs.md
release-notes.hbs.md
scst-scan/troubleshoot-scan.hbs.md
troubleshooting-tap/troubleshoot-install-tap.hbs.md
upgrading.hbs.md

* because the removed field `scanning.metadataStore.url` is provided in tap-values
* app-scanning is deployed to the cluster

[Draft] VSEE-1235 | documented the cases where upgrade fails

---

troubleshooting-tap/troubleshooting-gitops.hbs.md

Update troubleshoot to provide solution for delete-kubernetes-auth.sh for 1.6.5
NA

Update troubleshoot to provide solution for delete-kubernetes-auth.sh

---

app-sso/how-to-guides/service-operators/identity-providers.hbs.md
app-sso/reference/api/authserver.hbs.md

AppSSO: Service Ops can specify Configuration URI for OIDC provider config discovery

---

scst-scan/clusterimagetemplates.hbs.md
scst-scan/ivs-trivy.hbs.md

Differences between catalog repo [ClusterImageTemplate Trivy](https://gitlab.eng.vmware.com/supply-chain-choreographer/catalog/-/blob/main/src/ootb-templates/bundle/config/image-vulnerability-scan-trivy.yaml) and this ClusterImageTemplate Trivy sample in the Scan 2.0 docs:
* There is `registry.server` and `registry.repository` here but not in the catalog ClusterImageTemplate Trivy because it appears that in the ootb-templates there is ytt happening to populate the registry.server and registry.repository fields but we need to make sure they are populated here if a user wants to create their own ClusterImageTemplate sample.
* The `label_exclusions` in [catalog](https://gitlab.eng.vmware.com/supply-chain-choreographer/catalog/-/blob/main/src/ootb-templates/bundle/config/image-vulnerability-sc …

Update ClusterImageTemplate docs

---

api-auto-registration/troubleshooting.hbs.md

API Auto Registration depends on `kin-openapi`, which doesn't support OpenAPI v3.1 yet. This note in the troubleshooting section is temporary, [until v3.1 support is released](https://github.com/getkin/kin-openapi/issues/230).

API Auto Registration: note about unsupported OpenAPI v3.1

---

tap-gui/configurator/validated-community-plugins/about.hbs.md
tap-gui/configurator/validated-community-plugins/github-actions.hbs.md
tap-gui/configurator/validated-community-plugins/grafana.hbs.md
tap-gui/configurator/validated-community-plugins/homepage.hbs.md
tap-gui/configurator/validated-community-plugins/jira.hbs.md
tap-gui/configurator/validated-community-plugins/prometheus.hbs.md
tap-gui/configurator/validated-community-plugins/snyk.hbs.md
tap-gui/configurator/validated-community-plugins/sonarqube.hbs.md
tap-gui/configurator/validated-community-plugins/stackoverflow.hbs.md
tap-gui/configurator/validated-community-plugins/techinsights.hbs.md
tap-gui/plugins/about.hbs.md
toc.hbs.md

1.7
Notes:
* for plugin docs I linked to a lot of github pages. I wasn't sure if we prefer source code docs or npmjs pages, or something else.
* plugin version will change with future releases. It is important for customers to know which plugin version corresponds to which tap release. In the examples I provided the latest version for the 1.7 release, and noted that this is the latest version at  the time of writing. This will be improved with [ESBACK-628](https://jira.eng.vmware.com/browse/ESBACK-628)
* I've introduced some …

ESBACK-512: validated community plugins

---

release-notes.hbs.md

This is targeted for TAP 1.7 
related jira: https://jira.eng.vmware.com/browse/TANZUSC-4805

Document workaround for failed builds after upgrade

---

tanzu-build-service/tbs-workload-config.hbs.md

This is for TAP 1.7, no other branches needed.

Add example providing git credentials as workload service binding

---

scst-store/amr/data-model-and-concepts.hbs.md
scst-store/amr/graphql-query.hbs.md

Some GraphQL resources should be presented as alpha in the docs.
This applies to main and 1.7

Call out alpha GraphQL resources

---

tap-gui/plugins/about.hbs.md

added backstage <-> tap version table

---

install-tanzu-cli.hbs.md
template_variables.yaml

TAP 1.8+
With Tanzu CLI v1.1.0, we can use the MAJOR.MINOR reference in the `tanzu plugin install --group vmware-tap/default:vX.Y` command and it will always install the latest patch version for the MAJOR.MINOR version specified in the command.
This eliminates the need to update the Tanzu CLI plugin installation command docs every time a new Patch release GA's for a given Minor release line.

Create durable `tanzu cli plugin install --group....` command

---

tap-gui/cluster-view-setup.hbs.md

Allows k8s-reader cluster role to fetch CRDs for TAP Gui

---

release-notes.hbs.md

release notes: breaking change: TAP defaults to Deployment for Contour's Envoy now, causes downtime

---

release-notes.hbs.md

All TAP 1.6.x branches (1-6-0, 1-6-1, 1-6-2, 1-6-3, 1-6-4, etc)

release notes: breaking change: TAP Contour defaults to minTLS version of 1.3, may cause request failures in some infrastructures

---

aws-services/install-aws-services.hbs.md

A small fix to AWS Services install doc to clarify correct default versions for ENGINE-VERSION.
Which other branches do you want a technical writer to cherry-pick this PR to (if any)? 1.7

Fix to ENGINE-VERSION in AWS Services install

---

crossplane/reference/version-matrix.hbs.md
release-notes.hbs.md

Updates docs for new crossplane version.
The addition of the 1.7.0 row to the matrix in crossplane/reference/version-matrix.hbs.md should also be back ported to TAP 1.7. The 1.8.0 row and the update to the release notes should only exist on `main` for TAP 1.8.

Crossplane v1.14 in TAP 1.8

---

tap-gui/configurator/building.hbs.md

fixes typo replacing tanzu cmd with kubectl

---

install-openshift/profile.hbs.md

Adding 4.14 and corresponding k8s version in the install guide for OpenShift
1.7.1

Update profile.hbs.md for OpenShift 4.14

---

release-notes.hbs.md

This change applies to TAP 1.7.0 and 1.7.1.

Add CarbonBlack pod security known issue

---

api-validation-scoring/about.hbs.md
release-notes.hbs.md

This change is only for 1.7. I will be making a different MR for 1.8 to completely remove the package and its docs.
cc/ @csterwa @royclarkson

Add deprecated warning for APIx package

---

tap-gui/plugins/api-docs-getting-started.hbs.md

This section can indeed be removed.
cc @YugangW

Removing part referencing deprecated APIx package

---

install-aws/profile.hbs.md
install-openshift/profile.hbs.md

This exclusion is no longer needed, and was fixed in 1.3.2.  It was missed in removing it from openshift and aws.
1.4, 1.5, 1.6, 1.7.

Remove policy controller exclusion

---

scst-scan/install-app-scanning.hbs.md

where affinity assistance should be specifically be disabled.
please cherry pick to `main`.

VSEE-1287 | added a note to specifically call out TKGs 1.26+ as restricted cluster

---

cloud-native-runtimes/how-to-guides/app-operators/resource_management.hbs.md

* 1-7-0
* 1-7-1
* 1-7-2
* 1-7-3
---
The package no longer bundles net-istio. Cleaned out references to configuration options specific to net-istio. Additionally these specific values will always cause a deploy to fail.

Remove net-istio config options

---

authn-authz/pinniped-install-guide.hbs.md

(First PR! Apologies if I missed something.) 
The example httpproxy provided when using `tls.passthrough = true` does not follow contour's official documentation. We had to change this in our environment in order to connect to pinniped. Cross referenced this against another environment and they had made the same change (outside of TAP). 
https://projectcontour.io/docs/1.25/config/tls-termination/#tls-session-passthrough
This was tested against TAP 1.7.2, but likely needs to go to all 1.7.x 
---

Updating example for pinniped tls passthrough httpproxy

---

app-live-view/configuring-apps/convention-server.hbs.md
spring-boot-conventions/enabling-app-live-view.hbs.md

This is targeted for only TAP 1.8 release

remove deprecated appliveview-sample convention

---

scc/dockerfile-based-builds.hbs.md

The idea here is to make it more clear which values are example values and to distinguish between example values and what they mean instead using the same value for all examples.

better clarity on example values for `dockerfile-based-builds.hbs.md`

---

release-notes.hbs.md

Only for TAP 1.6.8
See gh-3219 and gh-3221.

appsso: 1-6-8 scopes fix

---

service-bindings/version-matrix.hbs.md

Add version matrix for servicebinding on tap 1.8

---

scst-store/api-walkthrough.hbs.md

The existing example uses an authenticated example which requires an access token. We should start with an unauthenticated endpoint to ease the reader.
Merge into 1.7, 1.6, 1.5, and 1.4.

Use a simple unauthenticated example to start the walkthrough

---

scst-scan/scan-types.hbs.md

A previous commit accidentally removed the secret header, which makes it more difficult for a user to apply this workaround.  Adding this back in.
Please cherry pick this to 1.6 and 1.7.

Fix source scan secret

---

about-package-profiles.hbs.md
release-notes.hbs.md
scst-scan/install-app-scanning.hbs.md
scst-scan/integrate-app-scanning.hbs.md
scst-scan/overview.hbs.md

Call out that App Scanning is now installed as part of the install profiles and does not require manual installation.  
Just main

App Scanning installed in profiles

---

install-openshift/profile.hbs.md

Update profile.hbs.md updating the versions supported

Update profile.hbs.md updating the versions supported for TAP 1.8

---

supply-chain/catalog/git-writer.hbs.md
toc.hbs.md

Introduce docs for git-writer component

---

prerequisites.hbs.md

Update prerequisites.hbs.md to add support for TKGs on VC7
Please update the https://github.com/pivotal/docs-tap/blob/1-7-4/k8s-matrix.hbs.md also accordingly. in the K8s matrix, call out TKr 1.26 and 1.27 against VC7.

Update prerequisites.hbs.md to add support for TKGs on VC7

---

multicluster/reference/tap-values-build-sample.hbs.md

In the build profile sample, there's a bullet point that describes `METADATA-STORE-URL-ON-VIEW-CLUSTER`. However, this variable no longer appears in the yaml example. So this bullet is no longer needed.
This applies to main and 1.8.

Removed unused metadata store description

---

release-notes.hbs.md
scst-store/amr/configuration.hbs.md

I changed a label that was `environment` to `env`. This is important because the DORA feature is looking for `env`.
This applies to main, 1.8, and 1.7.

Add instructions on using the `env` label when configuring AMR observer to support DORA

---

release-notes.hbs.md

Update release-notes.hbs.md to remove V8 as this applies to Vsphere with Tanzu V8 and V7.

Update release-notes.hbs.md to remove V8

---

scc/delivery-with-flux.hbs.md

- https://jira.eng.vmware.com/browse/TANZUSC-5892: users ran into issues when trying to use a kubeconfig that referenced the gcloud or aws CLIs
main

Note requirements for fluxcd kubeconfig

---

install-aws/resources.hbs.md

https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.7/tap/install-aws-resources.html
- Change the workload trust policy from "system:serviceaccount:default:default" to "system:serviceaccount:*:default"
- Change to StringEquals to StringLike
- With the above 2 allow all namespaces with default SA to access ECR.
This is becoming a 100% reproducible complaints coming from our customers when working with EKS.
Discussed internally in a slack thread.
https://vmware.slack.com/archives/C02D60T1ZDJ/p1702955025697119

Change namespace to accept to all namespaces

---

contour/how-to-guides/configuring-contour-with-loadbalancer-tls-termination.hbs.md

- The generic term is `Elastic Load Balancing`
- The create TLS certificate procedure is suggesting only the "import certificate" option which inaccurate, disallowing the "request certificate" procedure. Fixing to a more generic pointer
- By default it will create Classic Load Balancer
- Need to explicitly point to NLB (recommeded)

The example will create a classic loadbalancer and not network loadbalancer

---

install-azure/profile.hbs.md

The type of Azure LoadBalancers are defined at the time of cluster creation. The configuration here seems to be AWS specific but was copied over in error. There are currently no Azure specific settings in Contour.
* All of `1.8`
* All of `1.7`
* All of `1.6`
* All of `1.5`

[TANZUSC-5861] Remove invalid Contour configuration for Azure LoadBalancers

---

tap-gui/update-backstage-versions.sh

Slashes apparently can't be used in the template_variables. This updated script is able to produce the same variables that are currently in the template_variables file. I re-ran the script and got no diff in that file when compared to the hand modified variables that had the slashes removed.
None

Modifies the backstage versions transform to remove slashes

---

application-accelerator/creating-accelerators/using-local-engine-server.hbs.md

This is for TAP 1.8
The note section should look like this:
>**Note** For macOS users we need to do the following steps in order to open an app from an unidentified developer:
>(We are working on having these artifacts signed using an Apple developer account to avoid these extra steps)
>
>In the Finder on your Mac, locate the directory where you extracted the downloaded ZIP file and expand the "acc-engine" directory.
>
>We need to "control-open" the following files:
>
>    - control-click `acc-engine/app/bin/ytt` and then click Open. This will run it in a terminal that you can close.
>
>    - control-click `acc-engine/app/bin/java` and then click Open. This will run it in a terminal that you can close.
>
>The above app files are saved as exceptions to your security settings.
>You can now …

Attempt to fix formatting for local engine server note

---

supply-chain/reference/catalog/output-types.hbs.md

Updates the output type to match what is now output by Git Writer 0.1.3
None.

Document git PR output type

---

about-package-profiles.hbs.md
getting-started/add-test-and-security.hbs.md
scc/ootb-supply-chain-testing-scanning.hbs.md

TAP 1.8.x, grype is no longer installed through tap-values/profiles. 
Grype is now installed from Namespace Provisioner unless explicitly specified that the namespace does not have grype.

Update grype installation information

---

release-notes.hbs.md

Remove TAP version from the release notes deprecated API

---

scst-scan/tanzu-supply-chain/create-supply-chain-with-app-scanning.hbs.md
scst-scan/tanzu-supply-chain/create-supply-chain-workload.hbs.md
scst-scan/tanzu-supply-chain/scan-2-0-with-tanzu-supply-chain-overview.hbs.md
scst-scan/tanzu-supply-chain/setup-supply-chain-component.hbs.md

Summary:
* Specify "Customized Scanning Component" rather than all the other variations to reduce confusion.
* This docs PR is meant to address the comments/suggestions made in this [PR](https://github.com/pivotal/docs-tap/pull/3292#issuecomment-1952942201).
* Right now the list of prerequisites [here](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.8/tap/scst-scan-tanzu-supply-chain-create-supply-chain-with-app-scanning.html) are not separate in sections like and according to the [docs-tap readme](https://github.com/pivotal/docs-tap?tab=readme-ov-file#troubleshooting-markdown) the solution is to add a blank line after the stem sentence and before the first item in the list:
```
supplychain:
supplychain
supplychain catalog
.....
```
It's best to PR to the most …

Update app scanning supply chain docs with reviews/suggestions

---

supply-chain/platform-engineering/how-to/installing-supply-chain/installing-manually.hbs.md

This PR affects TAP 1.8 only.
The manual install instructions for Supply Chains had a dependency on `yq` but the same outcome can be achieved with kubectl and the jsonpath output method.

fix suply chain install to not use yq

---

scalability.hbs.md

Cherry-pick not needed as this is not seen earlier.

make amr-observer size example compatible with actual size recommended

---

prerequisites.hbs.md

Update prerequisites.hbs.md for including K8s 1.26 as well in 1.8.0
Please update https://github.com/pivotal/docs-tap/blob/main/k8s-matrix.hbs.md based on this MR.

Update prerequisites.hbs.md for including K8s 1.26 as well in 1.8.0

---

release-notes.hbs.md

Update release-notes.hbs.md for TAP via TMC for K8s 1.26 only.

---

install-openshift/profile.hbs.md

Red Hat OpenShift Container Platform v4.13 uses the Kubernetes version 1.26.3

Update profile.hbs.md with Openshift 4.13 for TAP 1.8.0

---

tap-gui/configurator/building.hbs.md

1.6, 1.7, 1.8
Please double check the markdown, I tried to make tabs similar to [Build your customized portal](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.7/tap/tap-gui-configurator-building.html#build-your-customized-portal-3)

Update steps to identify configurator image with newer imgpkg

---

tap-gui/configurator/create-plug-in-wrapper.hbs.md

remove --ignore-engines from tap-gui docs

---

scc/git-auth.hbs.md

Theres a typo in the docs this will lead to the following error executing the command:
```
➜  ~ ssh-keygen -t ecdsa -b 512 -C "" -f "identity" -N ""
Invalid ECDSA key length: valid lengths are 256, 384 or 521 bits
```
Update git-auth.hbs.md to fix typo on ssh-keygen command
then it works:
```
➜  ~ ssh-keygen -t ecdsa -b 521 -C "" -f "identity" -N ""
Generating public/private ecdsa key pair.
Your identification has been saved in identity
Your public key has been saved in identity.pub
The key fingerprint is:
```
Version 1.6 and 1.7 have those typos.
For more information about the branches, see …

Update git-auth.hbs.md to fix typo on ssh-keygen command

---

scst-scan/install-trivy-integration.hbs.md

This commit enhances documentation around the version of Trivy to use depending on the version of TAP that it will be installed into.

[trivy] Clarify the version of Trivy to install

---

tap-gui/plugins/dora.hbs.md
tap-gui/troubleshooting.hbs.md

- As of TAP 1.9, the plugin no longer requires authentication to display DORA metrics.
None. This is a change for TAP 1.9 only.

Remove auth references from DORA plugin docs

---

prerequisites.hbs.md

OpenShift 4.15 is GAed now. TAP 1.8.0 had not claimed the support yet RedHat had not GAed at TAP 1.8.0 GA time, but since OpenShift 4.15 is GAed now, we will add the support.
please update https://github.com/pivotal/docs-tap/blob/main/k8s-matrix.hbs.md as well with the same.

Update prerequisites.hbs.md with OpenShift 4.15 is GAed now.

---

release-notes.hbs.md

This should be part of the 1.8.x line

Appliveview known issue has been updated for 1.8.1

---

release-notes.hbs.md

This should be part of the 1.7.x line

Updated known issue for appliveview for 1.7.x

---

app-sso/concepts/grant-types.hbs.md

Target: TAP 1.9
Backport to 1.8 and 1.7

appsso: fix client credentials grant example

---

scst-scan/troubleshoot-scan.hbs.md

The fix targets all branches in release 1.7.x

Fix security context workaround

---

tap-gui/cluster-view-setup.hbs.md

1.7 (I guess that's 1-7-4 and 1-7-5)

Add a missing apigroup to 1.7 cluster view setup docs

---

tap-gui/cluster-view-setup.hbs.md

1.6 (I guess that's 1-6-8 and 1-6-9)

Add missing apigroups to 1.6 cluster view setup docs

---

scst-scan/app-scanning-troubleshooting.hbs.md
scst-scan/install-app-scanning.hbs.md

A few references to affinity assistance were missed in docs.  Cleaning up those references.
1.8

Affinity Assistant was removed in 1.8

---

aws-services/how-to-guides/index.hbs.md
aws-services/how-to-guides/troubleshooting.hbs.md
release-notes.hbs.md
toc.hbs.md

Adds a known issue for the AWS Services Package in TAP 1.8 / 1.8.1. We plan to resolve this known issue in TAP 1.8.2 / 1.9+.

Add AWS RMQ Secret Key Name known issue

---

scc/delivery-with-flux.hbs.md

- Match the Flux version with Source Controller used in delivery supply chain documentation
---
- `main` only

Flux version required for the delivery supply chain documentation

---

intellij-extension/install.hbs.md
partials/vscode-extension/_install.hbs.md

- now only available via respective marketplaces
TAP 1.8->TAP 1.5

Remove tanzunet links for IDE plugin installation

---

release-notes.hbs.md

- This issue was fixed in alm-catalog 0.1.5, which was released with TAP v1.8.1. See https://gitlab.eng.vmware.com/tanzu-application-platform/runtime-program/app-last-mile/sc-components/-/merge_requests/137
1-8-1 if necessary

fix an incorrect known issue in 1.8.1

---

tap-gui/cluster-view-setup.hbs.md

- Since TAP 1.8.0 the developer portal queries clusters for namespaces
- The role we tell customers to create lacks namespace permissions. This commit adds it.
- This change should be applied to the docs going back to v1.8.0
[TME-2630]
v1.8

Add namespace read permissions to k8s-reader role

---

release-notes.hbs.md

Summary:
* Add release note to provide workaround for the known issue of workload failing at the image scanning step when `image_scanner_template_name: image-vulnerability-scan-trivy` is specified without `image_scanning_cli.image`
1.8.2

[TANZUSC-6352] Add release note for known issue around image_scanning_cli.image

---

release-notes.hbs.md

Update release-notes.hbs.md adding N-2 upgrade support
Only into 1.9.x and above.

Update release-notes.hbs.md adding N-2 upgrade support

---

namespace-provisioner/use-case3.hbs.md

Fix the code example for SSH git auth to create the correct secret type. The example as previously written failed to reconcile, because basic auth secrets require a username and password.
This fix should apply to any branch that includes the ssh-auth secret.

Minor fix in namespace provisioner docs

---

release-notes.hbs.md

This should be cherry picked down to 1.8.2, 1.8.1, and 1.8.0.  It seems that Known issues were carried foreward incorrectly in those versions despite being resolved.

Fix Release Notes for Scan for 1.8.x

---

app-live-view/install-connector-as-a-service.hbs.md
toc.hbs.md

This is targeted for TAP 1.10.0 release

doc updates for installing connector-as-a-service

---

cli-plugins/apps/how-to-guides/integrate-lsp.hbs.md

Fixing typo on the end of the `tanzu apps local-source-proxy health` command.
Without the `  at the end it executes successfully:
````
$ tanzu apps local-source-proxy health
user_has_permission: true
reachable: true
upstream_authenticated: true
overall_health: true
message: All health checks passed
````
This typo exists on all existing versions of the documentation.
VMware Tanzu Application Platform 1.9
VMware Tanzu Application Platform 1.8
VMware Tanzu Application Platform 1.7
VMware Tanzu Application Platform 1.6

Fixed typo in  integrate-lsp.hbs.md
